In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
td_df=pd.read_csv('reviewtool_20240816_SEATTLE_Distance_Transfer_Flags.csv')
od_df=pd.read_csv('reviewtool_20240815_SEATTLE_OD_Distance_Checks.csv')

In [4]:
td_df.columns

Index(['id', 'ROUTE_SURVEYEDCode', 'PREV_TRANSFERSCode', 'PREV_TRANSFERS',
       'TRIP_FIRST_ROUTECode', 'TRIP_SECOND_ROUTECode', 'TRIP_THIRD_ROUTECode',
       'TRIP_FOURTH_ROUTECode', 'NEXT_TRANSFERSCode', 'NEXT_TRANSFERS',
       'TRIP_NEXT_ROUTECode', 'TRIP_AFTER_ROUTECode', 'TRIP_3RD_ROUTECode',
       'TRIP_LAST4TH_RTECode', 'STOP_ON_LAT', 'STOP_ON_LONG', 'STOP_OFF_LAT',
       'STOP_OFF_LONG', 'Elvis_Date_x', 'Final_Usage_x',
       'PREV_TRAN_1_ON_BUS_LAT', 'PREV_TRAN_1_ON_BUS_LONG',
       'PREV_TRAN_1_OFF_BUS_LAT', 'PREV_TRAN_1_OFF_BUS_LONG',
       'PREV_TRAN_2_ON_BUS_LAT', 'PREV_TRAN_2_ON_BUS_LONG',
       'PREV_TRAN_2_OFF_BUS_LAT', 'PREV_TRAN_2_OFF_BUS_LONG',
       'PREV_TRAN_3_ON_BUS_LAT', 'PREV_TRAN_3_ON_BUS_LONG',
       'PREV_TRAN_3_OFF_BUS_LAT', 'PREV_TRAN_3_OFF_BUS_LONG',
       'PREV_TRAN_4_ON_BUS_LAT', 'PREV_TRAN_4_ON_BUS_LONG',
       'PREV_TRAN_4_OFF_BUS_LAT', 'PREV_TRAN_4_OFF_BUS_LONG',
       'NEXT_TRAN_1_ON_BUS_LAT', 'NEXT_TRAN_1_ON_BUS_LONG',
       'NEXT_TRAN_1_OFF_BUS_LAT', 'NEXT_TRAN_1_OFF_BUS_LONG',
       'NEXT_TRAN_2_ON_BUS_LAT', 'NEXT_TRAN_2_ON_BUS_LONG',
       'NEXT_TRAN_2_OFF_BUS_LAT', 'NEXT_TRAN_2_OFF_BUS_LONG',
       'NEXT_TRAN_3_ON_BUS_LAT', 'NEXT_TRAN_3_ON_BUS_LONG',
       'NEXT_TRAN_3_OFF_BUS_LAT', 'NEXT_TRAN_3_OFF_BUS_LONG',
       'NEXT_TRAN_4_ON_BUS_LAT', 'NEXT_TRAN_4_ON_BUS_LONG',
       'NEXT_TRAN_4_OFF_BUS_LAT', 'NEXT_TRAN_4_OFF_BUS_LONG',
       'noOfTransferGPS', 'Transfer1_onroute_distance',
       'Transfer2_onroute_distance', 'Transfer3_onroute_distance',
       'Transfer5_onroute_distance', 'Transfer6_onroute_distance',
       'Transfer7_onroute_distance', 'Transfer8_onroute_distance',
       'Elvis_Date_y', 'FINAL_REVIEWER', 'Final_Usage_y', 'Transfer1_Distance',
       'Transfer2_Distance', 'Transfer3_Distance', 'Transfer4_Distance',
       'Transfer5_Distance', 'Transfer6_Distance', 'Transfer7_Distance',
       'Transfer8_Distance', 'Flaged', 'Transfer_Distance_Flag_Description'],
      dtype='object')

In [5]:
od_df.columns

Index(['id', 'Final_Direction_Code', 'Final_Direction',
       'ORIGIN_PLACE_TYPECode', 'ORIGIN_PLACE_TYPE', 'ORIGIN_ADDRESS_ADDR',
       'ORIGIN_ADDRESS_CITY', 'ORIGIN_ADDRESS_STATE', 'ORIGIN_ADDRESS_ZIP',
       'ORIGIN_ADDRESS_LAT', 'ORIGIN_ADDRESS_LONG', 'ORIGIN_TRANSPORT',
       'DESTIN_PLACE_TYPECode', 'DESTIN_PLACE_TYPE', 'DESTIN_ADDRESS_ADDR',
       'DESTIN_ADDRESS_CITY', 'DESTIN_ADDRESS_STATE', 'DESTIN_ADDRESS_ZIP',
       'DESTIN_ADDRESS_LAT', 'DESTIN_ADDRESS_LONG', 'DESTIN_TRANSPORT',
       'HOME_ADDRESS_PLACE', 'HOME_ADDRESS_ADDR', 'HOME_ADDRESS_CITY',
       'HOME_ADDRESS_STATE', 'HOME_ADDRESS_ZIP', 'HOME_ADDRESS_LAT',
       'HOME_ADDRESS_LONG', 'NEXT_TRAN_1_OFF_BUS_LAT',
       'NEXT_TRAN_1_OFF_BUS_LONG', 'NEXT_TRAN_2_OFF_BUS_LAT',
       'NEXT_TRAN_2_OFF_BUS_LONG', 'NEXT_TRAN_3_OFF_BUS_LAT',
       'NEXT_TRAN_3_OFF_BUS_LONG', 'NEXT_TRAN_4_OFF_BUS_LAT',
       'NEXT_TRAN_4_OFF_BUS_LONG', 'PREV_TRAN_1_ON_BUS_LAT',
       'PREV_TRAN_1_ON_BUS_LONG', 'PREV_TRAN_2_ON_BUS_LAT',
       'PREV_TRAN_2_ON_BUS_LONG', 'PREV_TRAN_3_ON_BUS_LAT',
       'PREV_TRAN_3_ON_BUS_LONG', 'PREV_TRAN_4_ON_BUS_LAT',
       'PREV_TRAN_4_ON_BUS_LONG', 'STOP_OFF_LAT', 'STOP_OFF_LONG',
       'STOP_ON_LAT', 'STOP_ON_LONG', 'DESTIN_ADDRESS_LAT.1',
       'DESTIN_ADDRESS_LONG.1', 'ORIGIN_ADDRESS_LAT.1',
       'ORIGIN_ADDRESS_LONG.1', 'DESTIN_TRANSPORT.1', 'NEXT_TRANSFERSCode',
       'ORIGIN_TRANSPORT.1', 'PREV_TRANSFERSCode', 'FINAL_REVIEWER',
       'ORIGIN_TO_SURVEYBOARD', 'ORIGIN_TO_FIRST_BOARD',
       'SURVEYBOARDING_TO_SURVEYALIGHTING', 'ORIGIN_TO_DESTINATION',
       'SURVEYALIGHTING_TO_DESTINATION', 'LAST_ALIGHTING_LOCATION_TO_DESTIN',
       'O2B/O2D', 'B2A/OD', 'A2D/OD', 'O_B_Dist_Check1', 'O_B_Dist_Check2',
       'O_B_Dist_Check3', 'A_D_Dist_Check1', 'A_D_Dist_Check2',
       'A_D_Dist_Check3', 'O_D_Dist_Check1', 'O_D_Dist_Check2',
       'O_D_Dist_Check3', 'B_A_Dist_Check1', 'B_A_Dist_Check2',
       'O_D_Distance_Flag_Description', 'SUM_ALL_CHECKS'],
      dtype='object')

In [6]:
new_df=pd.merge(od_df[['id','Final_Direction_Code','O_D_Distance_Flag_Description']],
                td_df[['id','ROUTE_SURVEYEDCode','Transfer_Distance_Flag_Description']],on='id',how='outer')

In [7]:
new_df

,id,Final_Direction_Code,O_D_Distance_Flag_Description,ROUTE_SURVEYEDCode,Transfer_Distance_Flag_Description
0,5640.0,SND_1_TLine_01,Origin to Destination distance is less than 0....,NaN,NaN
1,5768.0,SND_1_TLine_01,Origin to Destination distance is less than 0....,NaN,NaN
2,5832.0,NaN,NaN,SND_1_1Line_01,Distance between transfer routes is greater th...
3,5880.0,SND_1_595_00,Origin to Board distance is greater than 1.85 ...,NaN,NaN
4,5913.0,SND_1_594_01,Origin to Destination distance is greater than...,NaN,NaN
...,...,...,...,...,...
433,43032.0,SND_1_1Line_01,Origin to Board distance is greater than 1.85 ...,NaN,NaN
434,43106.0,NaN,NaN,SND_1_1Line_00,Distance between transfer routes is greater th...
435,43206.0,NaN,NaN,SND_1_1Line_00,Distance between transfer routes is greater th...
436,43209.0,NaN,NaN,SND_1_1Line_00,Distance between transfer routes is greater th...
437,43285.0,SND_1_1Line_01,Origin to Board distance is less than 0.25 mil...,NaN,NaN

In [8]:
for _,row in new_df.iterrows():
    if not pd.isna(row['Final_Direction_Code']):
        new_df.loc[row.name,'Route_Code']=row['Final_Direction_Code']
    elif not pd.isna(row['ROUTE_SURVEYEDCode']):
        new_df.loc[row.name,'Route_Code']=row['ROUTE_SURVEYEDCode']
    else:
        new_df.loc[row.name,'Route_Code']=pd.NA
    if not pd.isna(row['O_D_Distance_Flag_Description']) and not pd.isna(row['Transfer_Distance_Flag_Description']):
        new_df.loc[row.name,'Flag Description']=row['O_D_Distance_Flag_Description'] +' '+ row['Transfer_Distance_Flag_Description']
    elif not pd.isna(row['O_D_Distance_Flag_Description']):
        new_df.loc[row.name,'Flag Description']=row['O_D_Distance_Flag_Description']
    elif not pd.isna(row['Transfer_Distance_Flag_Description']):
        new_df.loc[row.name,'Flag Description']= row['Transfer_Distance_Flag_Description']
    else:
        new_df.loc[row.name,'Flag Description']=' '

In [9]:
new_df[['Final_Direction_Code','ROUTE_SURVEYEDCode','Route_Code']].head()

  Final_Direction_Code ROUTE_SURVEYEDCode      Route_Code
0       SND_1_TLine_01                NaN  SND_1_TLine_01
1       SND_1_TLine_01                NaN  SND_1_TLine_01
2                  NaN     SND_1_1Line_01  SND_1_1Line_01
3         SND_1_595_00                NaN    SND_1_595_00
4         SND_1_594_01                NaN    SND_1_594_01

In [10]:
new_df[['O_D_Distance_Flag_Description','Transfer_Distance_Flag_Description','Flag Description']].head()

,O_D_Distance_Flag_Description,Transfer_Distance_Flag_Description,Flag Description
0,Origin to Destination distance is less than 0....,NaN,Origin to Destination distance is less than 0....
1,Origin to Destination distance is less than 0....,NaN,Origin to Destination distance is less than 0....
2,NaN,Distance between transfer routes is greater th...,Distance between transfer routes is greater th...
3,Origin to Board distance is greater than 1.85 ...,NaN,Origin to Board distance is greater than 1.85 ...
4,Origin to Destination distance is greater than...,NaN,Origin to Destination distance is greater than...

In [11]:
new_df2=pd.merge(od_df[['id','Final_Direction_Code','O_D_Distance_Flag_Description']],
                td_df[['id','ROUTE_SURVEYEDCode','Transfer_Distance_Flag_Description']],on='id',how='inner')

In [12]:
new_df2

,id,Final_Direction_Code,O_D_Distance_Flag_Description,ROUTE_SURVEYEDCode,Transfer_Distance_Flag_Description
0,10078.0,SND_1_1Line_01,Origin to Destination distance is greater than...,SND_1_1Line_01,Distance between transfer routes is greater th...
1,31009.0,SND_1_1Line_00,B2A/OD (Boarding to Alighting divided by Origi...,SND_1_1Line_00,Distance between transfer routes is greater th...
2,33312.0,CMT_1_413_01,B2A/OD (Boarding to Alighting divided by Origi...,CMT_1_413_01,Distance between transfer routes is greater th...
3,34530.0,MET_1_177_00,Survey Alighting to Destination distance is le...,MET_1_177_00,Distance between transfer routes is greater th...
4,40244.0,SND_1_574_00,Origin to Destination distance is greater than...,SND_1_574_00,Distance between transfer routes is greater th...
5,40647.0,SND_1_513_00,Origin to Destination distance is greater than...,SND_1_513_00,Distance between transfer routes is greater th...
6,41203.0,SND_1_1Line_00,Survey Alighting to Destination distance is le...,SND_1_1Line_00,Distance between transfer routes is greater th...

In [13]:
new_df[new_df['id']==10078][['O_D_Distance_Flag_Description','Transfer_Distance_Flag_Description','Flag Description']]

,O_D_Distance_Flag_Description,Transfer_Distance_Flag_Description,Flag Description
31,Origin to Destination distance is greater than...,Distance between transfer routes is greater th...,Origin to Destination distance is greater than...

In [14]:
new_df[new_df['id']==10078][['Flag Description']].values

array([['Origin to Destination distance is greater than 50 miles. Distance between transfer routes is greater than 0.25']],
      dtype=object)