In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [2]:
wkday_overall_df=pd.read_excel('LACMTA_CR.xlsx',sheet_name='WkDAY-Overall')
wkday_route_df=pd.read_excel('LACMTA_CR.xlsx',sheet_name='WkDAY-RouteTotal')

In [3]:
wkday_overall_df.head(10)

,SORT,LS_NAME_CODE,LS_NAME,PARENT_LS_NAME,Agency_CR,PRE-EARLY AM,EARLY AM,AM,MIDDAY,PM,EVE,Direction Total,LS_ROUTELEVEL,LOOKUP_RTTOTAL
0,1,LAC_1_801_00,Metro A Line - Blue Line [Northbound],Metro A Line - Blue Line [Northbound],LAC,0,59.755,122.245,80.47,222.36,194.4925,679.3225,LAC_1_801,1926.463
1,2,LAC_1_801_01,Metro A Line - Blue Line [Southbound],Metro A Line - Blue Line [Southbound],LAC,0,64.67,118.6625,72.0525,241.965,199.3725,696.7225,LAC_1_801,-
2,3,LAC_1_802_00,Metro B Line - Red Line [Eastbound],Metro B/D Line - Red/Purple Line [Eastbound],LAC,0,48.26875,158.070833,284.204167,323.654167,161.727083,975.9250,LAC_1_802,2836.4
3,4,LAC_1_802_01,Metro B Line - Red Line [Westbound],Metro B/D Line - Red/Purple Line [Westbound],LAC,0,54.758333,203.33125,310.152083,321.554167,160.279167,1050.0750,LAC_1_802,-
4,5,LAC_1_803_00,Metro C Line - Green Line [Eastbound],Metro C Line - Green Line [Eastbound],LAC,0,12.4862,29.5685,62.9342,85.1464,28.4024,218.5377,LAC_1_803,603.44998
5,6,LAC_1_803_01,Metro C Line - Green Line [Westbound],Metro C Line - Green Line [Westbound],LAC,0,20.4696,55.3253,58.7919,53.2203,24.6909,212.4980,LAC_1_803,-
6,7,LAC_1_805_00,Metro D Line - Purple Line [Eastbound],Metro B/D Line - Red/Purple Line [Eastbound],LAC,0,-,-,-,-,-,0.0000,LAC_1_805,-
7,8,LAC_1_805_01,Metro D Line - Purple Line [Westbound],Metro B/D Line - Red/Purple Line [Westbound],LAC,0,-,-,-,-,-,0.0000,LAC_1_805,-
8,9,LAC_1_804_00,Metro E Line - Expo Line [Eastbound],Metro E Line - Expo Line [Eastbound],LAC,0,23.0875,55.8975,157.52,208.4725,81.2225,526.2000,LAC_1_804,1456.938
9,10,LAC_1_804_01,Metro E Line - Expo Line [Westbound],Metro E Line - Expo Line [Westbound],LAC,0,28.43,126.105,178.4,124.34,57.195,514.4700,LAC_1_804,-

In [4]:
def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [5]:
am_column_check=['am']
pm_column_check=['pm']
midday_column_check=['midday']
evening_column_check=['eve']

am_column=check_all_characters_present(wkday_overall_df,am_column_check)
pm_column=check_all_characters_present(wkday_overall_df,pm_column_check)
midday_colum=check_all_characters_present(wkday_overall_df,midday_column_check)
evening_column=check_all_characters_present(wkday_overall_df,evening_column_check)

In [6]:
new_df=pd.DataFrame()
new_df['ROUTE_SURVEYEDCode']=wkday_overall_df['LS_NAME_CODE']
# new_df['CR_Pre_Early_AM']=cr_df[pre_early_am_column[0]]
# new_df['CR_Early_AM']=cr_df[early_am_column[0]]
new_df['CR_AM_Peak']=wkday_overall_df[am_column[0]]
new_df['CR_Midday']=wkday_overall_df[midday_colum[0]]
new_df['CR_PM_Peak']=wkday_overall_df[pm_column[0]]
new_df['CR_Evening']=wkday_overall_df[evening_column[0]]

In [7]:
new_df[['CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']]

     CR_AM_Peak   CR_Midday  CR_PM_Peak  CR_Evening
0       122.245       80.47      222.36    194.4925
1      118.6625     72.0525     241.965    199.3725
2    158.070833  284.204167  323.654167  161.727083
3     203.33125  310.152083  321.554167  160.279167
4       29.5685     62.9342     85.1464     28.4024
..          ...         ...         ...         ...
235   39.901919   47.754348   62.482875   14.839447
236           -           -           -           -
237           -           -           -           -
238           -           -           -           -
239           -           -           -           -

[240 rows x 4 columns]

In [8]:
def convert_string_to_integer(x):
    try:
        return float(x)
    except (ValueError, TypeError):
        return 0

In [9]:
new_df[['CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']]=new_df[['CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']].applymap(convert_string_to_integer)

In [10]:
print(isinstance('-',str))

True

In [11]:
new_df[['CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']]

     CR_AM_Peak   CR_Midday  CR_PM_Peak  CR_Evening
0    122.245000   80.470000  222.360000  194.492500
1    118.662500   72.052500  241.965000  199.372500
2    158.070833  284.204167  323.654167  161.727083
3    203.331250  310.152083  321.554167  160.279167
4     29.568500   62.934200   85.146400   28.402400
..          ...         ...         ...         ...
235   39.901919   47.754348   62.482875   14.839447
236    0.000000    0.000000    0.000000    0.000000
237    0.000000    0.000000    0.000000    0.000000
238    0.000000    0.000000    0.000000    0.000000
239    0.000000    0.000000    0.000000    0.000000

[240 rows x 4 columns]