In [1]:
import math

In [2]:
def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate the Haversine distance between two points on the earth (specified in decimal degrees) in miles.
    """
    # Convert decimal degrees to radians
    lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])

    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    r = 3956  # Radius of Earth in miles
    return r * c

In [3]:
b_lat=33.537448
b_long=-112.099663
a_lat=33.508550
a_long=-112.075192
a_lat1=33.446274
a_long1=-112.069297

In [4]:
haversine_distance(b_lat,b_long,a_lat,a_long)

2.442365638216208

In [5]:
haversine_distance(b_lat,b_long,a_lat1,a_long1)

6.533448318810635

In [6]:
b_lat=33.537448
b_long=-112.099663
a_lat=33.446274
a_long=-112.069297

In [7]:
haversine_distance(b_lat,b_long,a_lat,a_long)

6.533448318810635

In [8]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [27]:
df=pd.read_excel('O2O MUNI.xlsx')
df.head()

,id,Completed,TIME_BOARDED,Day,TIME PERIOD,TIME PERIOD[CODE],ROUTE_DESCRIPTION[CODE],BOARD_ID,BOARD_STOP[CODE],BOARD_STOP_NAME,BOARD_LAT,BOARD_LONG,ALIGHT_ID,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME,ALIGHT_LAT,ALIGHT_LONG,TIME_BOARDED_Code_
0,45725,2024-01-22 13:53:10,1:00 am - 5:59 am,Weekday,OWL,6,MUN_1_M_00,3716.0,MUN_1_M_00_3716,Broad St & Capitol Ave,37.713152,-122.459159,3716.0,MUN_1_M_00_3716,Broad St & Capitol Ave,37.713152,-122.459159,AM1
1,45746,2024-01-24 12:38:25,1:00 am - 5:59 am,Weekday,OWL,6,MUN_1_N_00,6994.0,MUN_1_N_00_6994,Metro Montgomery Station/Outbound,37.788791,-122.402127,7217.0,MUN_1_N_00_7217,Metro Embarcadero Station,37.792590,-122.397268,AM1
2,45754,2024-01-24 20:38:51,1:00 am - 5:59 am,Weekday,OWL,6,MUN_1_M_00,6997.0,MUN_1_M_00_6997,Metro Civic Center Station/Outbd,37.778675,-122.414995,6991.0,MUN_1_M_00_6991,Metro Castro Station/Outbound,37.762683,-122.435289,AM1
3,45757,2024-01-25 03:36:14,1:00 am - 5:59 am,Weekday,OWL,6,MUN_1_T_00,7347.0,MUN_1_T_00_7347,Third Street/Gilman/Paul,37.722449,-122.395610,7401.0,MUN_1_T_00_7401,Third Street/Revere/Shafter,37.732262,-122.391502,AM1
4,45775,2024-01-29 09:02:35,4:00 pm - 6:59 pm,Weekday,PM PEAK,3,MUN_1_J_00,6997.0,MUN_1_J_00_6997,Metro Civic Center Station/Outbd,37.778675,-122.414995,6995.0,MUN_1_J_00_6995,Metro Powell Station/Outbound,37.784300,-122.407822,PM1

In [31]:
df['ROUTE_DESCRIPTION[CODE]_NEW']=df['ROUTE_DESCRIPTION[CODE]'].apply(lambda x : str(x).split('_')[-1])

In [34]:
df['ROUTE_DESCRIPTION[CODE]_NEW']=='00'

0         True
1         True
2         True
3         True
4         True
         ...
32532    False
32533    False
32534    False
32535    False
32536    False
Name: ROUTE_DESCRIPTION[CODE]_NEW, Length: 32537, dtype: bool

In [ ]:
summary_df=pd.DataFrame()
summary_df['ROUTE_DESCRIPTION[CODE]']=''
summary_df['BOARD_STOP_NAME']=''
summary_df['']=''

for _,row in df.iterrows():
    if row['TIME PERIOD[CODE]']==0 and ROUTE_DESCRIPTION[CODE]

In [26]:
period_mapping = {
    0: 'AM',
    1: 'MIDDAY',
    2: 'PM',
    3: 'PM PEAK',
    4: 'EVENING',
    5: 'NIGHT',
    6: 'OWL'
}

# Group by TIME PERIOD[CODE] and apply the lambda function
summary_df = df.groupby('TIME PERIOD[CODE]').apply(lambda x: x[['ROUTE_DESCRIPTION[CODE]', 'BOARD_STOP_NAME']])

# Rename the index using the mapping dictionary
summary_df = summary_df.rename(index=period_mapping)

# Reset index to move the TIME PERIOD[CODE] from index to column
# summary_df = summary_df.reset_index()
# summary_df = summary_df.rename(columns={'level_1': 'TIME PERIOD[CODE]'})
summary_df

                        ROUTE_DESCRIPTION[CODE]  \
TIME PERIOD[CODE]
AM                NIGHT              MUN_1_J_00
                  14                 MUN_1_J_00
                  16                 MUN_1_J_00
                  17               MUN_1_14R_00
                  18               MUN_1_14R_01
...                                         ...
OWL               21045              MUN_1_K_00
                  27421             MUN_1_5R_01
                  28611            MUN_1_28R_00
                  29708              MUN_1_M_00
                  32174              MUN_1_K_00

                                           BOARD_STOP_NAME
TIME PERIOD[CODE]
AM                NIGHT      Metro Powell Station/Outbound
                  14             Metro Embarcadero Station
                  16             Metro Embarcadero Station
                  17                   Mission St & 2nd St
                  18               Mission St & Geneva Ave
...                                                    ...
OWL               21045          Van Ness Station Outbound
                  27421               Fulton St & 30th Ave
                  28611    Park Presidio Blvd & Geary Blvd
                  29708  Metro Montgomery Station/Outbound
                  32174          Metro Embarcadero Station

[32537 rows x 2 columns]

In [20]:
result = df.groupby('TIME PERIOD[CODE]')[['ROUTE_DESCRIPTION[CODE]', 'BOARD_STOP_NAME']].count()
result

                   ROUTE_DESCRIPTION[CODE]  BOARD_STOP_NAME
TIME PERIOD[CODE]
0                                     6216             6216
1                                     7604             7604
2                                     5065             5065
3                                     8200             8200
4                                     4565             4565
5                                      497              497
6                                       31               31

In [21]:
result = df.groupby('TIME PERIOD[CODE]').apply(lambda x: x[['ROUTE_DESCRIPTION[CODE]', 'BOARD_STOP_NAME']])
result

                        ROUTE_DESCRIPTION[CODE]  \
TIME PERIOD[CODE]
0                 5                  MUN_1_J_00
                  14                 MUN_1_J_00
                  16                 MUN_1_J_00
                  17               MUN_1_14R_00
                  18               MUN_1_14R_01
...                                         ...
6                 21045              MUN_1_K_00
                  27421             MUN_1_5R_01
                  28611            MUN_1_28R_00
                  29708              MUN_1_M_00
                  32174              MUN_1_K_00

                                           BOARD_STOP_NAME
TIME PERIOD[CODE]
0                 5          Metro Powell Station/Outbound
                  14             Metro Embarcadero Station
                  16             Metro Embarcadero Station
                  17                   Mission St & 2nd St
                  18               Mission St & Geneva Ave
...                                                    ...
6                 21045          Van Ness Station Outbound
                  27421               Fulton St & 30th Ave
                  28611    Park Presidio Blvd & Geary Blvd
                  29708  Metro Montgomery Station/Outbound
                  32174          Metro Embarcadero Station

[32537 rows x 2 columns]