In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:

def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [4]:
# df=pd.read_csv('elvisdenverco2024obweekday_export_odbc.csv')
df=pd.read_csv('elvisbartca2024interceptNEW_main_export_odbc(001).csv')
filename='details_project_od_BART.xlsx'
df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ELVIS_USER_CHANGE_7_C_REASON,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,EXP_HOMELESSCode,EXP_HOMELESS,_REVERSE_TRIP,GENERATABLE_TRIPS
0,9,2024-04-08 06:09:51,83,en,2024-04-08 05:59:10,2024-06-06 03:30:02,174.249.144.185,https://bart-ca.etc-research.com/,-25200.0,999,...,\n\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11,2024-04-08 07:16:13,83,en,2024-04-08 07:07:19,2024-04-08 07:16:13,107.77.213.232,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,14,2024-04-08 08:21:40,83,en,2024-04-08 07:16:22,2024-09-07 02:29:43,107.77.213.232,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,999,...,\n\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,15,2024-04-08 07:57:27,83,en,2024-04-08 07:44:11,2024-07-04 11:40:55,172.58.89.249,https://bart-ca.etc-research.com/,-25200.0,JWR,...,\n\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,2024-04-08 08:00:14,83,en,2024-04-08 07:49:17,2024-07-05 11:33:04,174.249.144.185,https://bart-ca.etc-research.com/,-25200.0,EJG,...,\n\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df['Completed']=pd.to_datetime(df['Completed'], errors='coerce')
df['Survey Date'] = df['Completed'].dt.date

In [6]:
df[['Survey Date']]

     Survey Date
0     2024-04-08
1     2024-04-08
2     2024-04-08
3     2024-04-08
4     2024-04-08
...          ...
2982  2024-09-05
2983  2024-09-05
2984  2024-09-05
2985  2024-09-05
2986  2024-09-07

[2987 rows x 1 columns]

In [7]:
df=df[(df['INTERV_INIT']!='999')]
df = df[(df['HAVE_5_MIN_FOR_SURVECode'] == 1)]

In [8]:
def details_dataframe(filename):
    details_df=pd.read_excel(filename,sheet_name='AIR')
    return details_df


home_airport_hotel_column_names=['originaddresslat','originaddresslong', 'destinaddresslat', 'destinaddresslong','originplacetype','homeaddresslat','homeaddresslong',
                                 'destinairportcode','destinplacetype']

def check_home_airport_hotel(df, details_df):

    # Loop through each row in the DataFrame 'df'

    data_list = check_all_characters_present(df,home_airport_hotel_column_names)
    data_list.sort()
    
    for _, row in df.iterrows():
        # Extract latitude and longitude values for origin and destination
        
        origin_addr_lat = row[data_list[6]]
        origin_addr_lng = row[data_list[7]]
        destin_addr_lat = row[data_list[0]]
        destin_addr_lng = row[data_list[1]]

        # Check if origin latitude and longitude are missing
        if pd.isna(origin_addr_lat) or pd.isna(origin_addr_lng):
            print("Origin Lat Long Not present")
            # Get the type of origin place
            origin_place_type = row['ORIGIN_PLACE_TYPE']
            lat_col, lng_col = None, None  # Initialize variables for latitude and longitude column names
            if not pd.isna(origin_place_type):
            # Determine the appropriate columns based on place type
                if 'hotel' in origin_place_type.lower() or 'home' in origin_place_type.lower():
                    lat_col, lng_col = 'HOME_ADDRESS_LAT','HOME_ADDRESS_LONG'
                    print('origin placetype is home')
                elif 'airport' in origin_place_type.lower():
                    airport_destin_code = row['DESTIN_AIRPORTCode']
                    airport_row = details_df[details_df['LIME_CODE'] == airport_destin_code]
                    if not airport_row.empty:
                        lat_col, lng_col = 'lat6', 'lng6'

                # If valid latitude and longitude columns are found, populate the corresponding values
                if lat_col and lng_col:
                    print(f'values for home lat long {row[lat_col]} {row[lng_col]}')
                    df.at[row.name, 'ORIGIN_ADDRESS_LAT'] = row[lat_col]
                    df.at[row.name, 'ORIGIN_ADDRESS_LONG'] = row[lng_col]

        # Check if destination latitude and longitude are missing
        if pd.isna(destin_addr_lat) or pd.isna(destin_addr_lng):
            # Get the type of destination place
            print("Destin Lat Long Not Present")
            destin_place_type = row['DESTIN_PLACE_TYPE']
            print('destin placetype is',destin_place_type)
            lat_col, lng_col = None, None  # Initialize variables for latitude and longitude column names
            if not pd.isna(destin_place_type):
#                 print("Destination place type is NaN, skipping this row")
#                 continue
            # Determine the appropriate columns based on place type
                if 'hotel' in destin_place_type.lower() or 'home' in destin_place_type.lower():
                    print('destin placetype is home/hotel')
                    lat_col, lng_col = 'HOME_ADDRESS_LAT','HOME_ADDRESS_LONG'
                elif 'airport' in destin_place_type.lower():
                    airport_destin_code = row['DESTIN_AIRPORTCode']
                    airport_row = details_df[details_df['LIME_CODE'] == airport_destin_code]
                    if not airport_row.empty:
                        lat_col, lng_col = 'lat6', 'lng6'

                # If valid latitude and longitude columns are found, populate the corresponding values
                if lat_col and lng_col:
                    print(f'values for home lat long {row[lat_col]} {row[lng_col]}')
                    df.at[row.name, 'DESTIN_ADDRESS_LAT'] = row[lat_col]
                    df.at[row.name, 'DESTIN_ADDRESS_LONG'] = row[lng_col]
    # Return the DataFrame 'df' with the populated columns
    return df

In [9]:
origin_destin_columns_check=['originaddresslat','originaddresslong','destinaddresslat','destinaddresslong']
destin_columns_check=['destinaddresslat','destinaddresslong']
origin_columns_check=['originaddresslat','originaddresslong']
origin_destin_columns=check_all_characters_present(df,origin_destin_columns_check)
origin_columns=check_all_characters_present(df,origin_columns_check)
destin_columns=check_all_characters_present(df,destin_columns_check)
origin_destin_columns,origin_columns,destin_columns

(['ORIGIN_ADDRESS_LAT',
  'ORIGIN_ADDRESS_LONG',
  'DESTIN_ADDRESS_LAT',
  'DESTIN_ADDRESS_LONG'],
 ['ORIGIN_ADDRESS_LAT', 'ORIGIN_ADDRESS_LONG'],
 ['DESTIN_ADDRESS_LAT', 'DESTIN_ADDRESS_LONG'])

In [10]:
new_df=df[(df['id']==2650)|(df['id']==5472)|(df['id']==5547)|(df['id']==5562)|(df['id']==5570)][['id','ORIGIN_PLACE_TYPE',*origin_destin_columns,'DESTIN_PLACE_TYPE', 'HOME_ADDRESS_LAT','HOME_ADDRESS_LONG']]

In [11]:
details_df=details_dataframe(filename)

df=check_home_airport_hotel(df,details_df)

Origin Lat Long Not present
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.569729 -122.331034
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.548307 -122.309956
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.61048 -122.395857
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.96234 -122.010053
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.5875 -122.371903
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.018285 -121.924555
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 38.018285 -121.924555
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.005638 -122.316309
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.933382 -122.332643
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.93521 -122.315557
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.965256 -122.302317
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.714995 -122.161477
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.165731 -122.255569
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.911206 -122.288712
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.964719 -122.270954
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.927105 -122.302225
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.949651 -122.343455
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.002945 -122.300276
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.925303 -122.352895
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.960054 -122.342608
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.119869 -122.259044
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.547728 -121.742054
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.956659 -122.343499
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.002251 -122.298908
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.992633 -122.320207
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.947197 -122.334482
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.933387 -122.354547
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.953549 -122.34952
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.979785 -122.335334
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.247986 -122.043072
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.963809 -122.339773
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.94378 -122.314127
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.944316 -122.323307
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.00282 -122.30032
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.805714 -122.26731
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.811614 -122.25515
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.911751 -122.314228
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.813473 -122.268588
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.912779 -122.305014
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.855288 -122.24948
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.631614 -122.089727
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.770021 -122.446961
Origin Lat Long Not present
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.734743 -122.214332
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.847652 -122.269398
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.89471 -122.293811
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.942667 -121.931006
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.92685 -122.02976
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.925272 -121.778125
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.761897 -122.448144
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.641386 -122.419247
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.684808 -122.060097
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.774341 -122.193393
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.767907 -122.158023
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.755905 -122.159212
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 38.017665 -121.921866
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.755628 -122.198534
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.752245 -122.418462
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.358995 -122.028596
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.29238 -121.988783
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.352427 -121.992822
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.282255 -121.949796
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.394121 -121.946183
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.405133 -121.976921
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.41223 -121.938774
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.377324 -122.040319
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.400067 -121.881947
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.702654 -122.462463
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.586164 -122.079993
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 38.005926 -121.866989
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.764362 -122.190697
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.978592 -122.338803
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.740352 -122.178248
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.870328 -122.269137
Origin Lat Long Not present
origin placetype is home
values for home lat long 33.622054 -84.3690917
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.894756 -122.296529
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.876427 -122.266722
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.762375 -122.457073
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.762375 -122.457073
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.878994 -122.283325
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.769723 -122.191546
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.740352 -122.178248
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.885914 -122.277595
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.878992 -122.27748
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.759594 -122.190621
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.935752 -122.345906
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.867987 -122.263948
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.877802 -122.264037
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.871931 -122.266397
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.769397 -122.208769
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.876399 -122.273075
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.759594 -122.190621
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.870339 -122.261206
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.901405 -122.276623
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.865874 -122.274435
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.875787 -122.282476
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.867437 -122.299813
Origin Lat Long Not present
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.87331 -122.263404
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.888395 -122.296577
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.888953 -122.305782
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.862412 -122.28418
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.758047 -122.19167
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.758047 -122.19167
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.875404 -122.278049
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.877951 -122.278545
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.877621 -122.300761
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.890522 -122.294464
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.654937 -122.079621
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.870063 -122.284259
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.872905 -122.27218
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.863746 -122.283266
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.874056 -122.273053
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.886066 -122.266596
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.882263 -122.2802
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.76933 -122.186096
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.880912 -122.28779
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.876183 -122.274
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.871784 -122.272828
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.852474 -122.273895
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.764362 -122.190697
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.874425 -122.285937
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.875205 -122.294049
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.764362 -122.190697
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.764362 -122.190697
Destin Lat Long Not Present
destin placetype is Workplace (SFO Terminal or OAK Terminal)
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.869052 -122.292172
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.758578 -122.190495
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.870459 -122.28203
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.874854 -122.282535
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.852157 -122.286606
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.754176 -122.190984
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.862502 -122.278711
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.764582 -122.198333
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.880383 -122.304338
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.761971 -122.188474
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.822012 -122.253954
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.763102 -122.186549
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.998184 -121.731106
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.702786 -121.896698
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.875786 -122.289709
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.876015 -122.273524
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.660448 -121.875796
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.887687 -122.287408
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.873419 -122.266399
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.876624 -122.261135
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.861404 -122.258906
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.861404 -122.258906
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.707143 -122.074008
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.796183 -122.247651
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.766607 -122.175913
Origin Lat Long Not present
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.71816 -122.429997
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.815584 -122.26422
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.869427 -122.281969
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.640805 -122.413933
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.782083 -122.412245
Origin Lat Long Not present
Destin Lat Long Not Present
destin placetype is Airplane trip
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.755566 -122.198247
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.880235 -122.269242
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.925451 -122.339618
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.765056 -122.419698
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.85674 -122.266681
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.755112 -122.424315
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.761907 -122.418298
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.85129 -122.271772
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.866046 -122.27328
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.779113 -122.221425
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.864623 -122.27435
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.866695 -122.267151
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.777655 -122.225876
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.868742 -122.27646
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.777655 -122.225876
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.769397 -122.208769
Destin Lat Long Not Present
destin placetype is Workplace (SFO Terminal or OAK Terminal)
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.861321 -122.26438
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.839189 -122.287098
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.869326 -122.270263
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.86367 -122.272033
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.875325 -122.264387
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.805414 -122.264989
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.806868 -122.420938
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.806868 -122.420938
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.853268 -122.279074
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.852742 -122.283696
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.864882 -122.267923
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.841873 -122.278762
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.789318 -122.220523

Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.790839 -122.412769
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.778922 -122.423706
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.858712 -122.280262
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.706096 -122.121356
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.956672 -122.348463
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.764009 -122.418489
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.942872 -122.346576
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.871176 -122.268295
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.865379 -122.268999
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.820016 -122.246561
Origin Lat Long Not present
origin placetype is home
values for home lat long 38.027976 -121.88468
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.672735 -122.485104
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.780131 -122.216161
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.391387 -121.881316
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.880428 -122.272
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.765978 -122.420866
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.805134 -122.264778
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.765793 -121.952042
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 38.027976 -121.88468
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 38.010939 -121.803023
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.809538 -122.26948
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.656974 -122.415847
Origin Lat Long Not present
origin placetype is home
values for home lat long 37.867751 -122.272256
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.71777 -122.464316
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.829733 -122.256749
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.672093 -122.098035
Destin Lat Long Not Present
destin placetype is Home
destin placetype is home/hotel
values for home lat long 37.785013 -122.399788

In [12]:
new_df

,id,ORIGIN_PLACE_TYPE,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,DESTIN_PLACE_TYPE,HOME_ADDRESS_LAT,HOME_ADDRESS_LONG
842,2650,Home,NaN,NaN,37.794031,-122.394941,Workplace,37.980347,-122.031224
2548,5472,Workplace,37.698496,-121.926824,NaN,NaN,Home,37.791304,-122.407369
2612,5547,Workplace,37.697803,-121.925466,NaN,NaN,Home,37.800367,-122.216156
2623,5562,Workplace,37.697803,-121.925466,NaN,NaN,Home,37.796564,-122.256462
2631,5570,Workplace,37.697803,-121.925466,NaN,NaN,Home,37.795128,-122.276470

In [13]:
df[(df['id']==2650)|(df['id']==5472)|(df['id']==5547)|(df['id']==5562)|(df['id']==5570)][['id','ORIGIN_PLACE_TYPE',*origin_destin_columns,'DESTIN_PLACE_TYPE', 'HOME_ADDRESS_LAT','HOME_ADDRESS_LONG']]

,id,ORIGIN_PLACE_TYPE,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,DESTIN_PLACE_TYPE,HOME_ADDRESS_LAT,HOME_ADDRESS_LONG
842,2650,Home,37.980347,-122.031224,37.794031,-122.394941,Workplace,37.980347,-122.031224
2548,5472,Workplace,37.698496,-121.926824,37.791304,-122.407369,Home,37.791304,-122.407369
2612,5547,Workplace,37.697803,-121.925466,37.800367,-122.216156,Home,37.800367,-122.216156
2623,5562,Workplace,37.697803,-121.925466,37.796564,-122.256462,Home,37.796564,-122.256462
2631,5570,Workplace,37.697803,-121.925466,37.795128,-122.276470,Home,37.795128,-122.276470

In [14]:
df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT',
       ...
       'INVITE_EMAIL', 'INVITE_SMS', 'INVITE_CALL', 'INVITE_TOKEN',
       'INVITE_STATUS', 'EXP_HOMELESSCode', 'EXP_HOMELESS', '_REVERSE_TRIP',
       'GENERATABLE_TRIPS', 'Survey Date'],
      dtype='object', length=862)

In [15]:
df.drop_duplicates(subset=origin_destin_columns)

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,EXP_HOMELESSCode,EXP_HOMELESS,_REVERSE_TRIP,GENERATABLE_TRIPS,Survey Date
3,15,2024-04-08 07:57:27,83,en,2024-04-08 07:44:11,2024-07-04 11:40:55,172.58.89.249,https://bart-ca.etc-research.com/,-25200.0,JWR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08
4,16,2024-04-08 08:00:14,83,en,2024-04-08 07:49:17,2024-07-05 11:33:04,174.249.144.185,https://bart-ca.etc-research.com/,-25200.0,EJG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08
5,18,2024-04-08 08:10:24,83,en,2024-04-08 08:02:52,2024-07-05 11:32:46,174.249.147.91,NaN,-25200.0,MOW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08
6,19,2024-04-08 08:34:30,83,en,2024-04-08 08:03:10,2024-07-05 11:29:16,172.58.89.249,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,JWR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08
7,20,2024-04-08 08:15:17,83,en,2024-04-08 08:08:34,2024-07-04 12:16:31,174.249.144.185,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,EJG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2978,7080,2024-09-05 20:29:12,86,en,2024-09-05 19:17:05,2024-09-09 08:20:31,172.59.131.89,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,CVD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-05
2979,7082,2024-09-05 19:24:21,86,en,2024-09-05 19:17:44,2024-09-09 08:20:52,107.77.214.51,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,EVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-05
2981,7084,2024-09-05 20:30:11,86,en,2024-09-05 19:27:37,2024-09-09 08:21:04,166.216.158.194,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,SAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-05
2983,7086,2024-09-05 20:22:58,86,en,2024-09-05 20:17:58,2024-09-09 08:21:20,107.77.214.51,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,EVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-05
2984,7087,2024-09-05 20:35:15,86,en,2024-09-05 20:27:51,2024-09-09 08:21:32,107.77.213.224,https://bart-ca.etc-research.com/,-25200.0,TAX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-05

In [16]:
duplicated_df = df[df.duplicated(subset=origin_destin_columns, keep=False)]
duplicated_df

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,EXP_HOMELESSCode,EXP_HOMELESS,_REVERSE_TRIP,GENERATABLE_TRIPS,Survey Date
340,1605,2024-05-15 18:00:05,86,en,2024-05-15 17:54:54,2024-06-18 22:16:14,166.216.158.76,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,MDE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-15
342,1610,2024-05-15 18:04:24,86,en,2024-05-15 18:00:47,2024-05-15 18:04:24,166.216.158.76,https://bart-ca.etc-research.com/,-25200.0,MDE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-15
740,2488,2024-05-23 07:24:16,86,en,2024-05-23 07:13:25,2024-05-23 07:24:16,107.77.213.217,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,SAW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-23
946,2837,2024-05-28 11:24:53,86,en,2024-05-28 11:11:04,2024-05-28 11:24:53,107.77.212.190,NaN,-25200.0,MDE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-28
964,2862,2024-05-28 12:25:35,86,en,2024-05-28 12:18:26,2024-05-28 12:25:35,107.77.214.34,NaN,-25200.0,JMR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-28
972,2880,2024-05-28 13:25:46,86,en,2024-05-28 13:18:20,2024-05-28 13:25:46,174.249.147.30,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,ZLY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-28
976,2889,2024-05-28 13:48:22,86,en,2024-05-28 13:26:16,2024-05-28 13:48:22,174.249.147.30,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,ZLY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-28
985,2902,2024-05-28 13:52:35,86,en,2024-05-28 13:48:43,2024-05-28 13:52:35,174.249.147.30,https://bart-ca.etc-research.com/index.php/952...,-25200.0,ZLY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-28
990,2913,2024-05-28 14:13:28,86,en,2024-05-28 14:04:14,2024-05-28 14:13:28,174.249.147.30,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,ZLY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-28
995,2919,2024-05-28 14:23:50,86,en,2024-05-28 14:13:50,2024-05-28 14:23:50,174.249.147.30,https://bart-ca.etc-research.com/index.php/952...,-25200.0,ZLY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-28
1030,2965,2024-05-28 15:45:01,86,en,2024-05-28 15:40:58,2024-05-28 15:45:01,107.77.212.190,NaN,-25200.0,MDE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-28
2036,4449,2024-06-06 06:05:51,86,en,2024-06-06 06:00:26,2024-06-19 01:07:42,107.77.211.37,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,KHC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-06
2043,4458,2024-06-06 06:46:43,86,en,2024-06-06 06:33:57,2024-06-19 01:09:26,107.77.211.37,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,KHC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-06
2076,4502,2024-06-06 08:59:46,86,en,2024-06-06 08:55:45,2024-06-06 08:59:46,108.85.30.196,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,AEB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-06
2195,4760,2024-06-10 09:43:14,86,en,2024-06-10 09:37:43,2024-06-19 01:56:17,107.77.212.132,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,KHC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2246,4846,2024-06-10 12:40:12,86,en,2024-06-10 12:32:14,2024-06-26 04:06:40,107.77.213.217,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,SAW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2250,4854,2024-06-10 12:42:45,86,en,2024-06-10 12:40:28,2024-07-10 04:28:02,107.77.213.217,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,SAW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2254,4858,2024-06-10 12:56:41,86,en,2024-06-10 12:46:27,2024-06-19 01:22:10,174.249.148.106,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,AMT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2257,4868,2024-06-10 13:18:10,86,en,2024-06-10 12:57:07,2024-07-05 11:31:46,174.249.148.106,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,AMT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2270,4904,2024-06-10 13:52:54,86,en,2024-06-10 13:48:15,2024-06-19 01:44:18,174.195.80.4,https://bart-ca.etc-research.com/,-25200.0,CMH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2281,4929,2024-06-10 14:21:46,86,en,2024-06-10 14:15:53,2024-06-19 01:56:31,166.216.158.47,NaN,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2284,4934,2024-06-10 14:31:32,86,en,2024-06-10 14:26:36,2024-06-19 01:57:57,174.249.148.106,https://bart-ca.etc-research.com/,-25200.0,AMT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2289,4943,2024-06-10 15:01:27,86,en,2024-06-10 14:45:03,2024-06-19 02:00:23,174.249.148.106,NaN,-25200.0,AMT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2291,4947,2024-06-10 14:53:54,86,en,2024-06-10 14:50:09,2024-06-19 02:01:22,166.216.158.47,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2299,4958,2024-06-10 15:16:00,86,en,2024-06-10 15:08:28,2024-06-19 02:07:20,166.216.158.47,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2305,4968,2024-06-10 15:33:08,86,en,2024-06-10 15:22:56,2024-06-19 02:11:22,107.77.212.36,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,JMR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2307,4972,2024-06-10 15:34:48,86,en,2024-06-10 15:32:02,2024-06-19 02:12:21,166.216.158.47,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2323,5005,2024-06-10 16:47:01,86,en,2024-06-10 16:39:06,2024-06-19 02:22:17,174.249.150.104,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,CIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2324,5009,2024-06-10 16:58:35,86,en,2024-06-10 16:48:03,2024-07-05 08:37:31,174.249.150.104,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,CIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2329,5017,2024-06-10 17:11:37,86,en,2024-06-10 17:06:27,2024-06-19 02:24:27,166.216.158.47,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2338,5029,2024-06-10 18:12:53,86,en,2024-06-10 18:01:29,2024-06-19 02:28:13,174.249.150.104,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,CIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2343,5038,2024-06-10 18:52:39,86,en,2024-06-10 18:49:08,2024-06-19 02:30:38,166.216.158.47,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2346,5041,2024-06-10 19:27:56,86,en,2024-06-10 19:23:37,2024-06-19 02:32:07,174.249.150.104,https://bart-ca.etc-research.com/,-25200.0,CIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2350,5045,2024-06-10 19:40:43,86,en,2024-06-10 19:36:05,2024-06-19 01:24:53,174.249.150.104,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,CIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2351,5046,2024-06-10 19:44:20,86,en,2024-06-10 19:41:06,2024-06-19 01:25:13,174.249.150.104,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,CIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2352,5047,2024-06-10 20:04:04,86,en,2024-06-10 19:44:34,2024-06-19 01:25:34,174.249.150.104,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,CIS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-10
2445,5195,2024-06-11 10:25:01,86,en,2024-06-11 10:21:05,2024-06-11 10:25:01,107.77.211.143,NaN,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-11
2458,5216,2024-06-11 10:57:56,86,en,2024-06-11 10:54:15,2024-06-11 10:57:56,107.77.211.157,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-11
2464,5225,2024-06-11 11:12:24,86,en,2024-06-11 11:08:26,2024-06-11 11:12:24,107.77.211.157,https://bart-ca.etc-research.com/,-25200.0,RMM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-11
2471,5241,2024-06-11 11:27:10,86,en,2024-06-11 11:24:19,2024-06-11 11:27:10,174.195.85.197,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,AMT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-11
2495,5302,2024-06-11 12:21:07,86,en,2024-06-11 12:12:11,2024-06-11 12:21:07,174.195.85.197,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,AMT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-11
2601,5535,2024-06-11 15:43:00,86,en,2024-06-11 15:24:17,2024-06-11 15:43:00,107.77.212.72,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,ALD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-11
2629,5568,2024-06-11 16:10:02,86,en,2024-06-11 16:05:24,2024-06-11 16:10:02,107.77.212.72,https://bart-ca.etc-research.com/index.php/sur...,-25200.0,ALD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-11

In [17]:
unique_intervs=df['INTERV_INIT'].unique()
unique_intervs

array(['JWR', 'EJG', 'MOW', 'ICF', 'ANA', 'DNP', 'HRD', 'JAC', 'ODA',
       'ASS', 'LIZ', 'AJC', 'SAW', 'URY', 'CSO', 'P.R', 'KJT', 'AEB',
       'JFP', 'ALM', 'MDE', 'MD3', 'HHK', 'BDM', 'LMM', 'DDF', 'RAS',
       'JLR', 'MCM', 'KHC', 'SJH', 'BWC', 'BPB', 'ZLY', 'ANS', 'JMR',
       'EVE', 'ISA', 'CBA', 'CMH', 'RMM', 'LZZ', 'AMT', 'KMR', 'JMB',
       'AEW', 'JTT', 'JAT', 'CIS', 'HPF', 'RCM', 'STR', 'DJS', 'ALD',
       'WJJ', 'CS0', 'KRD', 'CVD', 'BEA', 'SAR', 'TAX'], dtype=object)

In [18]:
duplicated_df[duplicated_df['INTERV_INIT']=='ZLY'][origin_destin_columns]
# duplicated_df[duplicated_df['INTERV_INIT']=='ZLY'][['id','INTERV_INIT',*origin_destin_columns]].to_csv('INTERVIEWER_Duplicated_data01.csv',index=False)

,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG
972,37.897808,-122.064147,37.852157,-122.286606
976,37.897808,-122.064147,37.852157,-122.286606
985,37.897808,-122.064147,37.852157,-122.286606
990,37.897808,-122.064147,37.852157,-122.286606
995,37.897808,-122.064147,37.852157,-122.286606

In [19]:
for interv in unique_intervs:
    if interv=='ZLY':
        user_data=df[df['INTERV_INIT']==interv]
        user_duplicated_df=user_data[user_data.duplicated(subset=origin_destin_columns, keep=False)]
        user_duplicated_df[['id','INTERV_INIT',*origin_destin_columns]].to_csv('INTERVIEWER_Duplicated_data02.csv',index=False)

In [20]:
df[(df['id']==5472)|(df['id']==5547)|(df['id']==5562)|(df['id']==5570)][['id',*origin_destin_columns]]

,id,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG
2548,5472,37.698496,-121.926824,37.791304,-122.407369
2612,5547,37.697803,-121.925466,37.800367,-122.216156
2623,5562,37.697803,-121.925466,37.796564,-122.256462
2631,5570,37.697803,-121.925466,37.795128,-122.276470

In [21]:
final_duplicated_df = pd.DataFrame()
final_destin_duplicated_df = pd.DataFrame()
final_origin_duplicated_df = pd.DataFrame()

for interv in unique_intervs:
    
    user_data = df[df['INTERV_INIT'] == interv]
    unique_dates = user_data['Survey Date'].unique()

    for date in unique_dates:

        date_data = user_data[user_data['Survey Date'] == date]

        # Check for duplicated rows based on origin, destination, and both combined
        user_origin_duplicated_df = date_data[date_data.duplicated(subset=origin_columns, keep=False)]
        user_destin_duplicated_df = date_data[date_data.duplicated(subset=destin_columns, keep=False)]
        user_duplicated_df = date_data[date_data.duplicated(subset=origin_destin_columns, keep=False)]

        # Append results to the final DataFrames
        final_origin_duplicated_df = pd.concat([
            final_origin_duplicated_df, 
            user_origin_duplicated_df[['id', 'Survey Date', 'INTERV_INIT', 'ORIGIN_PLACE_TYPE', *origin_columns, 'HOME_ADDRESS_LAT', 'HOME_ADDRESS_LONG']]
        ])

        final_destin_duplicated_df = pd.concat([
            final_destin_duplicated_df, 
            user_destin_duplicated_df[['id', 'Survey Date', 'INTERV_INIT', *destin_columns, 'DESTIN_PLACE_TYPE', 'HOME_ADDRESS_LAT', 'HOME_ADDRESS_LONG']]
        ])

        final_duplicated_df = pd.concat([
            final_duplicated_df, 
            user_duplicated_df[['id', 'Survey Date', 'INTERV_INIT', 'ORIGIN_PLACE_TYPE', *origin_destin_columns, 'DESTIN_PLACE_TYPE', 'HOME_ADDRESS_LAT', 'HOME_ADDRESS_LONG']]
        ])

# Reset index for all DataFrames after concatenation
final_origin_duplicated_df.reset_index(drop=True, inplace=True)
final_destin_duplicated_df.reset_index(drop=True, inplace=True)
final_duplicated_df.reset_index(drop=True, inplace=True)

In [22]:
# final_duplicated_df.to_csv('Final_Interviewer_Data001.csv',index=False)

In [23]:
with pd.ExcelWriter(f'INTERV_Duplicated_Records.xlsx') as writer:
    # grouped[['INTERV_INIT','Description']].to_excel(writer, sheet_name="INTERV One Line Summary", index=False)
    final_origin_duplicated_df.to_excel(writer, sheet_name="INTERV Origin Duplicates", index=False)    
    final_destin_duplicated_df.to_excel(writer, sheet_name="INTERV Destin Duplicates", index=False)    
    final_duplicated_df.to_excel(writer, sheet_name="INTERV Overall Duplicates", index=False)

In [24]:
final_duplicated_df = pd.DataFrame()
final_destin_duplicated_df = pd.DataFrame()
final_origin_duplicated_df = pd.DataFrame()
origin_data=[]
destin_data=[]
origin_destin_data=[]
for interv in unique_intervs:
    
    user_data = df[df['INTERV_INIT'] == interv]
    unique_dates = user_data['Survey Date'].unique()
    for date in unique_dates:
        
        date_data = user_data[user_data['Survey Date'] == date]

        # Check for duplicated rows based on origin, destination, and both combined
        user_origin_duplicated_df = date_data[date_data.duplicated(subset=origin_columns, keep=False)]
        user_destin_duplicated_df = date_data[date_data.duplicated(subset=destin_columns, keep=False)]
        user_duplicated_df = date_data[date_data.duplicated(subset=origin_destin_columns, keep=False)]
        
        total_records=date_data.shape[0]
        origin_flag_records=user_origin_duplicated_df.shape[0]
        origin_flag_records_ids=user_origin_duplicated_df['id'].values
        destin_flag_records=user_destin_duplicated_df.shape[0]
        destin_flag_records_ids=user_destin_duplicated_df['id'].values
        origin_destin_flag_records=user_duplicated_df.shape[0]
        origin_destin_flag_records_ids=user_duplicated_df['id'].values
        
        # Append results to the final DataFrames
        final_origin_duplicated_df = pd.concat([
            final_origin_duplicated_df, 
            user_origin_duplicated_df[['id', 'Survey Date', 'INTERV_INIT', 'ORIGIN_PLACE_TYPE', *origin_columns, 'HOME_ADDRESS_LAT', 'HOME_ADDRESS_LONG']]
        ])

        final_destin_duplicated_df = pd.concat([
            final_destin_duplicated_df, 
            user_destin_duplicated_df[['id', 'Survey Date', 'INTERV_INIT', *destin_columns, 'DESTIN_PLACE_TYPE', 'HOME_ADDRESS_LAT', 'HOME_ADDRESS_LONG']]
        ])

        final_duplicated_df = pd.concat([
            final_duplicated_df, 
            user_duplicated_df[['id', 'Survey Date', 'INTERV_INIT', 'ORIGIN_PLACE_TYPE', *origin_destin_columns, 'DESTIN_PLACE_TYPE', 'HOME_ADDRESS_LAT', 'HOME_ADDRESS_LONG']]
        ])
        origin_data.append({
            'INTERV INIT':interv,
            'Survey Date':date,
            'Origin Duplicated Records':origin_flag_records,
            'Total Records':total_records,
            'Origin Duplicated Percentage':round(origin_flag_records/total_records*100,2) if total_records > 0 else 0,
            "Origin Flags IDS":origin_flag_records_ids
            
        })
        destin_data.append({
            'INTERV INIT':interv,
            'Survey Date':date,
            'Origin Duplicated Records':destin_flag_records,
            'Total Records':total_records,
            'Origin Duplicated Percentage':round(destin_flag_records/total_records*100,2) if total_records > 0 else 0,
            "Origin Flags IDS":destin_flag_records_ids
            
        })
        origin_destin_data.append({
                'INTERV INIT':interv,
                'Survey Date':date,
                'Origin Destin Duplicated Records':origin_destin_flag_records,
                'Total Records':total_records,
                'Origin Destin Duplicated Percentage':round(origin_destin_flag_records/total_records*100,2) if total_records > 0 else 0,
                "Origin Destin Flags IDS":origin_destin_flag_records_ids

            })

# Reset index for all DataFrames after concatenation
final_origin_duplicated_df.reset_index(drop=True, inplace=True)
final_destin_duplicated_df.reset_index(drop=True, inplace=True)
final_duplicated_df.reset_index(drop=True, inplace=True)
origin_df=pd.DataFrame(origin_data)
destin_df=pd.DataFrame(destin_data)
origin_destin_df=pd.DataFrame(origin_destin_data)

In [25]:
with pd.ExcelWriter(f'INTERV_Duplicated_stats03.xlsx') as writer:
    # grouped[['INTERV_INIT','Description']].to_excel(writer, sheet_name="INTERV One Line Summary", index=False)
    origin_df.to_excel(writer, sheet_name="INTERV Daily Origin%", index=False)    
    destin_df.to_excel(writer, sheet_name="INTERV Daily Destin%", index=False)    
    origin_destin_df.to_excel(writer, sheet_name="INTERV Daily OriginDestin%", index=False)    
    final_origin_duplicated_df.to_excel(writer, sheet_name="INTERV Origin Duplicates", index=False)    
    final_destin_duplicated_df.to_excel(writer, sheet_name="INTERV Destin Duplicates", index=False)    
    final_duplicated_df.to_excel(writer, sheet_name="INTERV Overall Duplicates", index=False)