In [1]:
import pandas as pd
import numpy as np
import warnings 

warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('elvisdenverco2024obweekday_export_odbc.csv')
df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ELVIS_USER_CHANGE_7_C_REASON,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,EXP_HOMELESSCode,EXP_HOMELESS,_REVERSE_TRIP,GENERATABLE_TRIPS
0,11423,2024-08-14 14:09:00,81,en,2024-08-14 13:58:35,2024-08-14 14:09:00,70.113.126.123,https://denver-co-od.etc-research.com/,-21600,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11424,2024-08-14 14:09:26,81,en,2024-08-14 14:09:03,2024-08-14 14:09:26,70.113.126.123,https://denver-co-od.etc-research.com/index.ph...,-21600,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11425,2024-08-14 14:24:11,81,en,2024-08-14 14:09:28,2024-08-14 14:24:11,70.113.126.123,https://denver-co-od.etc-research.com/index.ph...,-21600,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11427,2024-08-14 14:57:00,81,en,2024-08-14 14:36:36,2024-08-14 14:57:00,50.202.171.186,https://denver-co-od.etc-research.com/,-21600,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11634,2024-08-19 06:18:09,81,en,2024-08-19 06:10:17,2024-08-27 01:02:36,172.58.57.226,https://denver-co-od.etc-research.com/,-21600,ANC,...,\n\n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df=pd.read_excel('reviewtool_20240911_DENVER_interviewerstats.xlsx',sheet_name='Interviewer TimeStamp Checks')
df.shape

(2800, 10)

In [4]:
distance_df=pd.read_excel('reviewtool_20240911_DENVER_interviewerstats.xlsx',sheet_name='Interviewer Distance Checks')
distance_df.shape

(2800, 7)

In [54]:
over_all_data_df=pd.read_excel('reviewtool_20240911_DENVER_interviewerstats.xlsx',sheet_name='Interviewer Overall Summary')
over_all_data_df.shape

(39, 8)

In [5]:
jqt_df=df[df['INTERV_INIT']=='JQT']

In [6]:
jqt_df.shape

(142, 10)

In [7]:
jqt_df[jqt_df['Full Survey Time Flag']==1]

,id,INTERV_INIT,Survey Date,Full Survey Time,Logistics Time,Demographic Time,Field Reviewed,Full Survey Time Flag,Logistics Time Flag,Demographic Time Flag
794,14124,JQT,2024-08-22,3.483333,2.316667,1.166667,NaN,1,0,1
826,14213,JQT,2024-08-22,3.183333,2.233333,0.950000,NaN,1,0,1
1311,15217,JQT,2024-08-26,3.683333,2.266667,1.416667,NaN,1,0,1
1414,15459,JQT,2024-08-26,3.950000,2.883333,1.066667,NaN,1,0,1
1723,16053,JQT,2024-08-27,3.066667,2.466667,0.600000,NaN,1,0,1
...,...,...,...,...,...,...,...,...,...,...
2724,18106,JQT,2024-08-29,3.366667,2.283333,1.083333,NaN,1,0,1
2729,18116,JQT,2024-08-29,2.400000,1.583333,0.816667,NaN,1,1,1
2733,18120,JQT,2024-08-29,3.766667,2.866667,0.900000,NaN,1,0,1
2737,18132,JQT,2024-08-29,2.583333,1.783333,0.800000,NaN,1,1,1
2771,18194,JQT,2024-08-29,3.516667,2.400000,1.116667,NaN,1,0,1

In [8]:
84/142

0.5915492957746479

In [9]:
jqt_df[jqt_df['Demographic Time Flag']==1].shape

(109, 10)

In [10]:
118/142

0.8309859154929577

In [11]:
jqt_df[jqt_df['Logistics Time Flag']==1].shape

(32, 10)

In [12]:
65/142

0.45774647887323944

In [13]:
jqt_df['Survey Date'].unique()

<DatetimeArray>
['2024-08-21 00:00:00', '2024-08-22 00:00:00', '2024-08-26 00:00:00',
 '2024-08-27 00:00:00', '2024-08-29 00:00:00']
Length: 5, dtype: datetime64[ns]

In [14]:
unique_interv=df['INTERV_INIT'].unique()
unique_interv

array(['ANC', 'LSS', 'CBB', 'MAO', 'MXG', 'JMV', 'DHC', 'LXF', 'NSH',
       'TBT', 'SJG', 'CLB', 'LXO', 'JLD', 'GXG', 'BAM', 'DRM', 'MAD',
       'RLC', 'EJP', 'RAB', 'JQT', 'HJT', 'KSB', 'LAJ', 'DKG', 'PLD',
       'LDP', 'DAF', 'BBM', 'DMD', 'HSD', 'PCS', 'RJG', 'CAB', 'RWZ',
       'JLS', 'JTC', 'Pld'], dtype=object)

In [15]:
data=[]
for user in unique_interv:
    total_records=df[df['INTERV_INIT']==user].shape[0]    
    full_time_survey=df[(df['INTERV_INIT']==user)&(df['Full Survey Time Flag']==1)].shape[0]    
    logistic_time_survey=df[(df['INTERV_INIT']==user)&(df['Logistics Time Flag']==1)].shape[0]    
    demographic_time_survey=df[(df['INTERV_INIT']==user)&(df['Demographic Time Flag']==1)].shape[0]
    # Calculate percentages
    full_time_survey_percentage = (full_time_survey / total_records) * 100 if total_records != 0 else 0
    logistic_time_survey_percentage = (logistic_time_survey / total_records) * 100 if total_records != 0 else 0
    demographic_time_survey_percentage = (demographic_time_survey / total_records) * 100 if total_records != 0 else 0
    
    # Append results to the list
    data.append({
        'INTERV_INIT': user,
        'Total Records': total_records,
        'Full Time Survey Records': full_time_survey,
        'Logistic Time Survey Records': logistic_time_survey,
        'Demographic Time Survey Records': demographic_time_survey,
        'Full Time Survey Percentage': full_time_survey_percentage,
        'Logistic Time Survey Percentage': logistic_time_survey_percentage,
        'Demographic Time Survey Percentage': demographic_time_survey_percentage
    })
#     print(user,'=',total_records,full_time_survey_percentage,logistic_time_survey_percentage,demographic_time_survey_percentage)

In [16]:
result_df = pd.DataFrame(data)
result_df.head()

,INTERV_INIT,Total Records,Full Time Survey Records,Logistic Time Survey Records,Demographic Time Survey Records,Full Time Survey Percentage,Logistic Time Survey Percentage,Demographic Time Survey Percentage
0,ANC,399,193,9,363,48.370927,2.255639,90.977444
1,LSS,202,18,2,153,8.910891,0.990099,75.742574
2,CBB,47,2,0,26,4.255319,0.000000,55.319149
3,MAO,20,0,0,10,0.000000,0.000000,50.000000
4,MXG,10,0,0,0,0.000000,0.000000,0.000000

In [17]:
# Create an empty list to store results
data = []

# Iterate through each unique user
for user in unique_interv:
    # Get all records for the user
    user_data = df[df['INTERV_INIT'] == user]
    
    # Get unique dates for this user
    unique_dates = user_data['Survey Date'].unique()
    
    # Iterate through each unique date
    for date in unique_dates:
        # Get all records for the user on that specific date
        date_data = user_data[user_data['Survey Date'] == date]
        
        # Get total records for the user on that specific date
        total_records = date_data.shape[0]
        
        # Get flagged records for each type on that specific date
        full_time_survey = date_data[date_data['Full Survey Time Flag'] == 1].shape[0]
        logistic_time_survey = date_data[date_data['Logistics Time Flag'] == 1].shape[0]
        demographic_time_survey = date_data[date_data['Demographic Time Flag'] == 1].shape[0]
        
        # Calculate percentages
        full_time_survey_percentage = (full_time_survey / total_records) * 100 if total_records != 0 else 0
        logistic_time_survey_percentage = (logistic_time_survey / total_records) * 100 if total_records != 0 else 0
        demographic_time_survey_percentage = (demographic_time_survey / total_records) * 100 if total_records != 0 else 0
        
        # Append results to the list
        data.append({
            'INTERV_INIT': user,
            'Survey Date': date,
            'Total Records': total_records,
            'Full Time Survey Records': full_time_survey,
            'Logistic Time Survey Records': logistic_time_survey,
            'Demographic Time Survey Records': demographic_time_survey,
            'Full Time Survey Percentage': full_time_survey_percentage,
            'Logistic Time Survey Percentage': logistic_time_survey_percentage,
            'Demographic Time Survey Percentage': demographic_time_survey_percentage
        })

# Create a dataframe from the list
result_df = pd.DataFrame(data)

In [18]:
result_df

,INTERV_INIT,Survey Date,Total Records,Full Time Survey Records,Logistic Time Survey Records,Demographic Time Survey Records,Full Time Survey Percentage,Logistic Time Survey Percentage,Demographic Time Survey Percentage
0,ANC,2024-08-19,42,25,1,38,59.523810,2.380952,90.476190
1,ANC,2024-08-20,32,20,1,31,62.500000,3.125000,96.875000
2,ANC,2024-08-21,53,20,0,49,37.735849,0.000000,92.452830
3,ANC,2024-08-22,48,26,1,44,54.166667,2.083333,91.666667
4,ANC,2024-08-23,40,12,2,30,30.000000,5.000000,75.000000
...,...,...,...,...,...,...,...,...,...
140,JTC,2024-08-27,43,26,12,41,60.465116,27.906977,95.348837
141,JTC,2024-08-28,69,43,9,61,62.318841,13.043478,88.405797
142,JTC,2024-08-29,42,23,6,38,54.761905,14.285714,90.476190
143,JTC,2024-08-30,7,4,1,7,57.142857,14.285714,100.000000
144,Pld,2024-08-26,1,0,0,1,0.000000,0.000000,100.000000

In [19]:
# new_data=[]
# for user in unique_interv:
#     # Get all records for the user
#     user_data = df[df['INTERV_INIT'] == user]
    
#     # Get unique dates for this user
#     unique_dates = user_data['Survey Date'].unique()
    
#     # Iterate through each unique date
#     for date in unique_dates:
#         # Get all records for the user on that specific date
#         date_data = user_data[user_data['Survey Date'] == date]
        
#         # Get total records for the user on that specific date
#         total_records = date_data.shape[0]
        
#         # Get flagged records for each type on that specific date
#         full_time_survey_ids = date_data[date_data['Full Survey Time Flag'] == 1]['id'].values
#         logistic_time_survey_ids = date_data[date_data['Logistics Time Flag'] == 1]['id'].values
#         demographic_time_survey_ids = date_data[date_data['Demographic Time Flag'] == 1]['id'].values
        
#         checks_list=['Full Survey Time Flag','Logistics Time Flag','Demographic Time Flag']
#         for value in checks_list:
#             if value=='Full Survey Time Flag':
#                 new_data.append({
#                     'INTERV_INIT': user,
#                     'Survey Date': date,
#                     'Full Survey Time': len(full_time_survey_ids),
#                     'Logistic Time': np.nan,
#                     'Demographic Time': np.nan,
#                     'IDS':full_time_survey_ids
#                 })
#             elif value =='Logistics Time Flag':
#                 new_data.append({
#                     'INTERV_INIT': user,
#                     'Survey Date': date,
#                     'Full Survey Time': np.nan,
#                     'Logistic Time': len(logistic_time_survey_ids),
#                     'Demographic Time': np.nan,
#                     'IDS':logistic_time_survey_ids
#                 })
#             else:
#                 new_data.append({
#                     'INTERV_INIT': user,
#                     'Survey Date': date,
#                     'Full Survey Time': np.nan,
#                     'Logistic Time':np.nan ,
#                     'Demographic Time': len(demographic_time_survey_ids),
#                     'IDS':demographic_time_survey_ids
#                 })

# new_df=pd.DataFrame(new_data)

In [53]:
# New_Suammary_Sheet 01

In [20]:
new_data = []

# Loop through each unique user
for user in unique_interv:
    # Filter records for the current user
    user_data = df[df['INTERV_INIT'] == user]
    
    # Get unique survey dates for this user
    unique_dates = user_data['Survey Date'].unique()
    
    # Loop through each unique date
    for date in unique_dates:
        # Filter records for the specific date
        date_data = user_data[user_data['Survey Date'] == date]
        
        # Dictionary to store flagged records for each type
        flag_ids = {
            'Full Survey Time': date_data[date_data['Full Survey Time Flag'] == 1]['id'].values,
            'Logistic Time': date_data[date_data['Logistics Time Flag'] == 1]['id'].values,
            'Demographic Time': date_data[date_data['Demographic Time Flag'] == 1]['id'].values
        }

        # Append data to new_data list for each flag type
        for flag_type, ids in flag_ids.items():
            new_data.append({
                'INTERV_INIT': user,
                'Survey Date': date,
                'Full Survey Time': len(ids) if flag_type == 'Full Survey Time' else np.nan,
                'Logistic Time': len(ids) if flag_type == 'Logistic Time' else np.nan,
                'Demographic Time': len(ids) if flag_type == 'Demographic Time' else np.nan,
                'IDS': ids
            })

# Convert to DataFrame
new_df = pd.DataFrame(new_data)

In [21]:
# new_df.to_csv('TimeStamp_Revision_01.csv',index=False)

In [22]:
distance_df.columns

Index(['id', 'INTERV_INIT', 'Survey Date', 'ELVIS_USER_LOC_LAT',
       'ELVIS_USER_LOC_LONG', 'Distances', 'Consecutive_Flag'],
      dtype='object')

In [23]:
new_data2=[]
for user in unique_interv:
    # Get all records for the user
    user_data = distance_df[distance_df['INTERV_INIT'] == user]
    
    # Get unique dates for this user
    unique_dates = user_data['Survey Date'].unique()
    
    # Iterate through each unique date
    for date in unique_dates:
        # Get all records for the user on that specific date
        date_data = user_data[user_data['Survey Date'] == date]
        
        # Get total records for the user on that specific date
        total_records = date_data.shape[0]
        
        # Get flagged records for each type on that specific date
        distance_flags_survey_ids = date_data[date_data['Consecutive_Flag'] == 1]['id'].values
        
        new_data2.append({
                'INTERV_INIT': user,
                'Survey Date': date,
                'Distance Between Survey Locations': len(distance_flags_survey_ids),
                'IDS': distance_flags_survey_ids
            })

new_df2=pd.DataFrame(new_data2)

In [42]:
new_df.columns

Index(['INTERV_INIT', 'Survey Date', 'Full Survey Time', 'Logistic Time',
       'Demographic Time', 'IDS'],
      dtype='object')

In [43]:
new_df2.columns

Index(['INTERV_INIT', 'Survey Date', 'Distance Between Survey Locations',
       'IDS'],
      dtype='object')

In [31]:
# new_df2.to_csv("Location_Distance01.csv",index=False)

In [49]:
empty_columns = pd.DataFrame(np.nan, index=new_df.index, columns=[None] * 3)

In [50]:
new_df3=pd.concat([new_df,empty_columns,new_df2],axis=1)

In [51]:
# new_df3 = pd.merge(new_df, new_df2, on=['INTERV_INIT', 'Survey Date'], how='outer', suffixes=('', '_Distance_Flags'))

In [52]:
# new_df3.to_csv('Combine_Time_Distance01.csv',index=False)

In [39]:
gap_rows = pd.DataFrame(np.nan, index=range(3), columns=new_df.columns)  # 3 rows of NaN

# Step 2: Concatenate new_df, gap rows, and new_df2
new_df4 = pd.concat([new_df, gap_rows, new_df2], axis=1)
new_df4.to_csv('Combine_Time_Distance01.csv',index=False)

In [24]:
user_data=df[df['INTERV_INIT'] == 'JTC']
user_data

,id,INTERV_INIT,Survey Date,Full Survey Time,Logistics Time,Demographic Time,Field Reviewed,Full Survey Time Flag,Logistics Time Flag,Demographic Time Flag
1115,14778,JTC,2024-08-26,5.016667,3.216667,1.800000,NaN,0,0,1
1120,14787,JTC,2024-08-26,3.666667,2.583333,1.083333,NaN,1,0,1
1125,14794,JTC,2024-08-26,2.983333,2.116667,0.866667,NaN,1,0,1
1131,14805,JTC,2024-08-26,5.850000,3.883333,1.966667,NaN,0,0,1
1134,14809,JTC,2024-08-26,4.616667,3.266667,1.350000,NaN,0,0,1
...,...,...,...,...,...,...,...,...,...,...
2795,18235,JTC,2024-08-30,12.633333,11.916667,0.716667,NaN,0,0,1
2796,18236,JTC,2024-08-30,4.950000,3.100000,1.850000,NaN,0,0,1
2797,18237,JTC,2024-08-30,4.483333,3.466667,1.016667,NaN,0,0,1
2798,18238,JTC,2024-08-30,2.433333,1.733333,0.700000,NaN,1,1,1
2799,18239,JTC,2024-08-30,3.283333,2.733333,0.550000,NaN,1,0,1

In [63]:
# Distance Percentage Code

In [66]:
distance_df.shape[0]

2800

In [67]:
distance_df.columns

Index(['id', 'INTERV_INIT', 'Survey Date', 'ELVIS_USER_LOC_LAT',
       'ELVIS_USER_LOC_LONG', 'Distances', 'Consecutive_Flag'],
      dtype='object')

In [69]:
for value in unique_interv:
    total_records=distance_df[distance_df['INTERV_INIT']==value].shape[0]
    flag_records=distance_df[(distance_df['INTERV_INIT']==value)&(distance_df['Consecutive_Flag']==1)].shape[0]
    record_percentage=round((flag_records/total_records)*100,2)
    print(value,record_percentage)

ANC 3.26
LSS 4.95
CBB 0.0
MAO 0.0
MXG 0.0
JMV 0.0
DHC 0.0
LXF 6.76
NSH 13.79
TBT 0.0
SJG 39.13
CLB 0.0
LXO 36.73
JLD 0.0
GXG 58.73
BAM 45.45
DRM 0.0
MAD 0.0
RLC 0.0
EJP 30.16
RAB 0.0
JQT 99.3
HJT 11.76
KSB 54.21
LAJ 22.67
DKG 0.0
PLD 0.0
LDP 9.09
DAF 0.0
BBM 0.0
DMD 97.3
HSD 54.44
PCS 0.0
RJG 29.73
CAB 80.0
RWZ 15.62
JLS 0.0
JTC 8.15
Pld 0.0

In [55]:
# Overall df Summary Code starts here

In [62]:
over_all_data_df.head()

,INTERV_INIT,Total Records,Full Time Survey Records,Logistic Time Survey Records,Demographic Time Survey Records,Full Time Survey Percentage,Logistic Time Survey Percentage,Demographic Time Survey Percentage
0,ANC,399,193,9,363,48.37,2.26,90.98
1,LSS,202,18,2,153,8.91,0.99,75.74
2,CBB,47,2,0,26,4.26,0.00,55.32
3,MAO,20,0,0,10,0.00,0.00,50.00
4,MXG,10,0,0,0,0.00,0.00,0.00

In [57]:
grouped = over_all_data_df.groupby('INTERV_INIT').agg(
    Total_Records=('Total Records', 'sum'),
    Full_Time_Records_Percent=('Full Time Survey Percentage', 'mean'),
    Logistic_Time_Records_Percent=('Logistic Time Survey Percentage', 'mean'),
    Demographic_Time_Records_Percent=('Demographic Time Survey Percentage', 'mean'),
    Full_Time_Days_Over_25_Percent=('Full Time Survey Percentage', lambda x: (x > 25).mean() * 100),
    Logistic_Time_Days_Over_25_Percent=('Logistic Time Survey Percentage', lambda x: (x > 25).mean() * 100),
    Demographic_Time_Days_Over_25_Percent=('Demographic Time Survey Percentage', lambda x: (x > 25).mean() * 100)
).reset_index()

In [60]:
# Create a detailed summary description
def create_summary(row):
    description = (
        f"Summary for Interviewer {row['INTERV_INIT']}:"f"- Total Records: {row['Total_Records']}\n"
        f"- {row['Full_Time_Days_Over_25_Percent']:.1f}% of the days had over 25% of full survey records completed in under 4 minutes, affecting {row['Full_Time_Records_Percent']:.1f}% of total records.\n"
        f"- {row['Logistic_Time_Days_Over_25_Percent']:.1f}% of the days had over 25% of logistic part completed in under 2 minutes, affecting {row['Logistic_Time_Records_Percent']:.1f}% of total records.\n"
        f"- {row['Demographic_Time_Days_Over_25_Percent']:.1f}% of the days had over 25% of demographic part completed in under 2 minutes, affecting {row['Demographic_Time_Records_Percent']:.1f}% of total records."
    )
    return description

# Apply the summary function to each row
grouped['Description'] = grouped.apply(create_summary, axis=1)

# Output DataFrame with the description

In [61]:
grouped[['INTERV_INIT', 'Description']].to_csv('InterviewerOverallOneLineSummary.csv',index=False)

In [25]:
user_date=user_data['Survey Date'].values[0]

In [26]:
user_data[(user_data['Survey Date']==user_date)&(user_data['Full Survey Time Flag']==1)]['id'].values

array([14787, 14794, 14822, 14835, 14841, 14847, 14880, 14889, 14902,
       14904, 14907, 14908, 14915, 14927, 14932, 14934, 14953, 14961,
       14973, 14980, 15012, 15015, 15044, 15058, 15061, 15072, 15080,
       15095, 15098, 15105, 15109, 15114, 15376, 15385, 15393, 15401,
       15418, 15425, 15431, 15435, 15437, 15439, 15442, 15445, 15447,
       15449, 15469, 15477, 15480], dtype=int64)

In [27]:
len(user_data[(user_data['Survey Date']==user_date)&(user_data['Full Survey Time Flag']==1)]['id'].values)

49

In [28]:
checks_list=['Full Survey Time Flag','Logistics Time Flag','Demographic Time Flag']

In [29]:
for value in checks_list:
    print(len(user_data[(user_data['Survey Date']==user_date)&(user_data[value]==1)]['id'].values))

49
14
67

In [ ]:
asasas

In [70]:
over_all_data_df=pd.read_excel('reviewtool_20240911_DENVER_interviewerstats02.xlsx',sheet_name='Interviewer Overall Summary')
over_all_data_df.shape

(39, 9)

In [81]:
over_all_data_df.columns

Index(['INTERV_INIT', 'Total Records', 'Full Time Survey Records',
       'Logistic Time Survey Records', 'Demographic Time Survey Records',
       'Full Time Survey Percentage', 'Logistic Time Survey Percentage',
       'Demographic Time Survey Percentage', 'Location Distance Percentage'],
      dtype='object')

In [78]:
grouped = over_all_data_df.groupby('INTERV_INIT').agg(
    Total_Records=('Total Records', 'sum'),
    Full_Time_Records_Percent=('Full Time Survey Percentage', 'mean'),
    Logistic_Time_Records_Percent=('Logistic Time Survey Percentage', 'mean'),
    Demographic_Time_Records_Percent=('Demographic Time Survey Percentage', 'mean'),
    Location_Distance_Time_Records_Percent=('Location Distance Percentage', 'mean'),
    Full_Time_Days_Over_25_Percent=('Full Time Survey Percentage', lambda x: (x > 25).mean() * 100),
    Logistic_Time_Days_Over_25_Percent=('Logistic Time Survey Percentage', lambda x: (x > 25).mean() * 100),
    Demographic_Time_Days_Over_25_Percent=('Demographic Time Survey Percentage', lambda x: (x > 25).mean() * 100),
    Location_Distance_Time_Days_Over_25_Percent=('Location Distance Percentage', lambda x: (x > 25).mean() * 100)
).reset_index()

In [86]:
def create_summary(row):
#     description = (
#         f"Summary for Interviewer {row['INTERV_INIT']}:"f"- Total Records: {row['Total_Records']}\n"
#         f"- {row['Full_Time_Days_Over_25_Percent']:.1f}% of the days had over 25% of full survey records completed in under 4 minutes, affecting {row['Full_Time_Records_Percent']:.1f}% of total records.\n"
#         f"- {row['Logistic_Time_Days_Over_25_Percent']:.1f}% of the days had over 25% of logistic part completed in under 2 minutes, affecting {row['Logistic_Time_Records_Percent']:.1f}% of total records.\n"
#         f"- {row['Demographic_Time_Days_Over_25_Percent']:.1f}% of the days had over 25% of demographic part completed in under 2 minutes, affecting {row['Demographic_Time_Records_Percent']:.1f}% of total records.\n"
#         f"- {row['Location_Distance_Time_Days_Over_25_Percent']:.1f}% of the days had over 25% of their records being conducted within .25 miles of the previous survey, affecting {row['Location_Distance_Time_Records_Percent']:.1f}% of total records."
        
#     )
    description = (
        f"Summary for Interviewer {row['INTERV_INIT']}:\n"
        f"- Total Records: {row['Total_Records']}\n"
        f"- {row['Full_Time_Records_Percent']:.1f}% of full survey records were completed in under 4 minutes.\n"
        f"- {row['Logistic_Time_Records_Percent']:.1f}% of logistic part records were completed in under 2 minutes.\n"
        f"- {row['Demographic_Time_Records_Percent']:.1f}% of demographic part records were completed in under 2 minutes.\n"
        f"- {row['Location_Distance_Time_Records_Percent']:.1f}% of records were conducted within 0.25 miles of the previous survey."
    )
    return description

# Apply the summary function to each row
grouped['Description'] = grouped.apply(create_summary, axis=1)

In [87]:
grouped[['Description']][:1].values

array([['Summary for Interviewer ANC:\n- Total Records: 399\n- 48.4% of full survey records were completed in under 4 minutes.\n- 2.3% of logistic part records were completed in under 2 minutes.\n- 91.0% of demographic part records were completed in under 2 minutes.\n- 3.3% of records were conducted within 0.25 miles of the previous survey.']],
      dtype=object)