In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('elvislaguardia2024intercept_export_odbc.csv')
df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ELVIS_USER_CHANGE_7_C_DATE,ELVIS_USER_CHANGE_7_C_FIELD,ELVIS_USER_CHANGE_7_C_REASON,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,_REVERSE_TRIP,GENERATABLE_TRIPS
0,514,2024-07-24 13:56:09,87.0,en,2024-07-24 13:51:11,2024-07-24 13:56:09,50.202.171.186,https://laguardia-ny.etc-research.com/,-14400,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,522,2024-07-24 14:14:10,87.0,en,2024-07-24 14:06:11,2024-07-24 14:14:10,50.202.171.186,NaN,-14400,MDG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,524,2024-07-24 14:17:42,87.0,en,2024-07-24 14:16:08,2024-07-24 14:17:42,50.202.171.186,https://laguardia-ny.etc-research.com/index.php,-14400,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,525,2024-07-24 14:23:47,87.0,en,2024-07-24 14:17:44,2024-08-01 08:26:15,50.202.171.186,https://laguardia-ny.etc-research.com/index.ph...,-14400,999,...,\n\n,\n\n,\n\n,NaN,NaN,NaN,NaN,NaN,NaN,n1
4,528,2024-07-24 14:30:50,87.0,en,2024-07-24 14:19:21,2024-07-24 14:30:50,12.1.48.108,https://laguardia-ny.etc-research.com/,-14400,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
columns_names_check=['originaddresslat', 'originaddresslong', 'stoponlat', 'stoponlong', 'stopofflat', 'stopofflong', 'destinaddresslat', 'destinaddresslong']

In [4]:


def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [18]:
columns_names=check_all_characters_present(df,columns_names_check)
columns_names.sort()
columns_names

['DESTIN_ADDRESS_LAT',
 'DESTIN_ADDRESS_LONG',
 'ORIGIN_ADDRESS_LAT',
 'ORIGIN_ADDRESS_LONG',
 'STOP_OFF_LAT',
 'STOP_OFF_LONG',
 'STOP_ON_LAT',
 'STOP_ON_LONG']

In [14]:
new_df=df[columns_names][:5]

In [15]:
new_df

,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,STOP_OFF_LAT,STOP_OFF_LONG,STOP_ON_LAT,STOP_ON_LONG
0,NaN,NaN,40.726545,-73.941539,NaN,NaN,40.768790,-73.910815
1,NaN,NaN,40.773656,-73.959860,NaN,NaN,40.801818,-73.967642
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40.747929,-73.943983,NaN,NaN,40.773656,-73.95986,NaN,NaN
4,NaN,NaN,40.706672,-73.960228,NaN,NaN,40.746543,-73.890686

In [10]:
missing_address_lat=40.77292364642215
missing_address_long=-73.87219764178501
missing_address_lat,missing_address_long

(40.77292364642215, -73.87219764178501)

In [12]:
for _, row in new_df.iterrows():
    '''
    column_names=['DESTIN_ADDRESS_LAT',
     'DESTIN_ADDRESS_LONG',
     'ORIGIN_ADDRESS_LAT',
     'ORIGIN_ADDRESS_LONG',
     'STOP_OFF_LAT',
     'STOP_OFF_LONG',
     'STOP_ON_LAT',
     'STOP_ON_LONG']
    '''
    if pd.isna(row[columns_names[2]]) and pd.isna(row[columns_names[3]]):
        new_df.loc[row.name,columns_names[2]]=missing_address_lat
        new_df.loc[row.name,columns_names[3]]=missing_address_long
    if pd.isna(row[columns_names[6]]) and pd.isna(row[columns_names[7]]):
        new_df.loc[row.name,columns_names[6]]=missing_address_lat
        new_df.loc[row.name,columns_names[7]]=missing_address_long
    if pd.isna(row[columns_names[4]]) and pd.isna(row[columns_names[5]]):
        new_df.loc[row.name,columns_names[4]]=missing_address_lat
        new_df.loc[row.name,columns_names[5]]=missing_address_long
    if pd.isna(row[columns_names[0]]) and pd.isna(row[columns_names[1]]):
        new_df.loc[row.name,columns_names[0]]=missing_address_lat
        new_df.loc[row.name,columns_names[1]]=missing_address_long

In [13]:
new_df

,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,STOP_ON_LAT,STOP_ON_LONG,STOP_OFF_LAT,STOP_OFF_LONG
0,40.726545,-73.941539,40.772924,-73.872198,40.768790,-73.910815,40.772924,-73.872198
1,40.773656,-73.959860,40.772924,-73.872198,40.801818,-73.967642,40.772924,-73.872198
2,40.772924,-73.872198,40.772924,-73.872198,40.772924,-73.872198,40.772924,-73.872198
3,40.772924,-73.872198,40.747929,-73.943983,40.772924,-73.872198,40.773656,-73.959860
4,40.706672,-73.960228,40.772924,-73.872198,40.746543,-73.890686,40.772924,-73.872198

In [16]:
new_df

,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,STOP_OFF_LAT,STOP_OFF_LONG,STOP_ON_LAT,STOP_ON_LONG
0,NaN,NaN,40.726545,-73.941539,NaN,NaN,40.768790,-73.910815
1,NaN,NaN,40.773656,-73.959860,NaN,NaN,40.801818,-73.967642
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,40.747929,-73.943983,NaN,NaN,40.773656,-73.95986,NaN,NaN
4,NaN,NaN,40.706672,-73.960228,NaN,NaN,40.746543,-73.890686

In [19]:
def fill_missing_coordinates(row, missing_lat, missing_long, columns):
    for i in range(0, len(columns), 2):
        lat_col, long_col = columns[i], columns[i+1]
        if pd.isna(row[lat_col]) and pd.isna(row[long_col]):
            row[lat_col] = missing_lat
            row[long_col] = missing_long
    return row

# Apply the function to the DataFrame
new_df = new_df.apply(fill_missing_coordinates, axis=1, 
                      missing_lat=missing_address_lat, 
                      missing_long=missing_address_long, 
                      columns=columns_names)

In [20]:
new_df

,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,STOP_OFF_LAT,STOP_OFF_LONG,STOP_ON_LAT,STOP_ON_LONG
0,40.772924,-73.872198,40.726545,-73.941539,40.772924,-73.872198,40.768790,-73.910815
1,40.772924,-73.872198,40.773656,-73.959860,40.772924,-73.872198,40.801818,-73.967642
2,40.772924,-73.872198,40.772924,-73.872198,40.772924,-73.872198,40.772924,-73.872198
3,40.747929,-73.943983,40.772924,-73.872198,40.773656,-73.959860,40.772924,-73.872198
4,40.772924,-73.872198,40.706672,-73.960228,40.772924,-73.872198,40.746543,-73.890686

In [21]:
df=df.apply(fill_missing_coordinates, axis=1, 
                      missing_lat=missing_address_lat, 
                      missing_long=missing_address_long, 
                      columns=columns_names)

In [23]:
df[columns_names]

,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,STOP_OFF_LAT,STOP_OFF_LONG,STOP_ON_LAT,STOP_ON_LONG
0,40.772924,-73.872198,40.726545,-73.941539,40.772924,-73.872198,40.768790,-73.910815
1,40.772924,-73.872198,40.773656,-73.959860,40.772924,-73.872198,40.801818,-73.967642
2,40.772924,-73.872198,40.772924,-73.872198,40.772924,-73.872198,40.772924,-73.872198
3,40.747929,-73.943983,40.772924,-73.872198,40.773656,-73.959860,40.772924,-73.872198
4,40.772924,-73.872198,40.706672,-73.960228,40.772924,-73.872198,40.746543,-73.890686
...,...,...,...,...,...,...,...,...
951,40.806112,-73.944892,40.772924,-73.872198,40.808026,-73.945928,40.772924,-73.872198
952,40.744498,-73.914633,40.772924,-73.872198,40.745704,-73.901994,40.772924,-73.872198
953,40.756697,-73.961160,40.772924,-73.872198,40.746819,-73.891252,40.772924,-73.872198
954,40.747929,-73.943983,40.772924,-73.872198,40.773730,-73.960822,40.772924,-73.872198
955,40.772924,-73.872198,40.710212,-73.948493,40.772924,-73.872198,40.772924,-73.872198

In [24]:
df.to_csv('elvislaguardia2024intercept_export_odbc_filled.csv',index=False)