In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import warnings

warnings.filterwarnings('ignore')

I’ve implemented code to generate the O2O_STOPS sheet similarly to the original one.
Here's how it works:
I extracted the line name from the database (e.g., "BLUE_LINE_NB_ON" became "BlueLine").
From the details_file (sheet "STOPS"), I also extracted line names (e.g., "VTA_2_GreenLine_00" became "GreenLine").
I then compared the line names and stop names from both files.
If they matched, I included information such as ‘seq_fixed,’ ‘ETC_STOP_NAME,’ ‘ETC_STOP_ID,’ ‘ETC_ROUTE_ID,’ and ‘ETC_ROUTE_NAME’ from the database to build the final output.

In [2]:

def check_all_code_columns(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df_columns_lower if "code" in column]

    return matching_columns


def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

def clean_string(s):
    return s.replace(':', '').replace('-', '').replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

In [3]:
project_name='VTA'

df=pd.read_csv('vtaca2024rail_o2o_export_odbc.csv')

# df=df[df['INTERV_INIT']!='999']

detail_df=pd.read_excel('details_vta_CA_od_excel (1).xlsx',sheet_name='STOPS')

In [4]:
detail_df.columns

Index(['agency', 'gtfs_ver', 'gtfs_date', 'route_short_name',
       'route_long_name', 'direction_id', 'route_dir', 'seq_fixed', 'stop_id',
       'stop_name', 'stop_lat', 'stop_lon', 'stop_lat6', 'stop_lon6',
       'ETC_STOP_ID', 'ETC_STOP_NAME', 'notes', 'ETC_ROUTE_ID',
       'ETC_ROUTE_NAME'],
      dtype='object')

In [5]:
df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', '_INTERV_INIT',
       'TIME_ADJUST', 'ORIGRESPID', 'ROUTE_SURVEYED_Code_', 'ROUTE_SURVEYED',
       'BLUE_LINE_NB_ON_Code_', 'BLUE_LINE_NB_ON', 'BLUE_LINE_NB_OFF_Code_',
       'BLUE_LINE_NB_OFF', 'BLUE_LIME_SB_ON_Code_', 'BLUE_LIME_SB_ON',
       'BLUE_LIME_SB_OFF_Code_', 'BLUE_LIME_SB_OFF', 'GREEN_LINE_NB_ON_Code_',
       'GREEN_LINE_NB_ON', 'GREEN_LINE_NB_OFF_Code_', 'GREEN_LINE_NB_OFF',
       'GREEN_LINE_SB_ON_Code_', 'GREEN_LINE_SB_ON', 'GREEN_LINE_SB_OFF_Code_',
       'GREEN_LINE_SB_OFF', 'ORANGE_LINE_EB_ON_Code_', 'ORANGE_LINE_EB_ON',
       'ORANGE_LINE_EB_OFF_Code_', 'ORANGE_LINE_EB_OFF',
       'ORANGE_LINE_WB_ON_Code_', 'ORANGE_LINE_WB_ON',
       'ORANGE_LINE_WB_OFF_Code_', 'ORANGE_LINE_WB_OFF', 'TIME_BOARDED_Code_',
       'TIME_BOARDED', 'RESTART_URL'],
      dtype='object')

In [6]:
code_columns=check_all_code_columns(df,df.columns)

code_columns=check_all_characters_present(df,code_columns)
code_columns

['ROUTE_SURVEYED_Code_',
 'BLUE_LINE_NB_ON_Code_',
 'BLUE_LINE_NB_OFF_Code_',
 'BLUE_LIME_SB_ON_Code_',
 'BLUE_LIME_SB_OFF_Code_',
 'GREEN_LINE_NB_ON_Code_',
 'GREEN_LINE_NB_OFF_Code_',
 'GREEN_LINE_SB_ON_Code_',
 'GREEN_LINE_SB_OFF_Code_',
 'ORANGE_LINE_EB_ON_Code_',
 'ORANGE_LINE_EB_OFF_Code_',
 'ORANGE_LINE_WB_ON_Code_',
 'ORANGE_LINE_WB_OFF_Code_',
 'TIME_BOARDED_Code_']

In [7]:
detail_df['LineName']=detail_df['ETC_ROUTE_ID'].apply(lambda x: str(x).split('_')[2])

In [8]:
'VTA_2_GreenLine_00'.split('_')[2]

'GreenLine'

In [9]:
detail_df.query('LineName=="GreenLine"')

,agency,gtfs_ver,gtfs_date,route_short_name,route_long_name,direction_id,route_dir,seq_fixed,stop_id,stop_name,stop_lat,stop_lon,stop_lat6,stop_lon6,ETC_STOP_ID,ETC_STOP_NAME,notes,ETC_ROUTE_ID,ETC_ROUTE_NAME,LineName
4388,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,1,5380,Winchester Station,37.279610,-121.947906,37.279610,-121.947906,VTA_2_GreenLine_00_5380,Winchester Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4389,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,2,5379,Campbell Station,37.285900,-121.943027,37.285900,-121.943027,VTA_2_GreenLine_00_5379,Campbell Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4390,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,3,5378,Hamilton Station,37.294064,-121.936167,37.294064,-121.936167,VTA_2_GreenLine_00_5378,Hamilton Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4391,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,4,5377,Bascom Station,37.299851,-121.929830,37.299851,-121.929830,VTA_2_GreenLine_00_5377,Bascom Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4392,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,5,5376,Fruitdale Station,37.310482,-121.918017,37.310482,-121.918017,VTA_2_GreenLine_00_5376,Fruitdale Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4393,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,6,5375,Race Station,37.317567,-121.910314,37.317567,-121.910314,VTA_2_GreenLine_00_5375,Race Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4394,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,7,5374,Diridon Station,37.328947,-121.903511,37.328947,-121.903511,VTA_2_GreenLine_00_5374,Diridon Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4395,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,8,5388,San Fernando Station,37.330367,-121.898116,37.330367,-121.898116,VTA_2_GreenLine_00_5388,San Fernando Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4396,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,9,4746,Convention Center Station,37.330168,-121.889754,37.330168,-121.889754,VTA_2_GreenLine_00_4746,Convention Center Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4397,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,10,4747,San Antonio Station,37.332782,-121.887979,37.332782,-121.887979,VTA_2_GreenLine_00_4747,San Antonio Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4398,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,11,4748,Santa Clara Station,37.335924,-121.890354,37.335924,-121.890354,VTA_2_GreenLine_00_4748,Santa Clara Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4399,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,12,4749,Saint James Station,37.338402,-121.892183,37.338402,-121.892183,VTA_2_GreenLine_00_4749,Saint James Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4400,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,13,4750,Japantown/Ayer Station,37.345557,-121.897559,37.345557,-121.897559,VTA_2_GreenLine_00_4750,Japantown/Ayer Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4401,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,14,4751,Civic Center Station,37.352016,-121.902434,37.352016,-121.902434,VTA_2_GreenLine_00_4751,Civic Center Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4402,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,15,4752,Gish Station,37.362544,-121.910160,37.362544,-121.910160,VTA_2_GreenLine_00_4752,Gish Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4403,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,16,4753,Metro/Airport Station,37.370364,-121.915990,37.370364,-121.915990,VTA_2_GreenLine_00_4753,Metro/Airport Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4404,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,17,4754,Karina Station,37.376278,-121.920405,37.376278,-121.920405,VTA_2_GreenLine_00_4754,Karina Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4405,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,18,4755,Component Station,37.383483,-121.925777,37.383483,-121.925777,VTA_2_GreenLine_00_4755,Component Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4406,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,19,4756,Bonaventura Station,37.388749,-121.929742,37.388749,-121.929742,VTA_2_GreenLine_00_4756,Bonaventura Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4407,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,20,4757,Orchard Station,37.395730,-121.934869,37.395730,-121.934869,VTA_2_GreenLine_00_4757,Orchard Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4408,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,21,4758,River Oaks Station,37.402847,-121.940027,37.402847,-121.940027,VTA_2_GreenLine_00_4758,River Oaks Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4409,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,22,4759,Tasman Station,37.408669,-121.944463,37.408669,-121.944463,VTA_2_GreenLine_00_4759,Tasman Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4410,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,23,4801,Baypointe Station,37.410877,-121.941523,37.410877,-121.941523,VTA_2_GreenLine_00_4801,Baypointe Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4411,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,24,4807,Champion Station,37.409423,-121.952616,37.409423,-121.952616,VTA_2_GreenLine_00_4807,Champion Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4412,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,25,4808,Lick Mill Station,37.407616,-121.963679,37.407616,-121.963679,VTA_2_GreenLine_00_4808,Lick Mill Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4413,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,26,4809,Great America Station,37.403468,-121.974908,37.403468,-121.974908,VTA_2_GreenLine_00_4809,Great America Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4414,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,27,4810,Old Ironsides Station,37.403309,-121.979862,37.403309,-121.979862,VTA_2_GreenLine_00_4810,Old Ironsides Station,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4415,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,0,GreenLine_0,28,5866,PATRICK HENRY POCKET TRACK,37.403489,-121.984251,37.403489,-121.984251,VTA_2_GreenLine_00_5866,PATRICK HENRY POCKET TRACK,NaN,VTA_2_GreenLine_00,Green Line - Old Ironsides - Winchester [North...,GreenLine
4416,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,1,4797,Old Ironsides Station,37.403299,-121.978871,37.403299,-121.978871,VTA_2_GreenLine_01_4797,Old Ironsides Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4417,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,2,4798,Great America Station,37.403555,-121.974058,37.403555,-121.974058,VTA_2_GreenLine_01_4798,Great America Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4418,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,3,4799,Lick Mill Station,37.407795,-121.962925,37.407795,-121.962925,VTA_2_GreenLine_01_4799,Lick Mill Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4419,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,4,4800,Champion Station,37.408898,-121.951936,37.408898,-121.951936,VTA_2_GreenLine_01_4800,Champion Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4420,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,5,4761,Baypointe Station,37.410438,-121.942311,37.410438,-121.942311,VTA_2_GreenLine_01_4761,Baypointe Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4421,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,6,4762,Tasman Station,37.408056,-121.943998,37.408056,-121.943998,VTA_2_GreenLine_01_4762,Tasman Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4422,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,7,4763,River Oaks Station,37.401188,-121.938972,37.401188,-121.938972,VTA_2_GreenLine_01_4763,River Oaks Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4423,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,8,4764,Orchard Station,37.394082,-121.933837,37.394082,-121.933837,VTA_2_GreenLine_01_4764,Orchard Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4424,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,9,4765,Bonaventura Station,37.387197,-121.928715,37.387197,-121.928715,VTA_2_GreenLine_01_4765,Bonaventura Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4425,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,10,4766,Component Station,37.381937,-121.924755,37.381937,-121.924755,VTA_2_GreenLine_01_4766,Component Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4426,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,11,4767,Karina Station,37.374609,-121.919317,37.374609,-121.919317,VTA_2_GreenLine_01_4767,Karina Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4427,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,12,4768,Metro/Airport Station,37.368664,-121.914883,37.368664,-121.914883,VTA_2_GreenLine_01_4768,Metro/Airport Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4428,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,13,4769,Gish Station,37.360938,-121.909099,37.360938,-121.909099,VTA_2_GreenLine_01_4769,Gish Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4429,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,14,4770,Civic Center Station,37.351380,-121.901956,37.351380,-121.901956,VTA_2_GreenLine_01_4770,Civic Center Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4430,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,15,4771,Japantown/Ayer Station,37.344964,-121.897116,37.344964,-121.897116,VTA_2_GreenLine_01_4771,Japantown/Ayer Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4431,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,16,4772,Saint James Station,37.338358,-121.890805,37.338358,-121.890805,VTA_2_GreenLine_01_4772,Saint James Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4432,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,17,4773,Santa Clara Station,37.335796,-121.888910,37.335796,-121.888910,VTA_2_GreenLine_01_4773,Santa Clara Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4433,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,18,4774,San Antonio Station,37.333481,-121.887188,37.333481,-121.887188,VTA_2_GreenLine_01_4774,San Antonio Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4434,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,19,4775,Convention Center Station,37.329809,-121.890538,37.329809,-121.890538,VTA_2_GreenLine_01_4775,Convention Center Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4435,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,20,5389,San Fernando Station,37.330248,-121.899045,37.330248,-121.899045,VTA_2_GreenLine_01_5389,San Fernando Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4436,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,21,5381,Diridon Station,37.328296,-121.903588,37.328296,-121.903588,VTA_2_GreenLine_01_5381,Diridon Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4437,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,22,5382,Race Station,37.317155,-121.910753,37.317155,-121.910753,VTA_2_GreenLine_01_5382,Race Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4438,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,23,5383,Fruitdale Station,37.310122,-121.918483,37.310122,-121.918483,VTA_2_GreenLine_01_5383,Fruitdale Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4439,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,24,5384,Bascom Station,37.299467,-121.930304,37.299467,-121.930304,VTA_2_GreenLine_01_5384,Bascom Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4440,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,25,5385,Hamilton Station,37.293691,-121.936576,37.293691,-121.936576,VTA_2_GreenLine_01_5385,Hamilton Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4441,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,26,5386,Campbell Station,37.285483,-121.943395,37.285483,-121.943395,VTA_2_GreenLine_01_5386,Campbell Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine
4442,VTA,2,8/7/2024,GreenLine,Old Ironsides - Winchester,1,GreenLine_1,27,5387,Winchester Station,37.279178,-121.948307,37.279178,-121.948307,VTA_2_GreenLine_01_5387,Winchester Station,NaN,VTA_2_GreenLine_01,Green Line - Old Ironsides - Winchester [South...,GreenLine

In [10]:
detail_df[['LineName']]

        LineName
0             20
1             20
2             20
3             20
4             20
...          ...
5057  School288M
5058       SCVMC
5059       SCVMC
5060       SCVMC
5061       SCVMC

[5062 rows x 1 columns]

In [11]:
df[[
 'BLUE_LINE_NB_ON_Code_',
 'BLUE_LINE_NB_OFF_Code_',
 'BLUE_LIME_SB_ON_Code_',
 'BLUE_LIME_SB_OFF_Code_',
 'GREEN_LINE_NB_ON_Code_',
 'GREEN_LINE_NB_OFF_Code_',
 'GREEN_LINE_SB_ON_Code_',
 'GREEN_LINE_SB_OFF_Code_',
 'ORANGE_LINE_EB_ON_Code_',
 'ORANGE_LINE_EB_OFF_Code_',
 'ORANGE_LINE_WB_ON_Code_',
 'ORANGE_LINE_WB_OFF_Code_',]]

,BLUE_LINE_NB_ON_Code_,BLUE_LINE_NB_OFF_Code_,BLUE_LIME_SB_ON_Code_,BLUE_LIME_SB_OFF_Code_,GREEN_LINE_NB_ON_Code_,GREEN_LINE_NB_OFF_Code_,GREEN_LINE_SB_ON_Code_,GREEN_LINE_SB_OFF_Code_,ORANGE_LINE_EB_ON_Code_,ORANGE_LINE_EB_OFF_Code_,ORANGE_LINE_WB_ON_Code_,ORANGE_LINE_WB_OFF_Code_
0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,4.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,16.0,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,26.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
6834,22.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6835,NaN,NaN,NaN,NaN,23.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN
6836,NaN,NaN,NaN,NaN,23.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN
6837,NaN,NaN,NaN,NaN,22.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN
6838,NaN,NaN,NaN,NaN,23.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
def get_line_name(row):
    if pd.notna(row['BLUE_LINE_NB_ON_Code_']) or pd.notna(row['BLUE_LINE_NB_OFF_Code_']):
        return 'BlueLine'
    elif pd.notna(row['BLUE_LIME_SB_ON_Code_']) or pd.notna(row['BLUE_LIME_SB_OFF_Code_']):
        return 'BlueLine'
    elif pd.notna(row['GREEN_LINE_NB_ON_Code_']) or pd.notna(row['GREEN_LINE_NB_OFF_Code_']):
        return 'GreenLine'
    elif pd.notna(row['GREEN_LINE_SB_ON_Code_']) or pd.notna(row['GREEN_LINE_SB_OFF_Code_']):
        return 'GreenLine'
    elif pd.notna(row['ORANGE_LINE_EB_ON_Code_']) or pd.notna(row['ORANGE_LINE_EB_OFF_Code_']):
        return 'OrangeLine'
    elif pd.notna(row['ORANGE_LINE_WB_ON_Code_']) or pd.notna(row['ORANGE_LINE_WB_OFF_Code_']):
        return 'OrangeLine'
    else:
        return 'Unknown'

In [13]:
def get_line_name(row):
    if pd.notna(row['BLUE_LINE_NB_ON_Code_']) or pd.notna(row['BLUE_LINE_NB_OFF_Code_']):
        return 'BlueLine', row['BLUE_LINE_NB_ON']
    elif pd.notna(row['BLUE_LIME_SB_ON_Code_']) or pd.notna(row['BLUE_LIME_SB_OFF_Code_']):
        return 'BlueLine', row['BLUE_LIME_SB_ON']
    elif pd.notna(row['GREEN_LINE_NB_ON_Code_']) or pd.notna(row['GREEN_LINE_NB_OFF_Code_']):
        return 'GreenLine', row['GREEN_LINE_NB_ON']
    elif pd.notna(row['GREEN_LINE_SB_ON_Code_']) or pd.notna(row['GREEN_LINE_SB_OFF_Code_']):
        return 'GreenLine', row['GREEN_LINE_SB_ON']
    elif pd.notna(row['ORANGE_LINE_EB_ON_Code_']) or pd.notna(row['ORANGE_LINE_EB_OFF_Code_']):
        return 'OrangeLine', row['ORANGE_LINE_EB_ON']
    elif pd.notna(row['ORANGE_LINE_WB_ON_Code_']) or pd.notna(row['ORANGE_LINE_WB_OFF_Code_']):
        return 'OrangeLine', row['ORANGE_LINE_WB_ON']
    else:
        return 'Unknown', ''

In [14]:
def get_line_name(row):
    if pd.notna(row['BLUE_LINE_NB_ON_Code_']) or pd.notna(row['BLUE_LINE_NB_OFF_Code_']):
        on_stop = row['BLUE_LINE_NB_ON'] if pd.notna(row['BLUE_LINE_NB_ON']) else ''
        off_stop = row['BLUE_LINE_NB_OFF'] if pd.notna(row['BLUE_LINE_NB_OFF']) else ''
        return 'BlueLine', on_stop , off_stop
    elif pd.notna(row['BLUE_LIME_SB_ON_Code_']) or pd.notna(row['BLUE_LIME_SB_OFF_Code_']):
        on_stop = row['BLUE_LIME_SB_ON'] if pd.notna(row['BLUE_LIME_SB_ON']) else ''
        off_stop = row['BLUE_LIME_SB_OFF'] if pd.notna(row['BLUE_LIME_SB_OFF']) else ''
        return 'BlueLine', on_stop, off_stop
    elif pd.notna(row['GREEN_LINE_NB_ON_Code_']) or pd.notna(row['GREEN_LINE_NB_OFF_Code_']):
        on_stop = row['GREEN_LINE_NB_ON'] if pd.notna(row['GREEN_LINE_NB_ON']) else ''
        off_stop = row['GREEN_LINE_NB_OFF'] if pd.notna(row['GREEN_LINE_NB_OFF']) else ''
        return 'GreenLine', on_stop , off_stop
    elif pd.notna(row['GREEN_LINE_SB_ON_Code_']) or pd.notna(row['GREEN_LINE_SB_OFF_Code_']):
        on_stop = row['GREEN_LINE_SB_ON'] if pd.notna(row['GREEN_LINE_SB_ON']) else ''
        off_stop = row['GREEN_LINE_SB_OFF'] if pd.notna(row['GREEN_LINE_SB_OFF']) else ''
        return 'GreenLine', on_stop, off_stop
    elif pd.notna(row['ORANGE_LINE_EB_ON_Code_']) or pd.notna(row['ORANGE_LINE_EB_OFF_Code_']):
        on_stop = row['ORANGE_LINE_EB_ON'] if pd.notna(row['ORANGE_LINE_EB_ON']) else ''
        off_stop = row['ORANGE_LINE_EB_OFF'] if pd.notna(row['ORANGE_LINE_EB_OFF']) else ''
        return 'OrangeLine', on_stop , off_stop
    elif pd.notna(row['ORANGE_LINE_WB_ON_Code_']) or pd.notna(row['ORANGE_LINE_WB_OFF_Code_']):
        on_stop = row['ORANGE_LINE_WB_ON'] if pd.notna(row['ORANGE_LINE_WB_ON']) else ''
        off_stop = row['ORANGE_LINE_WB_OFF'] if pd.notna(row['ORANGE_LINE_WB_OFF']) else ''
        return 'OrangeLine', on_stop , off_stop
    else:
        return 'Unknown', '', ''

In [15]:
code_columns[1:-1]

['BLUE_LINE_NB_ON_Code_',
 'BLUE_LINE_NB_OFF_Code_',
 'BLUE_LIME_SB_ON_Code_',
 'BLUE_LIME_SB_OFF_Code_',
 'GREEN_LINE_NB_ON_Code_',
 'GREEN_LINE_NB_OFF_Code_',
 'GREEN_LINE_SB_ON_Code_',
 'GREEN_LINE_SB_OFF_Code_',
 'ORANGE_LINE_EB_ON_Code_',
 'ORANGE_LINE_EB_OFF_Code_',
 'ORANGE_LINE_WB_ON_Code_',
 'ORANGE_LINE_WB_OFF_Code_']

In [16]:
# df['LineNameDatabase'] = df[code_columns[1:-1]].apply(get_line_name, axis=1)

# Apply the function to create the new columns
df[['LineNameDatabase', 'ON_STOP_NAME','OFF_STOP_NAME']] = df.apply(get_line_name, axis=1, result_type='expand')

In [18]:
df[['LineNameDatabase', 'ON_STOP_NAME','OFF_STOP_NAME']]

     LineNameDatabase   ON_STOP_NAME  OFF_STOP_NAME
0           GreenLine     Winchester     Winchester
1            BlueLine   Santa Teresa         Tamien
2            BlueLine        Orchard  Metro/Airport
3          OrangeLine  Great America      Baypointe
4          OrangeLine      Cisco Way      Alum Rock
...               ...            ...            ...
6834         BlueLine    Bonaventure      Baypointe
6835        GreenLine       Champion  Old Ironsides
6836        GreenLine       Champion  Great America
6837        GreenLine         Tasman  Old Ironsides
6838        GreenLine       Champion  Old Ironsides

[6839 rows x 3 columns]

In [19]:
unique_line_names=df['LineNameDatabase'].unique()
unique_line_names

array(['GreenLine', 'BlueLine', 'OrangeLine'], dtype=object)

In [20]:
unique_on_stop_names=df['ON_STOP_NAME'].unique()
unique_off_stop_names=df['OFF_STOP_NAME'].unique()
unique_on_stop_names,unique_off_stop_names

(array(['Winchester', 'Santa Teresa', 'Orchard', 'Great America',
        'Cisco Way', 'Champion', 'Alder', 'Tasman', 'Bonaventure',
        'Hamilton', 'Baypointe', 'Gish', 'River Oaks', 'Mountainview',
        'Metro/Airport', 'Great Mall', 'Middlefield', 'Civic Center',
        'Japantown/Ayer', 'Milipitas', 'St. James', 'Alum Rock',
        'Old Ironsides', 'Santa Clara', 'Lick Kill', 'Penitencia Creek',
        'Convention Center', 'McKee', 'Children’s Discovery Museum',
        'Virginia', 'Tamien', 'Curtner', 'Capitol', 'Paseo de San Antonio',
        'Snell', 'Cottle', 'Ohlone/Chynoweth', 'Paseo de San Antonion',
        'Branham', 'Karina', 'San Jose Diridon', 'San Fernando',
        'Blossom Hill', 'Berryessa', 'Hostetter', 'Fruitdale', 'Bascom',
        'Downtown Campbell', 'Cropley', 'Race', 'Lick Mill', 'Fair Oaks',
        'Crossman', 'Whisman', 'Vienna', 'Reamwood', 'Component',
        'Moffett Park', 'Lockheed Martin', 'Bayshore/NASA', 'Borregas'],
       dtype=object),
 array(['Winchester', 'Tamien', 'Metro/Airport', 'Baypointe', 'Alum Rock',
        'McKee', 'Great Mall', 'Milipitas', 'Karina', 'Hamilton',
        'Santa Clara', 'Bonaventure', 'Paseo de San Antonio', 'Component',
        'Santa Teresa', 'Virginia', 'Cottle', 'Cisco Way', 'St. James',
        'Convention Center', 'Berryessa', 'Hostetter', 'Orchard',
        'Ohlone/Chynoweth', 'Curtner', 'Branham', 'Capitol',
        'Blossom Hill', 'San Jose Diridon', 'Civic Center', 'Borregas',
        'Japantown/Ayer', 'Paseo de San Antonion',
        'Children’s Discovery Museum', 'San Fernando', 'Champion',
        'Crossman', 'Bascom', 'Old Ironsides', 'Fruitdale',
        'Downtown Campbell', 'Whisman', 'Vienna', 'Tasman', 'Race', 'Gish',
        'River Oaks', 'Mountainview', 'Alder', 'Fair Oaks', 'Moffett Park',
        'Lockheed Martin', 'Middlefield', 'Reamwood', 'Snell',
        'Great America', 'Lick Mill', 'Cropley', 'Bayshore/NASA',
        'Lick Kill', 'Penitencia Creek'], dtype=object))

In [23]:
# Combine unique values from both ON and OFF stop names and remove duplicates
unique_stop_names = set(unique_on_stop_names).union(set(unique_off_stop_names))

# Convert the set back to a list if needed
unique_stop_names = list(unique_stop_names)

len(unique_stop_names)

61

In [ ]:
# Old Code

# unique_stop_names=df['STOP_NAME'].unique()
# unique_stop_names

In [25]:
# unique_stop_names.size

In [26]:
df.query('LineNameDatabase=="BlueLine"')[code_columns[1:-1]]

,BLUE_LINE_NB_ON_Code_,BLUE_LINE_NB_OFF_Code_,BLUE_LIME_SB_ON_Code_,BLUE_LIME_SB_OFF_Code_,GREEN_LINE_NB_ON_Code_,GREEN_LINE_NB_OFF_Code_,GREEN_LINE_SB_ON_Code_,GREEN_LINE_SB_OFF_Code_,ORANGE_LINE_EB_ON_Code_,ORANGE_LINE_EB_OFF_Code_,ORANGE_LINE_WB_ON_Code_,ORANGE_LINE_WB_OFF_Code_
1,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,4.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,2.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,5.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,1.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
6830,14.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6831,14.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6832,19.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6833,20.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6834,22.0,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
detail_df=detail_df.query('route_short_name.isin(@unique_line_names)')

In [32]:
detail_df.reset_index(inplace=True,drop=True)

In [33]:
detail_df.head()

,agency,gtfs_ver,gtfs_date,route_short_name,route_long_name,direction_id,route_dir,seq_fixed,stop_id,stop_name,stop_lat,stop_lon,stop_lat6,stop_lon6,ETC_STOP_ID,ETC_STOP_NAME,notes,ETC_ROUTE_ID,ETC_ROUTE_NAME,LineName
0,VTA,2,8/7/2024,BlueLine,Baypointe - Santa Teresa,0,BlueLine_0,1,4736,Santa Teresa Station,37.236668,-121.789141,37.236668,-121.789141,VTA_2_BlueLine_00_4736,Santa Teresa Station,NaN,VTA_2_BlueLine_00,Blue Line - Baypointe - Santa Teresa [Northbou...,BlueLine
1,VTA,2,8/7/2024,BlueLine,Baypointe - Santa Teresa,0,BlueLine_0,2,4737,Cottle Station,37.242732,-121.803159,37.242732,-121.803159,VTA_2_BlueLine_00_4737,Cottle Station,NaN,VTA_2_BlueLine_00,Blue Line - Baypointe - Santa Teresa [Northbou...,BlueLine
2,VTA,2,8/7/2024,BlueLine,Baypointe - Santa Teresa,0,BlueLine_0,3,4738,Snell Station,37.248055,-121.831339,37.248055,-121.831339,VTA_2_BlueLine_00_4738,Snell Station,NaN,VTA_2_BlueLine_00,Blue Line - Baypointe - Santa Teresa [Northbou...,BlueLine
3,VTA,2,8/7/2024,BlueLine,Baypointe - Santa Teresa,0,BlueLine_0,4,4739,Blossom Hill Station,37.253150,-121.841811,37.253150,-121.841811,VTA_2_BlueLine_00_4739,Blossom Hill Station,NaN,VTA_2_BlueLine_00,Blue Line - Baypointe - Santa Teresa [Northbou...,BlueLine
4,VTA,2,8/7/2024,BlueLine,Baypointe - Santa Teresa,0,BlueLine_0,5,4731,Ohlone-Chynoweth Station,37.257993,-121.859666,37.257993,-121.859666,VTA_2_BlueLine_00_4731,Ohlone-Chynoweth Station,NaN,VTA_2_BlueLine_00,Blue Line - Baypointe - Santa Teresa [Northbou...,BlueLine

In [34]:
detail_df.query('route_short_name=="GreenLine" and "Winchester".lower() in ETC_STOP_NAME')

Empty DataFrame
Columns: [agency, gtfs_ver, gtfs_date, route_short_name, route_long_name, direction_id, route_dir, seq_fixed, stop_id, stop_name, stop_lat, stop_lon, stop_lat6, stop_lon6, ETC_STOP_ID, ETC_STOP_NAME, notes, ETC_ROUTE_ID, ETC_ROUTE_NAME, LineName]
Index: []

In [ ]:
detail_df.query(
    'LineName == "GreenLine" and '
    'ETC_STOP_NAME.str.lower().str.contains("winchester") and '
    'ETC_ROUTE_ID.str.split("_").str[-1] != "01"', 
    engine='python'
)

In [ ]:
# results = []
# for line_name in unique_line_names:
#     for stop_name in unique_stop_names:
#         # Filter the DataFrame based on the given conditions
#         filtered_df = detail_df.query(
#             f'LineName == "{line_name}" and '
#             f'ETC_STOP_NAME.str.lower().str.contains("{stop_name.lower()}") and '
#             f'ETC_ROUTE_ID.str.split("_").str[-1] != "01"',
#             engine='python'
#         )
#         # If the combination is found, add it to the results
#         if not filtered_df.empty:
#             results.append((line_name, stop_name, filtered_df))

In [ ]:
results = []
for line_name in unique_line_names:
    for stop_name in unique_stop_names:
        # Filter the DataFrame based on the given conditions
        filtered_df = detail_df.query(
            f'LineName == "{line_name}" and '
            f'ETC_STOP_NAME.str.lower().str.contains("{stop_name.lower()}")',
            engine='python'
        )
        # If the combination is found, add it to the results
        if not filtered_df.empty:
            results.append((line_name, stop_name, filtered_df))

In [ ]:
for line_name, stop_name, df in results:
    print(f'Combination found: LineName = {line_name}, StopName = {stop_name}')
    print(df)

In [37]:
results = []

# Loop through each combination of line name and stop name
for line_name in unique_line_names:
    for stop_name in unique_stop_names:
        # Filter the DataFrame based on the given conditions
#         filtered_df = detail_df.query(
#             f'LineName == "{line_name}" and '
#             f'ETC_STOP_NAME.str.lower().str.contains("{stop_name.lower()}") and '
#             f'ETC_ROUTE_ID.str.split("_").str[-1] != "01"',
#             engine='python'
#         )
        filtered_df = detail_df.query(
            f'LineName == "{line_name}" and '
            f'ETC_STOP_NAME.str.lower().str.contains("{stop_name.lower()}")',
            engine='python'
        )
# If the combination is found, add the relevant data to the results
        if not filtered_df.empty:
            for _, row in filtered_df.iterrows():
                results.append({
                    'STOP_NAME': stop_name,
                    'STOP_ID': row['seq_fixed'],
                    'ETC_STOP_NAME': row['ETC_STOP_NAME'],
                    'note': '',  # Empty column for 'note'
                    'ETC_STOP_ID': row['ETC_STOP_ID'],
                    'ETC_ROUTE_ID': row['ETC_ROUTE_ID'],
                    'ETC_ROUTE_NAME': row['ETC_ROUTE_NAME']
                })

In [38]:
results_df = pd.DataFrame(results)

In [40]:
# results_df.to_csv('O2O_STOPS_VTA_02.csv',index=False)