In [1]:
import pandas as pd
import numpy as np

import warnings 

warnings.filterwarnings('ignore')

In [2]:
reviewer_df=pd.read_excel('reviewtool_20240828_DENVER_reviewerstats.xlsx',sheet_name='Reviewer Information')
df=pd.read_csv('reviewtool_20240828_DENVER_combinedflags.csv')

In [3]:
reviewer_df

,Reviewer,Total Reviewed,Percentage Reviewed (%),Total Removed,Removal Rate (%)
0,Kesar,150,15.0,1,0.666667
1,T A Divya,109,10.9,9,8.256881
2,Saurav,101,10.1,3,2.970297
3,Kashish,200,20.0,17,8.500000
4,Priyanka,141,14.1,12,8.510638
5,Divya sravani,99,9.9,9,9.090909
6,muskan,100,10.0,14,14.000000
7,Sneh,100,10.0,6,6.000000

In [4]:
reviewer_df.columns

Index(['Reviewer', 'Total Reviewed', 'Percentage Reviewed (%)',
       'Total Removed', 'Removal Rate (%)'],
      dtype='object')

In [22]:
high_removal_df=reviewer_df[reviewer_df['Removal Rate (%)']>=10]
high_removal_df

,Reviewer,Total Reviewed,Percentage Reviewed (%),Total Removed,Removal Rate (%)
6,muskan,100,10.0,14,14.0

In [6]:
df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO,2X_REVIEW_CHECK
0,2024-08-23,11423,Test,Test/No 5 MIN,Remove,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2024-08-23,11424,Test,Test/No 5 MIN,Remove,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2024-08-23,11425,Test,Test/No 5 MIN,Remove,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2024-08-23,11427,Test,Test/No 5 MIN,Remove,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2024-08-23,11634,HereAPI,Kesar,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [7]:
df.columns

Index(['Elvis_Date', 'elvis_id', '1st Cleaner', 'FINAL_REVIEWER',
       'Final_Usage', 'REASON FOR REMOVAL', 'REASON FOR REMOVAL [Other]',
       'route_match_flag', 'distance_flag', 'SUPERVISOR_COMMENT', 'id',
       'Completed', 'INTERV_INIT', 'ROUTE_SURVEYEDCode', 'ROUTE_SURVEYED',
       'HAVE_5_MIN_FOR_SURVECode', 'HAVE_5_MIN_FOR_SURVE', 'ORIGIN_PLACE_TYPE',
       'ORIGIN_TRANSPORTCode', 'ORIGIN_TRANSPORT', 'DESTIN_PLACE_TYPE',
       'DESTIN_TRANSPORTCode', 'DESTIN_TRANSPORT', '_INTRV_NOTE',
       'ELVIS_STATUS', 'ELVIS_COMMENT', 'ROUTE_STATUS', 'Stops_Status',
       'Test_Status', 'Traditional_Check', 'OD_Distance_Check',
       'Transfer_Distance_Check', '2x_REVIEWED_BY', '2x_REVIEWED_FLAG',
       'ADMIN_APPROVED', 'SURVEY_RECOVERY', 'SURVEY_RECOVERY_REVIEWED_BY',
       'Recovery Check', '2x_REVIEWED_BY.1', '2x_REVIEWED_FLAG.1',
       'ADMIN_APPROVED.1', 'RECORD_INFO', '2X_REVIEW_CHECK'],
      dtype='object')

In [8]:
new_df=pd.DataFrame()

In [24]:

reviewers_list =high_removal_df['Reviewer'].unique()
reviewers_list

array(['muskan'], dtype=object)

In [26]:
new_df=df[(df['FINAL_REVIEWER'].isin(reviewers_list))&(df['Final_Usage']=='Remove')]

In [27]:
new_df.to_csv('Reviewer_High_Percentage_Removals.csv',index=False)