In [1]:
import pandas as pd
import numpy as np

import warnings

warnings.filterwarnings('ignore')

In [2]:
kingelvis_files=['EMBARK_OK_KINGElvis','SEATTLE_WA_KINGElvis','BART_CA_KINGElvis','PALMTRAN_FL_KINGElvis','MUNI_CA_KINGElvis']

In [3]:
latest_combined_flags=['reviewtool_20240722_SEATTLE_combinedflags']

In [4]:
df=pd.read_excel('SEATTLE_WA_KINGElvis.xlsx',sheet_name='Elvis_Review')
comb_df=pd.read_csv('reviewtool_20240722_SEATTLE_combinedflags.csv')

df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,FINAL_REVIEWER2,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO
0,2024-05-03 00:00:00,NaN,No 5 MIN,muskan,NaN,NaN,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-05-03 00:00:00,5624.0,Test,muskan,NaN,NaN,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,2024-05-03 00:00:00,5625.0,Test,muskan,NaN,remove,D not given,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,2024-05-03 00:00:00,5628.0,Test,muskan,NaN,use,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,2024-05-03 00:00:00,5630.0,HereAPI,Utkarsh,NaN,Use,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [5]:
df.columns

Index(['Elvis_Date', 'elvis_id', '1st Cleaner', 'FINAL_REVIEWER',
       'FINAL_REVIEWER2', 'Final_Usage', 'REASON FOR REMOVAL',
       'REASON FOR REMOVAL [Other]', 'route_match_flag', 'distance_flag',
       'SUPERVISOR_COMMENT', 'id', 'Completed', 'INTERV_INIT',
       'ROUTE_SURVEYEDCode', 'ROUTE_SURVEYED', 'HAVE_5_MIN_FOR_SURVECode',
       'HAVE_5_MIN_FOR_SURVE', 'ORIGIN_PLACE_TYPE', 'ORIGIN_TRANSPORTCode',
       'ORIGIN_TRANSPORT', 'DESTIN_PLACE_TYPE', 'DESTIN_TRANSPORTCode',
       'DESTIN_TRANSPORT', '_INTRV_NOTE', 'ELVIS_STATUS', 'ELVIS_COMMENT',
       'ROUTE_STATUS', 'Stops_Status', 'Test_Status', 'Traditional_Check',
       'OD_Distance_Check', 'Transfer_Distance_Check', '2X_REVIEW_CHECK',
       '2X_REVIEW_CHECK.1', '2x_REVIEWED_BY', '2x_REVIEWED_FLAG',
       'ADMIN_APPROVED', 'SURVEY_RECOVERY', 'SURVEY_RECOVERY_REVIEWED_BY',
       'Recovery Check', '2x_REVIEWED_BY.1', '2x_REVIEWED_FLAG.1',
       'ADMIN_APPROVED.1', 'RECORD_INFO'],
      dtype='object')

In [6]:
comb_df.columns

Index(['Elvis_Date', 'elvis_id', '1st Cleaner', 'FINAL_REVIEWER',
       'FINAL_REVIEWER2', 'Final_Usage', 'REASON FOR REMOVAL',
       'REASON FOR REMOVAL [Other]', 'route_match_flag', 'distance_flag',
       'SUPERVISOR_COMMENT', 'id', 'Completed', 'INTERV_INIT',
       'ROUTE_SURVEYEDCode', 'ROUTE_SURVEYED', 'HAVE_5_MIN_FOR_SURVECode',
       'HAVE_5_MIN_FOR_SURVE', 'ORIGIN_PLACE_TYPE', 'ORIGIN_TRANSPORTCode',
       'ORIGIN_TRANSPORT', 'DESTIN_PLACE_TYPE', 'DESTIN_TRANSPORTCode',
       'DESTIN_TRANSPORT', '_INTRV_NOTE', 'ELVIS_STATUS', 'ELVIS_COMMENT',
       'ROUTE_STATUS', 'Stops_Status', 'Test_Status', 'Traditional_Check',
       'OD_Distance_Check', 'Transfer_Distance_Check', '2x_REVIEWED_BY',
       '2x_REVIEWED_FLAG', 'ADMIN_APPROVED', 'SURVEY_RECOVERY',
       'SURVEY_RECOVERY_REVIEWED_BY', 'Recovery Check', '2x_REVIEWED_BY.1',
       '2x_REVIEWED_FLAG.1', 'ADMIN_APPROVED.1', 'RECORD_INFO',
       '2X_REVIEW_CHECK'],
      dtype='object')

In [7]:
comb_df.rename(columns={'2X_REVIEW_CHECK':"2X_REVIEW_RECHECK"},inplace=True)

In [8]:
new_df=pd.merge(df,comb_df[['elvis_id','2X_REVIEW_RECHECK']],on='elvis_id',how='left')

In [9]:
total_records=new_df.shape[0]
total_records

30348

In [10]:
flag_condition=df['2X_REVIEW_CHECK']==1
total_flags=df[flag_condition].shape[0]
total_flags

1970

In [11]:
recheck_flag_condition=new_df['2X_REVIEW_RECHECK']==1
total_recheck_flags=df[recheck_flag_condition].shape[0]
total_recheck_flags

615

In [12]:
total_records=df.shape[0]
total_records

30348

In [13]:
flag_condition=df['2X_REVIEW_CHECK']==1

In [14]:
total_flags=df[flag_condition].shape[0]
total_flags

1970

In [15]:
record_condition=df['1st Cleaner'].str.lower()=='hereapi'

In [16]:
actual_records=df[record_condition].shape[0]
actual_records

22606

In [17]:
test_records=df[~record_condition].shape[0]
test_records

7742

In [18]:
pd.DataFrame({
    'Total_Survey_Records': [total_records],
    'Actual_Records': [actual_records],
    'Test_Records': [test_records],
    'Total_Flags': [total_flags],
    'Total_Recheck_Flags': [total_recheck_flags]
})

,Total_Survey_Records,Actual_Records,Test_Records,Total_Flags,Total_Recheck_Flags
0,30348,22606,7742,1970,615

In [19]:
with pd.ExcelWriter('Overall_Review_Flag_Report_02.xlsx') as writer:
    for file in kingelvis_files:
        project = file.split('_')[0]
        df = pd.read_excel(f"{file}.xlsx", sheet_name='Elvis_Review')

        total_recheck_flags = 0  # Initialize to 0 before checking

        for idx, flag in enumerate(latest_combined_flags):
            if project.lower() in flag.lower():
                print(f"Yes, {project} is present at index {idx}")
                comb_df = pd.read_csv(f'{latest_combined_flags[idx]}.csv')
                comb_df.rename(columns={'2X_REVIEW_CHECK': "2X_REVIEW_RECHECK"}, inplace=True)
                df = pd.merge(df, comb_df[['elvis_id', '2X_REVIEW_RECHECK']], on='elvis_id', how='left')
                recheck_flag_condition = df['2X_REVIEW_RECHECK'] == 1
                total_recheck_flags = df[recheck_flag_condition].shape[0]
                break  # Exit the loop after finding the first match

        total_records = df.shape[0]
        flag_condition = df['2X_REVIEW_CHECK'] == 1
        total_flags = df[flag_condition].shape[0]
        record_condition = df['1st Cleaner'].str.lower() == 'hereapi'
        actual_records = df[record_condition].shape[0]
        test_records = df[~record_condition].shape[0]

        new_df = pd.DataFrame({
            'Total_Survey_Records': [total_records],
            'Actual_Records': [actual_records],
            'Test_Records': [test_records],
            'Total_Flags': [total_flags],
            'Total_Recheck_Flags': [total_recheck_flags]
        })

        new_df.to_excel(writer, sheet_name=f'{project}_Report', index=False)

Yes, SEATTLE is present at index 0

In [20]:
# with pd.ExcelWriter('Overall_Review_Flag_Report.xlsx') as writer:
#     for file in kingelvis_files:
#         project = file.split('_')[0]
#         df = pd.read_excel(f"{file}.xlsx", sheet_name='Elvis_Review')
#         total_records = df.shape[0]
#         flag_condition = df['2X_REVIEW_CHECK'] == 1
#         total_flags = df[flag_condition].shape[0]
#         record_condition = df['1st Cleaner'].str.lower() == 'hereapi'
#         actual_records = df[record_condition].shape[0]
#         test_records = df[~record_condition].shape[0]
#         new_df = pd.DataFrame({
#             'Total_Survey_Records': [total_records],
#             'Actual_Records': [actual_records],
#             'Test_Records': [test_records],
#             'Total_Flags': [total_flags]
#         })
#         new_df.to_excel(writer, sheet_name=f'{project}_Report', index=False)

In [21]:
actual_records=df[record_condition]

In [22]:
actual_records.head()

,elvis_date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,FINAL_REVIEWER2,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO
45,2024-03-01 00:00:00,6015.0,HereAPI,Sameera,Use,NaN,NaN,NaN,Elvis_Review,Elvis_Review,...,Saurav,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
49,2024-03-01 00:00:00,6069.0,HereAPI,Sameera,Use,NaN,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
50,2024-03-01 00:00:00,6071.0,HereAPI,Sameera,Use,NaN,NaN,NaN,Elvis_Review,Elvis_Review,...,Saurav,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
52,2024-03-01 00:00:00,6073.0,HereAPI,Sameera,Use,NaN,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
53,2024-03-01 00:00:00,6074.0,HereAPI,Sameera,Use,NaN,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [23]:
unique_reviewers=actual_records['FINAL_REVIEWER'].str.lower().unique()

In [24]:
unique_reviewers

array(['sameera', 'kirubakaran', 'divya sravani', 'trusha', 'gowtham',
       'priyanka', 'raja', 'saurav', 'utkarsh', 'srisamhita', 'kesar',
       'muskan', 't a divya', 'sneh', 'kashish', 'sakshi', 'vidhi',
       'kashish ', 'kishor', 'kalpesh', 'jhalak', 'himanshu', 'vaishnavi',
       'priya', 'bhumika', 'sahil', 'sachin', 'rutwa', 'kiran', 'niti',
       'akshay', 'karthik', 'devanshi', 'kristyn', 'smith', 'harsh',
       'ankush', 'bhavesh'], dtype=object)

In [25]:
for reviewer in unique_reviewers:
    print(reviewer,actual_records[actual_records['FINAL_REVIEWER'].str.lower()==reviewer].shape[0],actual_records[(actual_records['FINAL_REVIEWER'].str.lower()==reviewer)&(actual_records['2X_REVIEW_CHECK']==1)].shape[0])

sameera 1105 115
kirubakaran 1358 144
divya sravani 777 75
trusha 403 38
gowtham 1178 98
priyanka 902 88
raja 1138 116
saurav 831 94
utkarsh 730 74
srisamhita 438 50
kesar 805 73
muskan 921 60
t a divya 525 41
sneh 838 66
kashish 1119 79
sakshi 452 40
vidhi 800 44
kashish  200 25
kishor 1000 85
kalpesh 1400 100
jhalak 600 48
himanshu 335 40
vaishnavi 1111 65
priya 903 42
bhumika 1098 79
sahil 709 65
sachin 279 25
rutwa 200 11
kiran 658 60
niti 550 39
akshay 600 54
karthik 910 83
devanshi 400 29
kristyn 1 0
smith 400 31
harsh 200 17
ankush 100 0
bhavesh 200 13

In [26]:
# with pd.ExcelWriter('Reviewer_Review_Flag_Report.xlsx') as writer:
#     for file in kingelvis_files:
#         project = file.split('_')[0]
#         df = pd.read_excel(f"{file}.xlsx", sheet_name='Elvis_Review')
        
#         # Filter the actual records
#         actual_records = df[df['1st Cleaner'].str.lower() == 'hereapi']
        
#         # Get the unique reviewers
#         unique_reviewers = actual_records['FINAL_REVIEWER'].str.lower().unique()
        
#         recheck_flagged_count=0
        
#         # Initialize a list to hold the data
#         data = []

#         for reviewer in unique_reviewers:
#             reviewed_count = actual_records[actual_records['FINAL_REVIEWER'].str.lower() == reviewer].shape[0]
#             flagged_count = actual_records[(actual_records['FINAL_REVIEWER'].str.lower() == reviewer) & (actual_records['2X_REVIEW_CHECK'] == 1)].shape[0]
            
#             # Append the data to the list
#             data.append({
#                 'Reviewer Name': reviewer,
#                 'Records_Reviewed': reviewed_count,
#                 'Flag_Records': flagged_count,
#             })
        
#         # Create a DataFrame from the list
#         new_df = pd.DataFrame(data)
        
#         # Write the DataFrame to the Excel file
#         new_df.to_excel(writer, sheet_name=f'{project}_Reviewer_Report', index=False)

In [27]:
with pd.ExcelWriter('Reviewer_Review_Flag_Report_02.xlsx') as writer:
    for file in kingelvis_files:
        project = file.split('_')[0]
        df = pd.read_excel(f"{file}.xlsx", sheet_name='Elvis_Review')
        
        # Filter the actual records
        actual_records = df[df['1st Cleaner'].str.lower() == 'hereapi']
        
        # Get the unique reviewers
        unique_reviewers = actual_records['FINAL_REVIEWER'].str.lower().unique()
        
        # Initialize a list to hold the data
        data = []

        # Initialize total_recheck_flags to 0
        total_recheck_flags = 0
        
        for idx, flag in enumerate(latest_combined_flags):
            if project.lower() in flag.lower():
                print(f"Yes, {project} is present at index {idx}")
                comb_df = pd.read_csv(f'{latest_combined_flags[idx]}.csv')
                comb_df.rename(columns={'2X_REVIEW_CHECK': "2X_REVIEW_RECHECK"}, inplace=True)
                actual_records = pd.merge(actual_records, comb_df[['elvis_id', '2X_REVIEW_RECHECK']], on='elvis_id', how='left')
                break  # Exit the loop after finding the first match

        for reviewer in unique_reviewers:
            reviewed_count = actual_records[actual_records['FINAL_REVIEWER'].str.lower() == reviewer].shape[0]
            flagged_count = actual_records[(actual_records['FINAL_REVIEWER'].str.lower() == reviewer) & (actual_records['2X_REVIEW_CHECK'] == 1)].shape[0]
            
            if '2X_REVIEW_RECHECK' in actual_records.columns:
                recheck_flagged_count = actual_records[(actual_records['FINAL_REVIEWER'].str.lower() == reviewer) & (actual_records['2X_REVIEW_RECHECK'] == 1)].shape[0]
            else:
                recheck_flagged_count = 0

            # Append the data to the list
            data.append({
                'Reviewer Name': reviewer,
                'Records_Reviewed': reviewed_count,
                'Flag_Records': flagged_count,
                'Recheck_Flag_Records': recheck_flagged_count
            })
        
        # Create a DataFrame from the list
        new_df = pd.DataFrame(data)
        
        # Write the DataFrame to the Excel file
        new_df.to_excel(writer, sheet_name=f'{project}_Reviewer_Report', index=False)

Yes, SEATTLE is present at index 0