In [1]:
import pandas as pd
import numpy as np
import random
import copy
import math
from datetime import date
from datetime import datetime
import warnings

warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv("elvissalemor2024obweekday_export_odbc(new_generation).csv")
comp_df=pd.read_excel("reviewtool_20240527_SALEM_RouteLevelComparison(Wkday & WkEnd).xlsx",sheet_name='Reverse Routes WkDAY')

In [4]:
df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ELVIS_USER_CHANGE_7_C_REASON,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,EXP_HOMELESSCode,EXP_HOMELESS,_REVERSE_TRIP,GENERATABLE_TRIPS
0,11421,2024-03-05 21:31:35,80,en,2024-03-05 21:30:57,2024-03-05 21:31:35,70.190.112.58,https://salem-or.etc-research.com/index.php/ad...,-28800,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11424,2024-03-05 21:35:24,80,en,2024-03-05 21:32:34,2024-03-05 21:35:24,70.190.112.58,https://salem-or.etc-research.com/index.php/ad...,-28800,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11441,2024-03-06 11:05:25,80,en,2024-03-06 11:05:01,2024-03-06 11:05:25,50.202.171.186,https://salem-or.etc-research.com/,-28800,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11473,2024-03-25 07:41:11,80,en,2024-03-25 07:05:51,2024-03-25 07:41:11,204.98.75.74,https://salem-or.etc-research.com/,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11476,2024-03-25 09:41:55,80,en,2024-03-25 08:54:10,2024-03-25 09:41:55,174.247.177.10,https://salem-or.etc-research.com/,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
comp_df.head()

,id,ROUTE_SURVEYEDCode,ROUTE_SURVEYED,Type,COMPLETED By
0,11598,SAL_2_11,11 Lancaster / Verda - South Lancaster,Reverse,NaN
1,11600,SAL_2_11,11 Lancaster / Verda - Keizer Transit Center,Reverse,NaN
2,11601,SAL_2_11,11 Lancaster / Verda - South Lancaster,Reverse,NaN
3,11623,SAL_2_11,11 Lancaster / Verda - Keizer Transit Center,Reverse,NaN
4,11626,SAL_2_11,11 Lancaster / Verda - Keizer Transit Center,Reverse,NaN

In [7]:

def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [8]:
generateable_column_check=['generatabletrips']
generateable_column=check_all_characters_present(df,generateable_column_check)
generateable_column

['GENERATABLE_TRIPS']

In [21]:
counter=0
for _,row in comp_df.iterrows():
    
    value=df[df['id']==row['id']][generateable_column[0]].values
    if pd.isna(value[0]):
        print(True)
    else:
        print(value[0],False)
    counter+=1
    if counter==50:
        break

Reverse False
Reverse False
Reverse False
Reverse False
True
True
Reverse False
Reverse False
Reverse False
Reverse False
True
True
True
True
True
Reverse False
True
True
True
True
True
True
True
True
True
Reverse False
Reverse False
True
True
Reverse False
Reverse False
True
True
Reverse False
Reverse,p1,Rev-p1 False
Reverse,p1,Rev-p1 False
True
True
True
True
True
Reverse,n1,Rev-n1 False
Reverse False
Reverse False
True
True
Reverse False
True
True
Reverse,p1,Rev-p1 False

In [ ]:
# KINGElvis FileName
file_name="SALEMOR_KINGElvis (6).xlsx"

if file_name.split('_')[0].isdigit():
    file_first_name=file_name.split('_')[0]+'_'+file_name.split('_')[1]
else:
    file_first_name=file_name.split('_')[0]
# for generated file version
version=2
project_name='SALEM'
today_date = date.today()
today_date=''.join(str(today_date).split('-'))

ke_df=pd.read_excel(file_name,sheet_name='Elvis_Review')

wkend_overall_df=pd.read_excel('SALEMOR_CR.xlsx',sheet_name='WkEND-Overall')
wkend_route_df=pd.read_excel('SALEMOR_CR.xlsx',sheet_name='WkEND-RouteTotal')

df=pd.read_csv("elvissalemor2024obweekday_export_odbc(new_generation).csv")
df['ROUTE_SURVEYEDCode_Splited']=df['ROUTE_SURVEYEDCode'].apply(lambda x:('_').join(x.split('_')[:-1]) )

wkday_overall_df=pd.read_excel('SALEMOR_CR.xlsx',sheet_name='WkDAY-Overall')
wkday_route_df=pd.read_excel('SALEMOR_CR.xlsx',sheet_name='WkDAY-RouteTotal')

ke_df=ke_df[ke_df['INTERV_INIT']!='999']
ke_df=ke_df[ke_df['INTERV_INIT']!=999]
ke_df=ke_df[ke_df['1st Cleaner']!='Test/No 5 MIN']
ke_df=ke_df[ke_df['Final_Usage'].str.lower()=='use']

In [ ]:
# Getting Data from Database where the Final Usage is Use in KINGELVIS  
df=pd.merge(df,ke_df['id'],on='id',how='inner')
df.drop_duplicates(subset='id',inplace=True)

In [ ]:

def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

date_columns_check=['completed','datestarted']
date_columns=check_all_characters_present(df,date_columns_check)

def determine_date(row):
    if not pd.isnull(row[date_columns[0]]):
        return row[date_columns[0]]
    elif not pd.isnull(row[date_columns[1]]):
        return row[date_columns[1]]
    else:
        return pd.NaT

df['Date'] = df.apply(determine_date, axis=1)

def get_day_name(x):
    date_object = datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
    day_name = date_object.strftime('%A')
    return day_name

df['Day']=df['Date'].apply(get_day_name)

weekend_df=df[df['Day'].isin(['Saturday','Sunday'])]

weekday_df=df[~(df['Day'].isin(['Saturday','Sunday']))]
# df.to_csv('Day Time SantaClarita.csv',index=False)

# exit()
#to get the TIMEON column
time_column_check=['timeoncode']
time_column=check_all_characters_present(df,time_column_check)

# to get ROUTE_SURVEYEDCode column from database File
route_survey_column_check=['routesurveyedcode']
route_survey_column=check_all_characters_present(df,route_survey_column_check)


#values to compare AM, MIDDAY, PM and Evening values
am_values=['AM1','AM2','AM3','MID1','MID2']
# am_values=[1,2,3,4,5]
midday_values=['MID3','MID4','MID5','MID6','MID7','PM1']
# midday_values=[6,7,8,9,10,11]
pm_values=['PM2','PM3','PM4','PM5']
# pm_values=[12,13,14]
evening_values=['PM6','PM7','PM8','PM9']
# evening_values=[15,16,17,18]

wkend_overall_df.dropna(subset=['LS_NAME_CODE'],inplace=True)
wkday_overall_df.dropna(subset=['LS_NAME_CODE'],inplace=True)

In [ ]:

def create_route_level_df(overall_df,route_df,df):
    am_values=['AM1','AM2','AM3','MID1','MID2']
    # am_values=[1,2,3,4,5]
    midday_values=['MID3','MID4','MID5','MID6','MID7','PM1']
    # midday_values=[6,7,8,9,10,11]
    pm_values=['PM2','PM3','PM4','PM5']
    # pm_values=[12,13,14]
    evening_values=['PM6','PM7','PM8','PM9']
    # evening_values=[15,16,17,18]
    # am_column_check=['ampeak']
    # pm_column_check=['pmpeak']
    # midday_column_check=['midday']
    # evening_column_check=['evening']
    # overall_goal_column_check=['totalsurveys']

    # am_column_check=['am']
    # pm_column_check=['pm']
    # midday_column_check=['midday']
    # evening_column_check=['eve']

    # am_column=check_all_characters_present(overall_df,am_column_check)
    # pm_column=check_all_characters_present(overall_df,pm_column_check)
    # midday_colum=check_all_characters_present(overall_df,midday_column_check)
    # evening_column=check_all_characters_present(overall_df,evening_column_check)
    # overall_goal_column=check_all_characters_present(cr_df,overall_goal_column_check)

    # pre_early_am_column=[0]  #0 is for Pre-Early AM header
    early_am_column=[1]  #1 is for Early AM header
    # am_column=[2] #2 is for AM header
    am_column=[2] #This is for AM header
    midday_colum=[3] #this is for MIDDAY header
    pm_column=[4] #this is for PM header
    evening_column=[5] #this is for EVENING header

    def convert_string_to_integer(x):
        try:
            return float(x)
        except (ValueError, TypeError):
            return 0

    # Creating new dataframe for specifically AM, PM, MIDDAY, Evenving data and added values from Compeletion Report
    new_df=pd.DataFrame()
    new_df['ROUTE_SURVEYEDCode']=overall_df['LS_NAME_CODE']
    new_df['CR_EARLY_AM']=overall_df[early_am_column[0]]
    new_df['CR_AM_Peak']=overall_df[am_column[0]]
    new_df['CR_Midday']=overall_df[midday_colum[0]]
    new_df['CR_PM_Peak']=overall_df[pm_column[0]]
    new_df['CR_Evening']=overall_df[evening_column[0]]
    new_df

    new_df[['CR_EARLY_AM','CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']]=new_df[['CR_EARLY_AM','CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']].applymap(convert_string_to_integer)
 
    # new_df['Overall Goal']=cr_df[overall_goal_column[0]]
    new_df.fillna(0,inplace=True)
    new_df.head()
    exit()
    # adding values for AM, PM, MIDDAY and Evening from Database file to new Dataframe
    for index, row in new_df.iterrows():
        route_code = row['ROUTE_SURVEYEDCode']

        # Define a function to get the counts and IDs
        def get_counts_and_ids(time_values):
            # Just for SALEM
            subset_df = df[(df['ROUTE_SURVEYEDCode_Splited'] == route_code) & (df[time_column[0]].isin(time_values))]
            # subset_df = df[(df['ROUTE_SURVEYEDCode'] == route_code) & (df[time_column[0]].isin(time_values))]
            count = subset_df.shape[0]
            ids = subset_df['id'].values
            return count, ids
        
        # Calculate counts and IDs for each time slot
        am_value, am_value_ids = get_counts_and_ids(am_values)
        midday_value, midday_value_ids = get_counts_and_ids(midday_values)
        pm_value, pm_value_ids = get_counts_and_ids(pm_values)
        evening_value, evening_value_ids = get_counts_and_ids(evening_values)
        
        # Assign values to new_df
        new_df.loc[index, 'CR_Total'] =row['CR_EARLY_AM']+ row['CR_AM_Peak'] + row['CR_Midday'] + row['CR_PM_Peak'] + row['CR_Evening']
        new_df.loc[index, 'CR_AM_Peak'] =row['CR_EARLY_AM']+ row['CR_AM_Peak']
        new_df.loc[index, 'DB_AM_Peak'] = am_value
        new_df.loc[index, 'DB_Midday'] = midday_value
        new_df.loc[index, 'DB_PM_Peak'] = pm_value
        new_df.loc[index, 'DB_Evening'] = evening_value
        new_df.loc[index, 'DB_Total'] = evening_value + am_value + midday_value + pm_value
        
        # Join the IDs as a comma-separated string
        new_df.loc[index, 'DB_AM_IDS'] = ', '.join(map(str, am_value_ids))
        new_df.loc[index, 'DB_Midday_IDS'] = ', '.join(map(str, midday_value_ids))
        new_df.loc[index, 'DB_PM_IDS'] = ', '.join(map(str, pm_value_ids))
        new_df.loc[index, 'DB_Evening_IDS'] = ', '.join(map(str, evening_value_ids))

    # new_df.to_csv('Time Base Comparison(Over All).csv',index=False)

    # Route Level Comparison
    # Just for SALEM because in SALEM Code values are already splitted
    new_df['ROUTE_SURVEYEDCode_Splited']=new_df['ROUTE_SURVEYEDCode']
    # new_df['ROUTE_SURVEYEDCode_Splited']=new_df['ROUTE_SURVEYEDCode'].apply(lambda x:('_').join(x.split('_')[:-1]) )

    # creating new dataframe for ROUTE_LEVEL_Comparison
    route_level_df=pd.DataFrame()

    unique_routes=new_df['ROUTE_SURVEYEDCode_Splited'].unique()

    route_level_df['ROUTE_SURVEYEDCode']=unique_routes

    route_df.rename(columns={'ROUTE_TOTAL':'CR_Overall_Goal','SURVEY_ROUTE_CODE':'ROUTE_SURVEYEDCode','LS_NAME_CODE':'ROUTE_SURVEYEDCode'},inplace=True)

    route_df.dropna(subset=['ROUTE_SURVEYEDCode'],inplace=True)
    route_level_df=pd.merge(route_level_df,route_df[['ROUTE_SURVEYEDCode','CR_Overall_Goal']],on='ROUTE_SURVEYEDCode')

    # adding values from database file and compeletion report for Route_Level
    for index , row in route_level_df.iterrows():
        subset_df=new_df[new_df['ROUTE_SURVEYEDCode_Splited']==row['ROUTE_SURVEYEDCode']]
        # sum_per_route_cr = subset_df[['CR_AM_Peak', 'CR_Midday', 'CR_PM_Peak', 'CR_Evening','CR_Total','Overall Goal']].sum()
        sum_per_route_cr = subset_df[['CR_EARLY_AM','CR_AM_Peak', 'CR_Midday', 'CR_PM_Peak', 'CR_Evening','CR_Total']].sum()
        sum_per_route_db = subset_df[['DB_AM_Peak', 'DB_Midday', 'DB_PM_Peak', 'DB_Evening','DB_Total']].sum()
        
        # route_level_df.loc[index,'CR_Pre_Early_AM']=sum_per_route_cr['CR_Pre_Early_AM']
#         route_level_df.loc[index,'CR_Early_AM']=sum_per_route_cr['CR_Early_AM']
        route_level_df.loc[index,'CR_AM_Peak']=sum_per_route_cr['CR_AM_Peak']
        route_level_df.loc[index,'CR_Midday']=sum_per_route_cr['CR_Midday']
        route_level_df.loc[index,'CR_PM_Peak']=sum_per_route_cr['CR_PM_Peak']
        route_level_df.loc[index,'CR_Evening']=sum_per_route_cr['CR_Evening']
        route_level_df.loc[index,'CR_Total']=sum_per_route_cr['CR_Total']
        # route_level_df.loc[index,'CR_Overall_Goal']=sum_per_route_cr['Overall Goal']
        
        route_level_df.loc[index,'DB_AM_Peak']=sum_per_route_db['DB_AM_Peak']
        route_level_df.loc[index,'DB_Midday']=sum_per_route_db['DB_Midday']
        route_level_df.loc[index,'DB_PM_Peak']=sum_per_route_db['DB_PM_Peak']
        route_level_df.loc[index,'DB_Evening']=sum_per_route_db['DB_Evening']
        route_level_df.loc[index,'DB_Total']=sum_per_route_db['DB_Total']   
        route_level_df.loc[index,'DB_AM_IDS']=', '.join(str(value) for value in subset_df['DB_AM_IDS'].values)    
        route_level_df.loc[index,'DB_Midday_IDS']=', '.join(str(value) for value in subset_df['DB_Midday_IDS'].values)    
        route_level_df.loc[index,'DB_PM_IDS']=', '.join(str(value) for value in subset_df['DB_PM_IDS'].values)    
        route_level_df.loc[index,'DB_Evening_IDS']=', '.join(str(value) for value in subset_df['DB_Evening_IDS'].values)

    # route_level_df.to_csv('Route Level Comparison(Value_Check).csv',index=False)
        
    # calculating the difference between values of database and compeletion report for Route_Level
    for index, row in route_level_df.iterrows():
        am_peak_diff=row['CR_AM_Peak']-row['DB_AM_Peak']
        midday_diff=row['CR_Midday']-row['DB_Midday']    
        pm_peak_diff=row['CR_PM_Peak']-row['DB_PM_Peak']
        evening_diff=row['CR_Evening']-row['DB_Evening']
        total_diff=row['CR_Total']-row['DB_Total']
        overall_difference=row['CR_Overall_Goal']-row['DB_Total']
        route_level_df.loc[index, 'AM_DIFFERENCE'] = math.ceil(max(0, am_peak_diff))
        route_level_df.loc[index, 'Midday_DIFFERENCE'] = math.ceil(max(0, midday_diff))
        route_level_df.loc[index, 'PM_DIFFERENCE'] = math.ceil(max(0, pm_peak_diff))
        route_level_df.loc[index, 'Evening_DIFFERENCE'] = math.ceil(max(0, evening_diff))
        # route_level_df.loc[index, 'Total_DIFFERENCE'] = math.ceil(max(0, total_diff))
        route_level_df.loc[index, 'Total_DIFFERENCE'] =math.ceil(max(0, am_peak_diff))+math.ceil(max(0, midday_diff))+math.ceil(max(0, pm_peak_diff))+math.ceil(max(0, evening_diff))
        route_level_df.loc[index, 'Overall_Goal_DIFFERENCE'] = math.ceil(max(0,overall_difference))

    return route_level_df

In [ ]:

wkday_route_level =create_route_level_df(wkday_overall_df,wkday_route_df,weekday_df)

In [ ]:
wkday_route_level