In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [2]:
draft_df=pd.read_excel('od_20241203_buffalo_ny_draftfinal.xlsx')
draft_df.head()

,ID,DATE_COMPLETED,ROUTE_DIRECTION[Code],ROUTE_DIRECTION,ROUTE_DIRECTION [Other],HOME_ADDRESS [CITY],HOME_ADDRESS [STATE],HOME_ADDRESS [ZIP],HOME_ADDRESS [LAT],HOME_ADDRESS [LONG],...,INCOME[Code],INCOME,SURVEY_LANGUAGE[Code],SURVEY_LANGUAGE,SURVEY_LANGUAGE [Other],ROUTE_DIR_TIME_CODE,UNLINKED_WGHT_FCTR,SYSTEM_TRANSFERS,LINKED_MULTP,LINKED_WGHT_FCTR
0,9995941,2024-09-25,MET_1_METRORAIL_00,METRO RAIL (INBOUND),NaN,Buffalo,NY,14215,42.936756,-78.811341,...,7,"$50,000 - $74,999",ENGLISH,ENGLISH,NaN,NaN,NaN,NaN,NaN,NaN
1,9996008,2024-09-26,MET_1_METRORAIL_00,METRO RAIL (INBOUND),NaN,Buffalo,NY,14214,42.940033,-78.841486,...,4,"$15,000 - $24,999",ENGLISH,ENGLISH,NaN,NaN,NaN,NaN,NaN,NaN
2,9996057,2024-09-27,MET_1_METRORAIL_00,METRO RAIL (INBOUND),NaN,Buffalo,NY,14209,42.911516,-78.864405,...,5,"$25,000 - $34,999",ENGLISH,ENGLISH,NaN,NaN,NaN,NaN,NaN,NaN
3,9996349,2024-10-11,MET_1_METRORAIL_00,METRO RAIL (INBOUND),NaN,Buffalo,NY,14214,42.946979,-78.841364,...,9,"$100,000 or more",ENGLISH,ENGLISH,NaN,NaN,NaN,NaN,NaN,NaN
4,9996353,2024-10-11,MET_1_METRORAIL_00,METRO RAIL (INBOUND),NaN,Buffalo,NY,14207,42.950171,-78.882184,...,2,"$5,000 - $9,999",ENGLISH,ENGLISH,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df=pd.read_csv('ROUTE_DIRECTION_REFACTOR_ROUTE_SPECIFIC002.csv')
df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,STOP_ON_LAT_NEW,STOP_ON_LONG_NEW,STOP_OFF_ADDRESS_NEW,STOP_OFF_SEQ,STOP_OFF_CLINTID_NEW,STOP_OFF_LAT_NEW,STOP_OFF_LONG_NEW,ROUTE_SURVEYEDCode_New,ROUTE_SURVEYED_NEW,STOP_ON_ADDRESS_NEW
0,2024-09-25,5907,HereAPI,Priyanka,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,42.954526,-78.820463,Kenmore Avenue Elmwood Avenue West,20.0,NFT_1_5_00_26520,42.958650,-78.878917,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NaN
1,2024-09-25,5914,HereAPI,Priyanka,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,42.958727,-78.873164,Niagara Street Albany Street South,60.0,NFT_1_5_00_35530,42.913200,-78.899739,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NaN
2,2024-09-25,5917,HereAPI,Priyanka,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,42.951627,-78.825567,Main Street Robie Street South,21.0,NFT_1_8_00_31240,42.929717,-78.849574,NFT_1_8_00,8 - MAIN (Inbound),NaN
3,2024-09-25,5920,HereAPI,Priyanka,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,42.951627,-78.825567,Pearl Street Court Street South Far,46.0,NFT_1_8_00_42010,42.885851,-78.875607,NFT_1_8_00,8 - MAIN (Inbound),NaN
4,2024-09-25,5922,HereAPI,Priyanka,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,42.955496,-78.898445,Niagara Street West Delavan Avenue,55.0,NFT_1_5_00_35740,42.922333,-78.898397,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NaN

In [4]:
draft_df.columns

Index(['ID', 'DATE_COMPLETED', 'ROUTE_DIRECTION[Code]', 'ROUTE_DIRECTION',
       'ROUTE_DIRECTION [Other]', 'HOME_ADDRESS [CITY]',
       'HOME_ADDRESS [STATE]', 'HOME_ADDRESS [ZIP]', 'HOME_ADDRESS [LAT]',
       'HOME_ADDRESS [LONG]',
       ...
       'INCOME[Code]', 'INCOME', 'SURVEY_LANGUAGE[Code]', 'SURVEY_LANGUAGE',
       'SURVEY_LANGUAGE [Other]', 'ROUTE_DIR_TIME_CODE', 'UNLINKED_WGHT_FCTR',
       'SYSTEM_TRANSFERS', 'LINKED_MULTP', 'LINKED_WGHT_FCTR'],
      dtype='object', length=167)

In [5]:
df.columns

Index(['Elvis_Date', 'elvis_id', '1st Cleaner', 'FINAL_REVIEWER',
       'Final_Usage', 'REASON FOR REMOVAL', 'REASON FOR REMOVAL [Other]',
       'route_match_flag', 'distance_flag', 'SUPERVISOR_COMMENT', 'id',
       'Completed', 'INTERV_INIT', 'ROUTE_SURVEYEDCode_KE', 'ROUTE_SURVEYED',
       'HAVE_5_MIN_FOR_SURVECode', 'HAVE_5_MIN_FOR_SURVE', 'ORIGIN_PLACE_TYPE',
       'ORIGIN_TRANSPORTCode', 'ORIGIN_TRANSPORT', 'DESTIN_PLACE_TYPE',
       'DESTIN_TRANSPORTCode', 'DESTIN_TRANSPORT', '_INTRV_NOTE',
       'ELVIS_STATUS', 'ELVIS_COMMENT', 'ROUTE_STATUS', 'Stops_Status',
       'Test_Status', 'Traditional_Check', 'OD_Distance_Check',
       'Transfer_Distance_Check', '2X_REVIEW_CHECK', '2X_REVIEW_CHECK.1',
       '2x_REVIEWED_BY', '2x_REVIEWED_FLAG', 'ADMIN_APPROVED',
       'SURVEY_RECOVERY', 'SURVEY_RECOVERY_REVIEWED_BY', 'Recovery Check',
       '2x_REVIEWED_BY.1', '2x_REVIEWED_FLAG.1', 'ADMIN_APPROVED.1',
       'RECORD_INFO', 'ROUTE_SURVEYEDCode', 'STOP_OFF_ADDR', 'STOP_ON_ADDR',
       'STOP_OFF_CLNTID', 'STOP_ON_CLNTID', 'STOP_OFF_LAT', 'STOP_OFF_LONG',
       'STOP_ON_LAT', 'STOP_ON_LONG', 'STOP_ON_ADDR_NEW', 'STOP_ON_SEQ',
       'STOP_ON_CLINTID_NEW', 'STOP_ON_LAT_NEW', 'STOP_ON_LONG_NEW',
       'STOP_OFF_ADDRESS_NEW', 'STOP_OFF_SEQ', 'STOP_OFF_CLINTID_NEW',
       'STOP_OFF_LAT_NEW', 'STOP_OFF_LONG_NEW', 'ROUTE_SURVEYEDCode_New',
       'ROUTE_SURVEYED_NEW', 'STOP_ON_ADDRESS_NEW'],
      dtype='object')

In [6]:
df.rename(columns={'id':'ID'},inplace=True)

In [7]:
new_df=pd.merge(draft_df[['ID', 'ROUTE_DIRECTION[Code]', 'ROUTE_DIRECTION','STOP_OFF [CLNTID]','STOP_ON [CLNTID]']],df[['ID','STOP_OFF_CLNTID',
       'STOP_ON_CLNTID', 'STOP_ON_CLINTID_NEW',
       'STOP_OFF_CLINTID_NEW',
        'ROUTE_SURVEYEDCode_New',
       'ROUTE_SURVEYED_NEW']],on='ID')
# new_df=pd.merge(draft_df[['ID', 'ROUTE_DIRECTION[Code]', 'ROUTE_DIRECTION','STOP_OFF [ADDR]','STOP_OFF [CLNTID]']],df[['ID','ROUTE_SURVEYEDCode_New','ROUTE_SURVEYED_NEW','STOP_OFF_ADDR','STOP_OFF_CLNTID','STOP_OFF_CLNTID_new','STOP_OFF_ADDR_new']],on='ID')

In [8]:
new_df.sort_values(by='ID',ascending=True,inplace=True)

In [9]:
new_df.head()

,ID,ROUTE_DIRECTION[Code],ROUTE_DIRECTION,STOP_OFF [CLNTID],STOP_ON [CLNTID],STOP_OFF_CLNTID,STOP_ON_CLNTID,STOP_ON_CLINTID_NEW,STOP_OFF_CLINTID_NEW,ROUTE_SURVEYEDCode_New,ROUTE_SURVEYED_NEW
4487,5907,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NFT_1_5_00_26520,NFT_1_5_00_31360,NFT_1_5_00_26520,NFT_1_5_00_31360,NFT_1_5_00_31360,NFT_1_5_00_26520,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound)
4488,5914,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NFT_1_5_00_35530,NFT_1_5_00_26560,NFT_1_5_00_35530,NFT_1_5_00_26560,NFT_1_5_00_26560,NFT_1_5_00_35530,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound)
5269,5917,NFT_1_8_00,8 - MAIN (Inbound),NFT_1_8_00_31240,NFT_1_8_00_31670,NFT_1_8_00_31240,NFT_1_8_00_31670,NFT_1_8_00_31670,NFT_1_8_00_31240,NFT_1_8_00,8 - MAIN (Inbound)
5270,5920,NFT_1_8_00,8 - MAIN (Inbound),NFT_1_8_00_42010,NFT_1_8_00_31670,NFT_1_8_00_42010,NFT_1_8_00_31670,NFT_1_8_00_31670,NFT_1_8_00_42010,NFT_1_8_00,8 - MAIN (Inbound)
4493,5922,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NFT_1_5_00_35740,NFT_1_5_00_40040,NFT_1_5_00_35740,NFT_1_5_00_40040,NFT_1_5_00_40040,NFT_1_5_00_35740,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound)

In [10]:
new_df.columns

Index(['ID', 'ROUTE_DIRECTION[Code]', 'ROUTE_DIRECTION', 'STOP_OFF [CLNTID]',
       'STOP_ON [CLNTID]', 'STOP_OFF_CLNTID', 'STOP_ON_CLNTID',
       'STOP_ON_CLINTID_NEW', 'STOP_OFF_CLINTID_NEW', 'ROUTE_SURVEYEDCode_New',
       'ROUTE_SURVEYED_NEW'],
      dtype='object')

In [11]:
# Adding the 'Same Direction' column based on the condition
new_df['Same Direction'] = new_df['ROUTE_DIRECTION[Code]'] == new_df['ROUTE_SURVEYEDCode_New']

# Converting True/False to 'True'/'False' as strings if needed
new_df['Same Direction'] = new_df['Same Direction'].map({True: 'True', False: 'False'})

In [12]:
new_df.head()

,ID,ROUTE_DIRECTION[Code],ROUTE_DIRECTION,STOP_OFF [CLNTID],STOP_ON [CLNTID],STOP_OFF_CLNTID,STOP_ON_CLNTID,STOP_ON_CLINTID_NEW,STOP_OFF_CLINTID_NEW,ROUTE_SURVEYEDCode_New,ROUTE_SURVEYED_NEW,Same Direction
4487,5907,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NFT_1_5_00_26520,NFT_1_5_00_31360,NFT_1_5_00_26520,NFT_1_5_00_31360,NFT_1_5_00_31360,NFT_1_5_00_26520,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),True
4488,5914,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NFT_1_5_00_35530,NFT_1_5_00_26560,NFT_1_5_00_35530,NFT_1_5_00_26560,NFT_1_5_00_26560,NFT_1_5_00_35530,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),True
5269,5917,NFT_1_8_00,8 - MAIN (Inbound),NFT_1_8_00_31240,NFT_1_8_00_31670,NFT_1_8_00_31240,NFT_1_8_00_31670,NFT_1_8_00_31670,NFT_1_8_00_31240,NFT_1_8_00,8 - MAIN (Inbound),True
5270,5920,NFT_1_8_00,8 - MAIN (Inbound),NFT_1_8_00_42010,NFT_1_8_00_31670,NFT_1_8_00_42010,NFT_1_8_00_31670,NFT_1_8_00_31670,NFT_1_8_00_42010,NFT_1_8_00,8 - MAIN (Inbound),True
4493,5922,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),NFT_1_5_00_35740,NFT_1_5_00_40040,NFT_1_5_00_35740,NFT_1_5_00_40040,NFT_1_5_00_40040,NFT_1_5_00_35740,NFT_1_5_00,5 - NIAGARA-KENMORE (Inbound),True

In [13]:
new_df.to_csv('Route Direction Comparison_ROUTE_SPECIFIC002.csv',index=False)

In [14]:
print(new_df.columns)

Index(['ID', 'ROUTE_DIRECTION[Code]', 'ROUTE_DIRECTION', 'STOP_OFF [CLNTID]',
       'STOP_ON [CLNTID]', 'STOP_OFF_CLNTID', 'STOP_ON_CLNTID',
       'STOP_ON_CLINTID_NEW', 'STOP_OFF_CLINTID_NEW', 'ROUTE_SURVEYEDCode_New',
       'ROUTE_SURVEYED_NEW', 'Same Direction'],
      dtype='object')