In [1]:
import pandas as pd
import numpy as np
import random
import copy
import math
from datetime import date
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

In [2]:
file_name="SEATTLE_WA_KINGElvis.xlsx"

if file_name.split('_')[0].isdigit():
    file_first_name=file_name.split('_')[0]+'_'+file_name.split('_')[1]
else:
    file_first_name=file_name.split('_')[0]

# for generated file version
version=2
project_name='SEATTLE'
today_date = date.today()
today_date=''.join(str(today_date).split('-'))

ke_df=pd.read_excel(file_name,sheet_name='Elvis_Review')

In [3]:
wkend_overall_df=pd.read_excel('project_CR_SEATTLE.xlsx',sheet_name='WkEND-Overall')
wkend_route_df=pd.read_excel('project_CR_SEATTLE.xlsx',sheet_name='WkEND-RouteTotal')
df=pd.read_csv("elvisseattlewa2024obweekday_export_odbc.csv")
wkday_overall_df=pd.read_excel('project_CR_SEATTLE.xlsx',sheet_name='WkDAY-Overall')
wkday_route_df=pd.read_excel('project_CR_SEATTLE.xlsx',sheet_name='WkDAY-RouteTotal')

In [4]:
wkend_overall_df.head()

,DAY,SORT,LS_NAME_CODE,LS_NAME,Agency_CR,0,1,2,3,4,5,Direction Total,LS_ROUTELEVEL,Unnamed: 13
0,SATURDAY,1,SND_1_512_01,(Sound) 512 Everett - Northgate Station [NORTH...,ST CT Bus,NaN,NaN,4.9675,7.1925,NaN,NaN,NaN,35,SND_1_512
1,SATURDAY,2,SND_1_512_00,(Sound) 512 Everett - Northgate Station [SOUTH...,ST CT Bus,NaN,NaN,6.8775,4.155,NaN,NaN,NaN,0,SND_1_512
2,SATURDAY,3,SND_1_522_00,(Sound) 522 Woodinville - Seattle [EASTBOUND],ST CT Bus,NaN,NaN,3.9588,4.3525,NaN,NaN,NaN,25,SND_1_522
3,SATURDAY,4,SND_1_522_01,(Sound) 522 Woodinville - Seattle [WESTBOUND],ST CT Bus,NaN,NaN,4.8213,3.4875,NaN,NaN,NaN,0,SND_1_522
4,SATURDAY,5,SND_1_535_01,(Sound) 535 Lynnwood - Bellevue [NORTHBOUND],ST CT Bus,NaN,NaN,1.0525,1.355,NaN,NaN,NaN,7,SND_1_535

In [5]:
wkend_route_df.head()

,DAY,SORT,LS_NAME_CODE,LS_NAME,ROUTE_TOTAL
0,SATURDAY,1,SND_1_512,(Sound) 512 Everett - Northgate Station,35.0
1,SATURDAY,2,SND_1_522,(Sound) 522 Woodinville - Seattle,25.0
2,SATURDAY,3,SND_1_535,(Sound) 535 Lynnwood - Bellevue,7.0
3,SATURDAY,4,SND_1_542,(Sound) 542 Redmond - University District,7.0
4,SATURDAY,5,SND_1_545,(Sound) 545 Redmond - Seattle,19.0

In [6]:
df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,HOME_ADDRESS_ZIP,HOME_ADDRESS_7TOHIDE,HOME_ADDRESS_8TOHIDE,HOME_ADDRESS_LAT,HOME_ADDRESS_9TOHIDE,HOME_ADDRESS_10TOHIDE,HOME_ADDRESS_LONG,HOMEADD_TIME,_REVERSE_TRIP,GENERATABLE_TRIPS
0,5624,11/04/2024 06:19,66,en,11/04/2024 06:15,11/04/2024 06:19,70.113.126.123,https://seattle-od.etc-research.com/,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5625,11/04/2024 06:33,66,en,11/04/2024 06:19,11/04/2024 06:33,70.113.126.123,https://seattle-od.etc-research.com/index.php/...,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5628,11/04/2024 07:37,66,en,11/04/2024 07:28,11/04/2024 07:37,72.182.38.183,https://seattle-od.etc-research.com/,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5630,11/04/2024 09:40,66,en,11/04/2024 09:33,11/04/2024 09:40,172.56.104.199,https://seattle-od.etc-research.com/,-25200,BLN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5633,11/04/2024 09:43,66,en,11/04/2024 09:40,11/04/2024 09:43,172.56.104.199,https://seattle-od.etc-research.com/index.php/...,-25200,BLN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
wkday_overall_df.head()

,SORT,LS_NAME_CODE,LS_NAME,Agency_CR,0,1,2,3,4,5,Direction Total,LS_ROUTELEVEL
0,1,SND_1_510_01,(Sound) 510 Everett - Seattle [NORTHBOUND],ST CT Bus,0,0.0,2.0,17.0,1.0,0,20.0,91.0
1,2,SND_1_510_00,(Sound) 510 Everett - Seattle [SOUTHBOUND],ST CT Bus,0,35.0,0.0,0.0,0.0,0,35.0,NaN
2,3,SND_1_512_01,(Sound) 512 Everett - Northgate Station [NORTH...,ST CT Bus,0,15.0,44.0,24.0,22.0,0,105.0,356.0
3,4,SND_1_512_00,(Sound) 512 Everett - Northgate Station [SOUTH...,ST CT Bus,0,18.0,54.0,25.0,11.0,0,109.0,NaN
4,5,SND_1_513_01,(Sound) 513 Seaway Transit Ctr - Northgate Sta...,ST CT Bus,0,0.0,0.0,13.0,3.0,0,17.0,46.0

In [8]:
wkday_route_df.head()

,SORT,LS_NAME_CODE,LS_NAME,ROUTE_TOTAL
0,1,SND_1_510,(Sound) 510 Everett - Seattle,91.0
1,2,SND_1_512,(Sound) 512 Everett - Northgate Station,356.0
2,3,SND_1_513,(Sound) 513 Seaway Transit Ctr - Northgate Sta...,46.0
3,4,SND_1_522,(Sound) 522 Woodinville - Seattle,271.0
4,5,SND_1_532,(Sound) 532 Everett - Bellevue,81.0

In [9]:
df['ROUTE_SURVEYEDCode_Splited']=df['ROUTE_SURVEYEDCode'].apply(lambda x:('_').join(str(x).split('_')[:-1]) )

In [10]:
df[['ROUTE_SURVEYEDCode_Splited']].head()

  ROUTE_SURVEYEDCode_Splited
0                SND_1_1Line
1                SND_1_1Line
2                SND_1_1Line
3                SND_1_TLine
4                SND_1_TLine

In [11]:
ke_df=ke_df[ke_df['INTERV_INIT']!='999']
ke_df=ke_df[ke_df['INTERV_INIT']!=999]
ke_df=ke_df[ke_df['1st Cleaner']!='Test/No 5 MIN']
ke_df=ke_df[ke_df['Final_Usage'].str.lower()=='use']

In [12]:
ke_df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,FINAL_REVIEWER2,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO
4,2024-05-03 00:00:00,5630.0,HereAPI,Utkarsh,NaN,Use,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
5,2024-05-03 00:00:00,5633.0,HereAPI,Utkarsh,NaN,Use,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
6,2024-05-03 00:00:00,5634.0,HereAPI,Utkarsh,NaN,Use,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
7,2024-05-03 00:00:00,5638.0,HereAPI,Utkarsh,NaN,Use,NaN,NaN,Elvis_Review,Elvis_Review,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
8,2024-05-03 00:00:00,5639.0,HereAPI,Utkarsh,NaN,Use,NaN,NaN,Elvis_Review,Elvis_Review,...,Kashish,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [13]:
df=pd.merge(df,ke_df['id'],on='id',how='inner')
df.drop_duplicates(subset='id',inplace=True)

In [14]:
def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [15]:
date_columns_check=['completed','datestarted']
date_columns=check_all_characters_present(df,date_columns_check)
date_columns

['Completed', 'Date_started']

In [16]:
def determine_date(row):
    if not pd.isnull(row[date_columns[0]]):
        return row[date_columns[0]]
    elif not pd.isnull(row[date_columns[1]]):
        return row[date_columns[1]]
    else:
        return pd.NaT

In [17]:
df['Date'] = df.apply(determine_date, axis=1)

In [18]:
df[['Date']].head()

               Date
0  11/04/2024 09:40
1  11/04/2024 09:43
2  11/04/2024 10:17
3  11/04/2024 11:26
4  11/04/2024 11:32

In [19]:
def get_day_name(x):
    date_object = datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
    day_name = date_object.strftime('%A')
    return day_name

df['Day']=df['Date'].apply(get_day_name)

ValueError: time data '11/04/2024 09:40' does not match format '%Y-%m-%d %H:%M:%S'

In [ ]:
df[['Day']].tail()

In [ ]:
weekend_df=df[df['Day'].isin(['Saturday','Sunday'])]

weekday_df=df[~(df['Day'].isin(['Saturday','Sunday']))]

In [ ]:
weekday_df[['Day']].head()

In [ ]:
weekend_df[['Day']].head()

In [ ]:
time_column_check=['timeoncode']
time_column=check_all_characters_present(df,time_column_check)
time_column

In [ ]:
route_survey_column_check=['routesurveyedcode']
route_survey_column=check_all_characters_present(df,route_survey_column_check)

In [ ]:
wkend_overall_df.dropna(subset=['LS_NAME_CODE'],inplace=True)
wkday_overall_df.dropna(subset=['LS_NAME_CODE'],inplace=True)

In [ ]:
def create_route_level_df(overall_df,route_df,df):
    am_values=['AM1','AM2','AM3','AM4']
    midday_values=['AM5','AM6','AM7','MID1','MID2','MID3']
    pm_values=['PM1','PM2','PM3','PM4']
    evening_values=['PM5','PM6','PM7','PM8']
    # evening_values=['PM6','PM7','PM8','PM9']
    # evening_values=[15,16,17,18]
    # am_column_check=['ampeak']
    # pm_column_check=['pmpeak']
    # midday_column_check=['midday']
    # evening_column_check=['evening']
    # overall_goal_column_check=['totalsurveys']

    # am_column_check=['am']
    # pm_column_check=['pm']
    # midday_column_check=['midday']
    # evening_column_check=['eve']

    # am_column=check_all_characters_present(overall_df,am_column_check)
    # pm_column=check_all_characters_present(overall_df,pm_column_check)
    # midday_colum=check_all_characters_present(overall_df,midday_column_check)
    # evening_column=check_all_characters_present(overall_df,evening_column_check)
    # overall_goal_column=check_all_characters_present(cr_df,overall_goal_column_check)

    # pre_early_am_column=[0]  #0 is for Pre-Early AM header
    early_am_column=[0]  #1 is for Early AM header
    # am_column=[2] #2 is for AM header
    am_column=[1] #This is for AM header
    midday_colum=[2] #this is for MIDDAY header
    pm_column=[3] #this is for PM header
    evening_column=[4] #this is for EVENING header

    def convert_string_to_integer(x):
        try:
            return float(x)
        except (ValueError, TypeError):
            return 0

    # Creating new dataframe for specifically AM, PM, MIDDAY, Evenving data and added values from Compeletion Report
    new_df=pd.DataFrame()
    new_df['ROUTE_SURVEYEDCode']=overall_df['LS_NAME_CODE']
    new_df['CR_EARLY_AM']=overall_df[early_am_column[0]]
    new_df['CR_AM_Peak']=overall_df[am_column[0]]
    new_df['CR_Midday']=overall_df[midday_colum[0]]
    new_df['CR_PM_Peak']=overall_df[pm_column[0]]
    new_df['CR_Evening']=overall_df[evening_column[0]]
    new_df.to_csv("NEW_DF.csv",index=False)
    print("new_df_columns",new_df.columns)
    new_df[['CR_EARLY_AM','CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']]=new_df[['CR_EARLY_AM','CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']].applymap(convert_string_to_integer)
 
    # new_df['Overall Goal']=cr_df[overall_goal_column[0]]
    new_df.fillna(0,inplace=True)

    # adding values for AM, PM, MIDDAY and Evening from Database file to new Dataframe
    for index, row in new_df.iterrows():
        route_code = row['ROUTE_SURVEYEDCode']

        # Define a function to get the counts and IDs
        def get_counts_and_ids(time_values):
            # Just for SALEM
#             subset_df = df[(df['ROUTE_SURVEYEDCode_Splited'] == route_code) & (df[time_column[0]].isin(time_values))]
            subset_df = df[(df['ROUTE_SURVEYEDCode'] == route_code) & (df[time_column[0]].isin(time_values))]
            count = subset_df.shape[0]
            ids = subset_df['id'].values
            return count, ids
        
        # Calculate counts and IDs for each time slot
        am_value, am_value_ids = get_counts_and_ids(am_values)
        midday_value, midday_value_ids = get_counts_and_ids(midday_values)
        pm_value, pm_value_ids = get_counts_and_ids(pm_values)
        evening_value, evening_value_ids = get_counts_and_ids(evening_values)
        
        # Assign values to new_df
        new_df.loc[index, 'CR_Total'] = row['CR_EARLY_AM'] + row['CR_AM_Peak'] + row['CR_Midday'] + row['CR_PM_Peak'] + row['CR_Evening']
        new_df.loc[index, 'CR_AM_Peak'] =row['CR_EARLY_AM']+ row['CR_AM_Peak']
        new_df.loc[index, 'DB_AM_Peak'] = am_value
        new_df.loc[index, 'DB_Midday'] = midday_value
        new_df.loc[index, 'DB_PM_Peak'] = pm_value
        new_df.loc[index, 'DB_Evening'] = evening_value
        new_df.loc[index, 'DB_Total'] = evening_value + am_value + midday_value + pm_value
        
        # Join the IDs as a comma-separated string
        new_df.loc[index, 'DB_AM_IDS'] = ', '.join(map(str, am_value_ids))
        new_df.loc[index, 'DB_Midday_IDS'] = ', '.join(map(str, midday_value_ids))
        new_df.loc[index, 'DB_PM_IDS'] = ', '.join(map(str, pm_value_ids))
        new_df.loc[index, 'DB_Evening_IDS'] = ', '.join(map(str, evening_value_ids))

#     new_df.to_csv('Time Base Comparison(Over All).csv',index=False)

    # Route Level Comparison
    # Just for SALEM because in SALEM Code values are already splitted
#     new_df['ROUTE_SURVEYEDCode_Splited']=new_df['ROUTE_SURVEYEDCode']
    new_df['ROUTE_SURVEYEDCode_Splited']=new_df['ROUTE_SURVEYEDCode'].apply(lambda x:('_').join(x.split('_')[:-1]) )

    # creating new dataframe for ROUTE_LEVEL_Comparison
    route_level_df=pd.DataFrame()

    unique_routes=new_df['ROUTE_SURVEYEDCode_Splited'].unique()

    route_level_df['ROUTE_SURVEYEDCode']=unique_routes

    route_df.rename(columns={'ROUTE_TOTAL':'CR_Overall_Goal','SURVEY_ROUTE_CODE':'ROUTE_SURVEYEDCode','LS_NAME_CODE':'ROUTE_SURVEYEDCode'},inplace=True)

    route_df.dropna(subset=['ROUTE_SURVEYEDCode'],inplace=True)
    route_level_df=pd.merge(route_level_df,route_df[['ROUTE_SURVEYEDCode','CR_Overall_Goal']],on='ROUTE_SURVEYEDCode')

    # adding values from database file and compeletion report for Route_Level
    for index , row in route_level_df.iterrows():
        subset_df=new_df[new_df['ROUTE_SURVEYEDCode_Splited']==row['ROUTE_SURVEYEDCode']]
        # sum_per_route_cr = subset_df[['CR_AM_Peak', 'CR_Midday', 'CR_PM_Peak', 'CR_Evening','CR_Total','Overall Goal']].sum()
        sum_per_route_cr = subset_df[['CR_EARLY_AM','CR_AM_Peak', 'CR_Midday', 'CR_PM_Peak', 'CR_Evening','CR_Total']].sum()
        sum_per_route_db = subset_df[['DB_AM_Peak', 'DB_Midday', 'DB_PM_Peak', 'DB_Evening','DB_Total']].sum()
        
        # route_level_df.loc[index,'CR_Pre_Early_AM']=sum_per_route_cr['CR_Pre_Early_AM']
        # route_level_df.loc[index,'CR_Early_AM']=sum_per_route_cr['CR_Early_AM']
        route_level_df.loc[index,'CR_AM_Peak']=sum_per_route_cr['CR_AM_Peak']
        route_level_df.loc[index,'CR_Midday']=sum_per_route_cr['CR_Midday']
        route_level_df.loc[index,'CR_PM_Peak']=sum_per_route_cr['CR_PM_Peak']
        route_level_df.loc[index,'CR_Evening']=sum_per_route_cr['CR_Evening']
        route_level_df.loc[index,'CR_Total']=sum_per_route_cr['CR_Total']
        # route_level_df.loc[index,'CR_Overall_Goal']=sum_per_route_cr['Overall Goal']
        
        route_level_df.loc[index,'DB_AM_Peak']=sum_per_route_db['DB_AM_Peak']
        route_level_df.loc[index,'DB_Midday']=sum_per_route_db['DB_Midday']
        route_level_df.loc[index,'DB_PM_Peak']=sum_per_route_db['DB_PM_Peak']
        route_level_df.loc[index,'DB_Evening']=sum_per_route_db['DB_Evening']
        route_level_df.loc[index,'DB_Total']=sum_per_route_db['DB_Total']   
        route_level_df.loc[index,'DB_AM_IDS']=', '.join(str(value) for value in subset_df['DB_AM_IDS'].values)    
        route_level_df.loc[index,'DB_Midday_IDS']=', '.join(str(value) for value in subset_df['DB_Midday_IDS'].values)    
        route_level_df.loc[index,'DB_PM_IDS']=', '.join(str(value) for value in subset_df['DB_PM_IDS'].values)    
        route_level_df.loc[index,'DB_Evening_IDS']=', '.join(str(value) for value in subset_df['DB_Evening_IDS'].values)

    # route_level_df.to_csv('Route Level Comparison(Value_Check).csv',index=False)
        
    # calculating the difference between values of database and compeletion report for Route_Level
    for index, row in route_level_df.iterrows():
        am_peak_diff=row['CR_AM_Peak']-row['DB_AM_Peak']
        midday_diff=row['CR_Midday']-row['DB_Midday']    
        pm_peak_diff=row['CR_PM_Peak']-row['DB_PM_Peak']
        evening_diff=row['CR_Evening']-row['DB_Evening']
        total_diff=row['CR_Total']-row['DB_Total']
        overall_difference=row['CR_Overall_Goal']-row['DB_Total']
        route_level_df.loc[index, 'AM_DIFFERENCE'] = math.ceil(max(0, am_peak_diff))
        route_level_df.loc[index, 'Midday_DIFFERENCE'] = math.ceil(max(0, midday_diff))
        route_level_df.loc[index, 'PM_DIFFERENCE'] = math.ceil(max(0, pm_peak_diff))
        route_level_df.loc[index, 'Evening_DIFFERENCE'] = math.ceil(max(0, evening_diff))
        # route_level_df.loc[index, 'Total_DIFFERENCE'] = math.ceil(max(0, total_diff))
        route_level_df.loc[index, 'Total_DIFFERENCE'] =math.ceil(max(0, am_peak_diff))+math.ceil(max(0, midday_diff))+math.ceil(max(0, pm_peak_diff))+math.ceil(max(0, evening_diff))
        route_level_df.loc[index, 'Overall_Goal_DIFFERENCE'] = math.ceil(max(0,overall_difference))

    return route_level_df

In [ ]:
wkday_route_level =create_route_level_df(wkday_overall_df,wkday_route_df,weekday_df)

In [ ]:
wkday_route_level

In [ ]:
am_values=['AM1','AM2','AM3','AM4']
# for SEATTLE
midday_values=['AM5','AM6','AM7','MID1','MID2','MID3']
# FOR SEATTLE
pm_values=['PM1','PM2','PM3','PM4']
# FOR SEATTLE
evening_values=['PM5','PM6','PM7','PM8']

early_am_column=[0]  #1 is for Early AM header
# am_column=[2] #2 is for AM header
am_column=[1] #This is for AM header
midday_colum=[2] #this is for MIDDAY header
pm_column=[4] #this is for PM header
evening_column=[5] #this is for EVENING header


def convert_string_to_integer(x):
    try:
        return float(x)
    except (ValueError, TypeError):
        return 0

In [ ]:
new_df=pd.DataFrame()
new_df['ROUTE_SURVEYEDCode']=wkday_overall_df['LS_NAME_CODE']
new_df['CR_EARLY_AM']=wkday_overall_df[early_am_column[0]]
new_df['CR_AM_Peak']=wkday_overall_df[am_column[0]]
new_df['CR_Midday']=wkday_overall_df[midday_colum[0]]
new_df['CR_PM_Peak']=wkday_overall_df[pm_column[0]]
new_df['CR_Evening']=wkday_overall_df[evening_column[0]]
#     new_df.to_csv("NEW_DF.csv",index=False)
print("new_df_columns",new_df.columns)
new_df[['CR_EARLY_AM','CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']]=new_df[['CR_EARLY_AM','CR_AM_Peak','CR_Midday','CR_PM_Peak','CR_Evening']].applymap(convert_string_to_integer)

In [ ]:
new_df.fillna(0,inplace=True)

In [ ]:
new_df.head()

In [ ]:
for index, row in new_df.iterrows():
    route_code = row['ROUTE_SURVEYEDCode']
    
    # Define a function to get the counts and IDs
    def get_counts_and_ids(time_values):
        # Just for SALEM
        subset_df = df[(df['ROUTE_SURVEYEDCode_Splited'] == route_code) & (df[time_column[0]].isin(time_values))]
        # subset_df = df[(df['ROUTE_SURVEYEDCode'] == route_code) & (df[time_column[0]].isin(time_values))]
        count = subset_df.shape[0]
        ids = subset_df['id'].values
        return count, ids

    # Calculate counts and IDs for each time slot
    am_value, am_value_ids = get_counts_and_ids(am_values)
    midday_value, midday_value_ids = get_counts_and_ids(midday_values)
    pm_value, pm_value_ids = get_counts_and_ids(pm_values)
    evening_value, evening_value_ids = get_counts_and_ids(evening_values)

    # Assign values to new_df
    new_df.loc[index, 'CR_Total'] = row['CR_EARLY_AM'] + row['CR_AM_Peak'] + row['CR_Midday'] + row['CR_PM_Peak'] + row['CR_Evening']
    new_df.loc[index, 'CR_AM_Peak'] =row['CR_EARLY_AM']+ row['CR_AM_Peak']
    new_df.loc[index, 'DB_AM_Peak'] = am_value
    new_df.loc[index, 'DB_Midday'] = midday_value
    new_df.loc[index, 'DB_PM_Peak'] = pm_value
    new_df.loc[index, 'DB_Evening'] = evening_value
    new_df.loc[index, 'DB_Total'] = evening_value + am_value + midday_value + pm_value

In [ ]:
new_df.head()

In [ ]:
df[(df['ROUTE_SURVEYEDCode_Splited'] == 'SND_1_510') & (df[time_column[0]].isin(midday_values))]

In [ ]:
route_value="_".join("SND_1_510_01".split('_')[:-1])
route_value

In [ ]:
value="SND_1_510_00".split('_')
if len(value)>3:
    route_value="_".join(value[:-1])
else:
    route_value="_".join(value)
route_value

In [ ]:
def edit_ls_code_column(x):
    value=x.split('_')
    if len(value)>3:
        route_value="_".join(value[:-1])
    else:
        route_value="_".join(value)
    return route_value

In [ ]:
edit_ls_code_column("SND_1_510_00")