In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [2]:
df=pd.read_excel("reviewtool_20240828_DENVER_reviewerstats.xlsx",sheet_name='Route Summary')
df.head()

,Route,Total_Reviews,Total_Removals,Removal_Rate_Percentage,Route_Reviewed_Percentage,Removed_Survey_ids,Sum of Origin Change,Sum of Destin Change,Sum of NextTrans Change,Sum of PrevTrans Change,...,Sum of Origin Change.1,Sum of Destin Change.1,Sum of PrevTrans Change.1,Sum of NextTrans Change.1,Sum of Record Change.1,Origin Change Percentage.1,Destin Change Percentage.1,NextTrans Change Percentage.1,PrevTrans Change Percentage.1,Record Change Percentage.1
0,RTD_1_AB1,60,0,0.000000,6.0,NaN,30,21,0,0,...,34.0,30.0,2.0,0.0,66.0,22.67%,20.0%,0.0%,1.33%,44.0%
1,RTD_1_323,18,0,0.000000,1.8,NaN,0,0,0,0,...,2.0,5.0,7.0,6.0,19.0,1.83%,4.59%,5.5%,6.42%,17.43%
2,RTD_1_324,49,1,2.040816,4.9,14278,0,1,1,0,...,4.0,3.0,7.0,6.0,18.0,3.96%,2.97%,5.94%,6.93%,17.82%
3,RTD_1_208,12,0,0.000000,1.2,NaN,0,1,0,0,...,2.0,6.0,3.0,9.0,19.0,1.0%,3.0%,4.5%,1.5%,9.5%
4,RTD_1_206,1,0,0.000000,0.1,NaN,0,0,0,0,...,3.0,4.0,11.0,9.0,25.0,2.13%,2.84%,6.38%,7.8%,17.73%

In [3]:
df.columns

Index(['Route', 'Total_Reviews', 'Total_Removals', 'Removal_Rate_Percentage',
       'Route_Reviewed_Percentage', 'Removed_Survey_ids',
       'Sum of Origin Change', 'Sum of Destin Change',
       'Sum of NextTrans Change', 'Sum of PrevTrans Change',
       'Sum of Record Change', 'Origin Change Percentage',
       'Destin Change Percentage', 'NextTrans Change Percentage',
       'PrevTrans Change Percentage', 'Record Change Percentage', 'Row Labels',
       'Count of Elvis_ID', 'Sum of Origin Change.1', 'Sum of Destin Change.1',
       'Sum of PrevTrans Change.1', 'Sum of NextTrans Change.1',
       'Sum of Record Change.1', 'Origin Change Percentage.1',
       'Destin Change Percentage.1', 'NextTrans Change Percentage.1',
       'PrevTrans Change Percentage.1', 'Record Change Percentage.1'],
      dtype='object')

In [9]:
df[df['Removal_Rate_Percentage']>10][['Route','Total_Reviews','Total_Removals','Removal_Rate_Percentage','Removed_Survey_ids']]
# df[df['Removal_Rate_Percentage']>10][['Route','Total_Reviews','Total_Removals','Removal_Rate_Percentage','Removed_Survey_ids']].to_csv('Route_High_Percentange_Removal.csv',index=False)

,Route,Total_Reviews,Total_Removals,Removal_Rate_Percentage,Removed_Survey_ids
7,RTD_1_A,105,12,11.428571,"12328, 12538, 13459, 13474, 13488, 13523, 1353..."
13,RTD_1_FF,7,2,28.571429,"12382, 12577"
14,RTD_1_N,145,17,11.724138,"12569, 12616, 12736, 12805, 12920, 12980, 1302..."
15,RTD_1_G,165,21,12.727273,"12613, 12672, 12799, 12876, 12878, 13010, 1305..."