In [1]:
import pandas as pd
import numpy as np
from datetime import date,datetime
import warnings
import copy
from rapidfuzz import process, fuzz


warnings.filterwarnings('ignore')

In [2]:
def check_all_code_columns(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df_columns_lower if "code" in column]

    return matching_columns


def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

def clean_string(s):
    return s.replace(':', '').replace('-', '').replace(')', '').replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

In [3]:
today_date = date.today()
today_date=''.join(str(today_date).split('-'))
project_name='SEATTLE'


df=pd.read_csv('seattle_rail2024o2o_export_odbc.csv')

# Details File O2O_STOPS Sheet
detail_df=pd.read_excel('details_project_od_Seattle2 (1).xlsx',sheet_name='O2O_STOPS')

# Details File Stops Sheet
seq_df=pd.read_excel('details_project_od_Seattle2 (1).xlsx',sheet_name='STOPS')

In [4]:
# df=df.iloc[:15,:]
# df.head()

In [5]:
df.shape

(1161, 36)

In [6]:
df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT', 'ORIGRESPID', 'ROUTE_SURVEYED_Code_', 'ROUTE_SURVEYED',
       'ROUTE_SURVEYED_Other_', 'STLINE2_ON_Code_', 'STLINE2_ON',
       'STLINE2_OFF_Code_', 'STLINE2_OFF', 'SSSL_ON_Code_', 'SSSL_ON',
       'SSSL_OFF_Code_', 'SSSL_OFF', 'S1L_ON_Code_', 'S1L_ON', 'S1L_OFF_Code_',
       'S1L_OFF', 'STTAC_ON_Code_', 'STTAC_ON', 'STTAC_OFF_Code_', 'STTAC_OFF',
       'TIME_BOARDED_Code_', 'TIME_BOARDED', 'LANGUAGE_Code_', 'LANGUAGE',
       'LANGUAGE_Other_', 'RESTART_URL'],
      dtype='object')

In [7]:
df['ROUTE_SURVEYED_Code_'].unique()

array(['STLINE2', 'SSSL'], dtype=object)

In [8]:

code_columns=check_all_code_columns(df,df.columns)

code_columns=check_all_characters_present(df,code_columns)
columns_to_remove=[]
for column in code_columns:
    cleaned_column=clean_string(column)
#     if 'routesurveyed' in cleaned_column or 'language' in cleaned_column:
    if 'time' in cleaned_column or 'language' in cleaned_column:
        columns_to_remove.append(column)
columns_to_remove

['TIME_BOARDED_Code_', 'LANGUAGE_Code_']

In [9]:
detail_df.ETC_ROUTE_ID.unique()

array(['SND_1_SLine_00', 'SND_1_1Line_01', 'SND_1_TLine_00',
       'SND_1_2Line_00'], dtype=object)

In [10]:
seq_df.ETC_ROUTE_ID.unique()

array(['CMT_1_101_00', 'CMT_1_101_01', 'CMT_1_102_00', 'CMT_1_102_01',
       'CMT_1_105_00', 'CMT_1_105_01', 'CMT_1_106_00', 'CMT_1_106_01',
       'CMT_1_107_00', 'CMT_1_107_01', 'CMT_1_109_00', 'CMT_1_109_01',
       'CMT_1_111_00', 'CMT_1_111_01', 'CMT_1_112_00', 'CMT_1_112_01',
       'CMT_1_113_00', 'CMT_1_113_01', 'CMT_1_114_00', 'CMT_1_114_01',
       'CMT_1_115_00', 'CMT_1_115_01', 'CMT_1_116_00', 'CMT_1_116_01',
       'CMT_1_119_00', 'CMT_1_119_01', 'CMT_1_120_00', 'CMT_1_120_01',
       'CMT_1_130_00', 'CMT_1_130_01', 'CMT_1_166_00', 'CMT_1_166_01',
       'CMT_1_196_00', 'CMT_1_196_01', 'CMT_1_201_00', 'CMT_1_201_01',
       'CMT_1_202_00', 'CMT_1_202_01', 'CMT_1_209_00', 'CMT_1_209_01',
       'CMT_1_220_00', 'CMT_1_220_01', 'CMT_1_222_00', 'CMT_1_222_01',
       'CMT_1_227_00', 'CMT_1_227_01', 'CMT_1_230_00', 'CMT_1_230_01',
       'CMT_1_240_00', 'CMT_1_240_01', 'CMT_1_247_00', 'CMT_1_247_01',
       'CMT_1_270_00', 'CMT_1_270_01', 'CMT_1_271_00', 'CMT_1_271_01',
       'CMT_1_280_00', 'CMT_1_280_01', 'CMT_1_402_00', 'CMT_1_402_01',
       'CMT_1_405_00', 'CMT_1_405_01', 'CMT_1_410_00', 'CMT_1_410_01',
       'CMT_1_412_00', 'CMT_1_412_01', 'CMT_1_413_00', 'CMT_1_413_01',
       'CMT_1_415_00', 'CMT_1_415_01', 'CMT_1_416_00', 'CMT_1_416_01',
       'CMT_1_417_00', 'CMT_1_417_01', 'CMT_1_421_00', 'CMT_1_421_01',
       'CMT_1_422_00', 'CMT_1_422_01', 'CMT_1_424_00', 'CMT_1_424_01',
       'CMT_1_425_00', 'CMT_1_425_01', 'CMT_1_435_00', 'CMT_1_435_01',
       'CMT_1_810_00', 'CMT_1_810_01', 'CMT_1_821_00', 'CMT_1_821_01',
       'CMT_1_860_00', 'CMT_1_860_01', 'CMT_1_871_00', 'CMT_1_871_01',
       'CMT_1_880_00', 'CMT_1_880_01', 'CMT_1_SwiftBlue_00',
       'CMT_1_SwiftBlue_01', 'CMT_1_SwiftGreen_00', 'CMT_1_SwiftGreen_01',
       'CMT_1_SwiftOrange_00', 'CMT_1_SwiftOrange_01',
       'COS_1_FirstHillStreetcar_00', 'COS_1_FirstHillStreetcar_01',
       'COS_1_SouthLakeUnionStreetcar_00',
       'COS_1_SouthLakeUnionStreetcar_01', 'EVR_1_12_00', 'EVR_1_12_01',
       'EVR_1_18_00', 'EVR_1_18_01', 'EVR_1_19_00', 'EVR_1_19_01',
       'EVR_1_2_00', 'EVR_1_2_01', 'EVR_1_29_00', 'EVR_1_29_01',
       'EVR_1_3_00', 'EVR_1_3_01', 'EVR_1_4_00', 'EVR_1_4_01',
       'EVR_1_6_00', 'EVR_1_6_01', 'EVR_1_7_00', 'EVR_1_7_01',
       'EVR_1_8_00', 'EVR_1_8_01', 'INT_1_12_00', 'INT_1_12_01',
       'INT_1_13_00', 'INT_1_13_01', 'INT_1_21_00', 'INT_1_21_01',
       'INT_1_41_00', 'INT_1_41_01', 'INT_1_42_00', 'INT_1_42_01',
       'INT_1_45_00', 'INT_1_45_01', 'INT_1_47_00', 'INT_1_47_01',
       'INT_1_48_00', 'INT_1_48_01', 'INT_1_60_00', 'INT_1_60_01',
       'INT_1_620_00', 'INT_1_620_01', 'INT_1_62A_00', 'INT_1_62A_01',
       'INT_1_62B_00', 'INT_1_62B_01', 'INT_1_64_00', 'INT_1_64_01',
       'INT_1_65_00', 'INT_1_65_01', 'INT_1_66_00', 'INT_1_66_01',
       'INT_1_67_00', 'INT_1_67_01', 'INT_1_68_00', 'INT_1_68_01',
       'INT_1_94_00', 'INT_1_94_01', 'KIT_1_106_00', 'KIT_1_106_01',
       'KIT_1_184_00', 'KIT_1_212_00', 'KIT_1_212_01', 'KIT_1_215_00',
       'KIT_1_215_01', 'KIT_1_217_00', 'KIT_1_217_01', 'KIT_1_219_00',
       'KIT_1_219_01', 'KIT_1_220_00', 'KIT_1_220_01', 'KIT_1_221_00',
       'KIT_1_221_01', 'KIT_1_222_00', 'KIT_1_222_01', 'KIT_1_223_00',
       'KIT_1_223_01', 'KIT_1_224_00', 'KIT_1_224_01', 'KIT_1_225_00',
       'KIT_1_225_01', 'KIT_1_226_00', 'KIT_1_226_01', 'KIT_1_228_00',
       'KIT_1_228_01', 'KIT_1_229_00', 'KIT_1_229_01', 'KIT_1_235_00',
       'KIT_1_235_01', 'KIT_1_237_00', 'KIT_1_237_01', 'KIT_1_301_00',
       'KIT_1_301_01', 'KIT_1_302_00', 'KIT_1_302_01', 'KIT_1_307_00',
       'KIT_1_307_01', 'KIT_1_332_00', 'KIT_1_332_01', 'KIT_1_333_00',
       'KIT_1_333_01', 'KIT_1_344_00', 'KIT_1_344_01', 'KIT_1_390_00',
       'KIT_1_390_01', 'KIT_1_4_01', 'KIT_1_5_01', 'KIT_1_8_00',
       'KIT_1_8_01', 'KIT_1_81_00', 'KIT_1_81_01', 'KIT_1_85_00',
       'KIT_1_85_01', 'KIT_1_86_00', 'KIT_1_86_01', 'KIT_1_9_01',
       'KIT_1_93_00', 'KIT_1_93_01', 'KIT_1_94_00', 'KIT_1_94_01',
       'KIT_1_95_00', 'KIT_1_95_01', 'KIT_1_96_00', 'KIT_1_96_01',
       'KIT_1_97_00', 'KIT_1_97_01', 'KIT_1_98_00', 'KIT_1_98_01',
       'KIT_1_99_00', 'KIT_1_99_01', 'KIT_1_AFF_00', 'KIT_1_AFF_01',
       'KIT_1_BIRIDE_00', 'KIT_1_BIRIDE_01', 'KIT_1_BPOFF_00',
       'KIT_1_BPOFF_01', 'KIT_1_BSFF_00', 'KIT_1_KRIDE_00',
       'KIT_1_KRIDE_01', 'KIT_1_KSFF_00', 'KIT_1_NFTH_00',
       'KIT_1_Seattle-BremertonFastFerry_01', 'KIT_1_SKFF_01',
       'KIT_1_SKRIDE_00', 'KIT_1_SKRIDE_01', 'KIT_1_SOD_00',
       'KIT_1_SOD_01', 'KIT_1_SSFF_00', 'KIT_1_SSFF_01', 'MET_1_1_00',
       'MET_1_1_01', 'MET_1_10_00', 'MET_1_10_01', 'MET_1_101_00',
       'MET_1_101_01', 'MET_1_102_00', 'MET_1_102_01', 'MET_1_105_00',
       'MET_1_105_01', 'MET_1_106_00', 'MET_1_106_01', 'MET_1_107_00',
       'MET_1_107_01', 'MET_1_11_00', 'MET_1_11_01', 'MET_1_111_00',
       'MET_1_111_01', 'MET_1_113_00', 'MET_1_113_01', 'MET_1_118_00',
       'MET_1_118_01', 'MET_1_119_00', 'MET_1_119_01', 'MET_1_12_00',
       'MET_1_12_01', 'MET_1_124_00', 'MET_1_124_01', 'MET_1_125_00',
       'MET_1_125_01', 'MET_1_128_00', 'MET_1_128_01', 'MET_1_13_00',
       'MET_1_13_01', 'MET_1_131_00', 'MET_1_131_01', 'MET_1_132_00',
       'MET_1_132_01', 'MET_1_14_00', 'MET_1_14_01', 'MET_1_148_00',
       'MET_1_148_01', 'MET_1_150_00', 'MET_1_150_01', 'MET_1_153_00',
       'MET_1_153_01', 'MET_1_156_00', 'MET_1_156_01', 'MET_1_160_00',
       'MET_1_160_01', 'MET_1_161_00', 'MET_1_161_01', 'MET_1_162_00',
       'MET_1_162_01', 'MET_1_165_00', 'MET_1_165_01', 'MET_1_168_00',
       'MET_1_168_01', 'MET_1_17_00', 'MET_1_17_01', 'MET_1_177_00',
       'MET_1_177_01', 'MET_1_181_00', 'MET_1_181_01', 'MET_1_182_00',
       'MET_1_182_01', 'MET_1_183_00', 'MET_1_183_01', 'MET_1_184_00',
       'MET_1_184_01', 'MET_1_187_00', 'MET_1_187_01', 'MET_1_193_00',
       'MET_1_193_01', 'MET_1_2_00', 'MET_1_2_01', 'MET_1_20_00',
       'MET_1_20_01', 'MET_1_204_00', 'MET_1_204_01', 'MET_1_208_00',
       'MET_1_208_01', 'MET_1_21_00', 'MET_1_21_01', 'MET_1_212_00',
       'MET_1_212_01', 'MET_1_218_00', 'MET_1_218_01', 'MET_1_22_00',
       'MET_1_22_01', 'MET_1_221_00', 'MET_1_221_01', 'MET_1_224_00',
       'MET_1_224_01', 'MET_1_225_00', 'MET_1_225_01', 'MET_1_226_00',
       'MET_1_226_01', 'MET_1_230_00', 'MET_1_230_01', 'MET_1_231_00',
       'MET_1_231_01', 'MET_1_239_00', 'MET_1_239_01', 'MET_1_24_00',
       'MET_1_24_01', 'MET_1_240_00', 'MET_1_240_01', 'MET_1_241_00',
       'MET_1_241_01', 'MET_1_245_00', 'MET_1_245_01', 'MET_1_246_00',
       'MET_1_246_01', 'MET_1_249_00', 'MET_1_249_01', 'MET_1_250_00',
       'MET_1_250_01', 'MET_1_255_00', 'MET_1_255_01', 'MET_1_257_00',
       'MET_1_257_01', 'MET_1_269_00', 'MET_1_269_01', 'MET_1_27_00',
       'MET_1_27_01', 'MET_1_271_00', 'MET_1_271_01', 'MET_1_28_00',
       'MET_1_28_01', 'MET_1_3_00', 'MET_1_3_01', 'MET_1_302_00',
       'MET_1_302_01', 'MET_1_303_00', 'MET_1_303_01', 'MET_1_31_00',
       'MET_1_31_01', 'MET_1_311_00', 'MET_1_311_01', 'MET_1_32_00',
       'MET_1_32_01', 'MET_1_322_00', 'MET_1_322_01', 'MET_1_33_00',
       'MET_1_33_01', 'MET_1_330_00', 'MET_1_330_01', 'MET_1_331_00',
       'MET_1_331_01', 'MET_1_345_00', 'MET_1_345_01', 'MET_1_346_00',
       'MET_1_346_01', 'MET_1_347_00', 'MET_1_347_01', 'MET_1_348_00',
       'MET_1_348_01', 'MET_1_36_00', 'MET_1_36_01', 'MET_1_372_00',
       'MET_1_372_01', 'MET_1_4_00', 'MET_1_4_01', 'MET_1_40_00',
       'MET_1_40_01', 'MET_1_43_00', 'MET_1_43_01', 'MET_1_44_00',
       'MET_1_44_01', 'MET_1_45_00', 'MET_1_45_01', 'MET_1_48_00',
       'MET_1_48_01', 'MET_1_49_00', 'MET_1_49_01', 'MET_1_5_00',
       'MET_1_5_01', 'MET_1_50_00', 'MET_1_50_01', 'MET_1_56_00',
       'MET_1_56_01', 'MET_1_57_00', 'MET_1_57_01', 'MET_1_60_00',
       'MET_1_60_01', 'MET_1_62_00', 'MET_1_62_01', 'MET_1_630_00',
       'MET_1_630_01', 'MET_1_631_00', 'MET_1_631_01', 'MET_1_635_00',
       'MET_1_635_01', 'MET_1_65_00', 'MET_1_65_01', 'MET_1_67_00',
       'MET_1_67_01', 'MET_1_7_00', 'MET_1_7_01', 'MET_1_70_00',
       'MET_1_70_01', 'MET_1_73_00', 'MET_1_73_01', 'MET_1_75_00',
       'MET_1_75_01', 'MET_1_773_00', 'MET_1_773_01', 'MET_1_775_00',
       'MET_1_775_01', 'MET_1_79_00', 'MET_1_79_01', 'MET_1_8_00',
       'MET_1_8_01', 'MET_1_893_00', 'MET_1_893_01', 'MET_1_895_00',
       'MET_1_895_01', 'MET_1_9_00', 'MET_1_9_01', 'MET_1_901_00',
       'MET_1_901_01', 'MET_1_903_00', 'MET_1_903_01', 'MET_1_906_00',
       'MET_1_906_01', 'MET_1_907_00', 'MET_1_907_01', 'MET_1_914_00',
       'MET_1_915_00', 'MET_1_915_01', 'MET_1_917_00', 'MET_1_917_01',
       'MET_1_930_00', 'MET_1_930_01', 'MET_1_973_00', 'MET_1_973_01',
       'MET_1_975_00', 'MET_1_975_01', 'MET_1_981_00', 'MET_1_982_00',
       'MET_1_982_01', 'MET_1_984_01', 'MET_1_986_00', 'MET_1_986_01',
       'MET_1_987_00', 'MET_1_987_01', 'MET_1_988_00', 'MET_1_988_01',
       'MET_1_989_00', 'MET_1_989_01', 'MET_1_994_00', 'MET_1_994_01',
       'MET_1_ALine_00', 'MET_1_ALine_01', 'MET_1_BLine_00',
       'MET_1_BLine_01', 'MET_1_CLine_00', 'MET_1_CLine_01',
       'MET_1_DLine_00', 'MET_1_DLine_01',
       'MET_1_Duvall-MonroeShuttle_00', 'MET_1_ELine_00',
       'MET_1_ELine_01', 'MET_1_FLine_00', 'MET_1_FLine_01',
       'MET_1_HLine_00', 'MET_1_HLine_01', 'MET_1_SVT_00', 'MET_1_SVT_01',
       'PIE_1_1_00', 'PIE_1_1_01', 'PIE_1_10_00', 'PIE_1_10_01',
       'PIE_1_100_00', 'PIE_1_100_01', 'PIE_1_11_00', 'PIE_1_11_01',
       'PIE_1_13_00', 'PIE_1_13_01', 'PIE_1_16_00', 'PIE_1_16_01',
       'PIE_1_2_00', 'PIE_1_2_01', 'PIE_1_202_00', 'PIE_1_202_01',
       'PIE_1_206_00', 'PIE_1_206_01', 'PIE_1_212_00', 'PIE_1_212_01',
       'PIE_1_214_00', 'PIE_1_214_01', 'PIE_1_28_00', 'PIE_1_28_01',
       'PIE_1_3_00', 'PIE_1_3_01', 'PIE_1_4_00', 'PIE_1_4_01',
       'PIE_1_400_00', 'PIE_1_400_01', 'PIE_1_402_00', 'PIE_1_402_01',
       'PIE_1_409_00', 'PIE_1_409_01', 'PIE_1_41_00', 'PIE_1_41_01',
       'PIE_1_42_00', 'PIE_1_42_01', 'PIE_1_425_00', 'PIE_1_425_01',
       'PIE_1_45_00', 'PIE_1_45_01', 'PIE_1_48_00', 'PIE_1_48_01',
       'PIE_1_497_00', 'PIE_1_497_01', 'PIE_1_500_00', 'PIE_1_500_01',
       'PIE_1_501_00', 'PIE_1_501_01', 'PIE_1_52_00', 'PIE_1_52_01',
       'PIE_1_53_00', 'PIE_1_53_01', 'PIE_1_54_00', 'PIE_1_54_01',
       'PIE_1_55_00', 'PIE_1_55_01', 'PIE_1_57_00', 'PIE_1_57_01',
       'PIE_1_63_00', 'PIE_1_63_01', 'PIE_1_701_00', 'PIE_1_701_01',
       'SCM_1_SCWEST_00', 'SCM_1_SCWEST_01', 'SND_1_1Line_00',
       'SND_1_1Line_01', 'SND_1_510_00', 'SND_1_510_01', 'SND_1_512_00',
       'SND_1_512_01', 'SND_1_513_00', 'SND_1_513_01', 'SND_1_522_00',
       'SND_1_522_01', 'SND_1_532_00', 'SND_1_532_01', 'SND_1_535_00',
       'SND_1_535_01', 'SND_1_542_00', 'SND_1_542_01', 'SND_1_545_00',
       'SND_1_545_01', 'SND_1_550_00', 'SND_1_550_01', 'SND_1_554_00',
       'SND_1_554_01', 'SND_1_556_00', 'SND_1_556_01', 'SND_1_560_00',
       'SND_1_560_01', 'SND_1_566_00', 'SND_1_566_01', 'SND_1_574_00',
       'SND_1_574_01', 'SND_1_577_00', 'SND_1_577_01', 'SND_1_578_00',
       'SND_1_578_01', 'SND_1_580_00', 'SND_1_580_01', 'SND_1_586_00',
       'SND_1_586_01', 'SND_1_590_00', 'SND_1_590_01', 'SND_1_592_00',
       'SND_1_592_01', 'SND_1_594_00', 'SND_1_594_01', 'SND_1_595_00',
       'SND_1_595_01', 'SND_1_596_00', 'SND_1_596_01', 'SND_1_NLine_00',
       'SND_1_NLine_01', 'SND_1_SLine_00', 'SND_1_SLine_01',
       'SND_1_TLine_00', 'SND_1_TLine_01', 'WSF_1_ANAFH_00',
       'WSF_1_ANALI_00', 'WSF_1_ANAORCA_00', 'WSF_1_ANASHAW_00',
       'WSF_1_BAINIS_00', 'WSF_1_BREMSEA_00', 'WSF_1_CLINTONMUKI_00',
       'WSF_1_COUPT_00', 'WSF_1_EDKING_00', 'WSF_1_FAUNTSOUTH_00',
       'WSF_1_FAUNTVASH_00', 'WSF_1_FHANA_01', 'WSF_1_FHLOPEZ_00',
       'WSF_1_FHORCA_00', 'WSF_1_FHSHAW_00', 'WSF_1_KINGED_01',
       'WSF_1_LOPEZANA_01', 'WSF_1_LOPEZFH_01', 'WSF_1_LOPEZORCA_00',
       'WSF_1_LOPEZSHAW_00', 'WSF_1_MUKICLINT_01', 'WSF_1_ORCAANA_01',
       'WSF_1_ORCAFRIDAY_01', 'WSF_1_ORCALOPEZ_01', 'WSF_1_ORCASHAW_00',
       'WSF_1_POINTTAHL_00', 'WSF_1_PORTCOUP_01', 'WSF_1_SEABAIN_01',
       'WSF_1_SEABREM_01', 'WSF_1_SHAWANA_01', 'WSF_1_SHAWFRIDAY_01',
       'WSF_1_SHAWLOPEZ_01', 'WSF_1_SHAWORCA_01', 'WSF_1_SOUTHFAUNT_01',
       'WSF_1_SOUTHVASH_00', 'WSF_1_TAHLPOINT_01', 'WSF_1_VASHFAUNT_01',
       'WSF_1_VASHSOUTH_01', 'SND_1_2Line_00', 'SND_1_2Line_01'],
      dtype=object)

In [11]:
o2o_df=copy.deepcopy(df)

new_df=o2o_df.drop(columns=columns_to_remove)

code_columns_check=check_all_characters_present(new_df,code_columns)

new_code_columns=check_all_characters_present(new_df,code_columns_check)

route_surveyed_column_check=['routesurveyed']
route_surveyed_column=check_all_characters_present(new_df,route_surveyed_column_check)
route_surveyed_column

['ROUTE_SURVEYED']

In [12]:
new_code_columns

['ROUTE_SURVEYED_Code_',
 'STLINE2_ON_Code_',
 'STLINE2_OFF_Code_',
 'SSSL_ON_Code_',
 'SSSL_OFF_Code_',
 'S1L_ON_Code_',
 'S1L_OFF_Code_',
 'STTAC_ON_Code_',
 'STTAC_OFF_Code_']

In [13]:
new_code_columns

['ROUTE_SURVEYED_Code_',
 'STLINE2_ON_Code_',
 'STLINE2_OFF_Code_',
 'SSSL_ON_Code_',
 'SSSL_OFF_Code_',
 'S1L_ON_Code_',
 'S1L_OFF_Code_',
 'STTAC_ON_Code_',
 'STTAC_OFF_Code_']

In [14]:

def get_route_line(x):
#     return x[1]
    b_values=x.split('(')
    print(b_values)
    if len(b_values)>1:
        print('ENtering in b_values_condition')
        join_value=" ".join(b_values[:-1]).strip()
        values=str(join_value).split(' ')
        return values[-2]
    else:
        print('Entering else block')
        values=x.split(' ')
        print(values)
        if len(values)>1:
            return values[-2]
        return x[1]
    
new_df['Line_Value']=new_df[route_surveyed_column[0]].apply(get_route_line)

['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST SOUNDER S LINE']
Entering else block
['ST', 'SOUNDER', 'S', 'LINE']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']
['ST 2 Line']
Entering else block
['ST', '2', 'Line']

In [15]:
a='STLINE2'

In [16]:
new_df['Line_Value'].unique()

array(['2', 'S'], dtype=object)

In [17]:
a='STLINE2'
get_route_line(a)

['STLINE2']
Entering else block
['STLINE2']

'T'

In [18]:
new_df[['Line_Value']].head()

  Line_Value
0          2
1          S
2          2
3          2
4          2

In [19]:
new_df['Line_Value'].unique()

array(['2', 'S'], dtype=object)

In [20]:

def get_detail_route_line(x):
    values=str(x).split('_')
    if len(values)>1:
        return values[-2][0]
    else:
        return x
    
seq_df['Line_Value']=seq_df['ETC_ROUTE_ID'].apply(get_detail_route_line)

In [21]:
a='SND_1_TLine_00'
get_detail_route_line(a)

'T'

In [22]:
seq_df['Line_Value'].unique()

array(['1', '2', '4', '8', 'S', 'F', '3', '6', '7', '9', '5', 'A', 'B',
       'K', 'N', 'C', 'D', 'E', 'H', 'T', 'L', 'M', 'O', 'P', 'V'],
      dtype=object)

In [23]:
code_columns[1:-2]

['STLINE2_ON_Code_',
 'STLINE2_OFF_Code_',
 'SSSL_ON_Code_',
 'SSSL_OFF_Code_',
 'S1L_ON_Code_',
 'S1L_OFF_Code_',
 'STTAC_ON_Code_',
 'STTAC_OFF_Code_']

In [24]:
new_code_columns

['ROUTE_SURVEYED_Code_',
 'STLINE2_ON_Code_',
 'STLINE2_OFF_Code_',
 'SSSL_ON_Code_',
 'SSSL_OFF_Code_',
 'S1L_ON_Code_',
 'S1L_OFF_Code_',
 'STTAC_ON_Code_',
 'STTAC_OFF_Code_']

In [25]:
required_code_columns=code_columns[:-2]
required_code_columns

['ROUTE_SURVEYED_Code_',
 'STLINE2_ON_Code_',
 'STLINE2_OFF_Code_',
 'SSSL_ON_Code_',
 'SSSL_OFF_Code_',
 'S1L_ON_Code_',
 'S1L_OFF_Code_',
 'STTAC_ON_Code_',
 'STTAC_OFF_Code_']

In [26]:

for _, row in new_df.iterrows():
    counter = 0
    for i in range(1, len(new_code_columns)):
        seq_value = row[code_columns[i]]
        value_column_check = [''.join(part for part in required_code_columns[i].split('_') if part.lower() != 'code').lower()]
        value_column = check_all_characters_present(new_df, value_column_check)
        value = row[value_column[0]]

        if pd.isnull(value) or pd.isnull(seq_value):
            continue  # Skip if value or seq_value is null

        stop_value = value

        # First, filter sequence_value using the original logic
        sequence_value = seq_df[
            (seq_df['Line_Value'] == row['Line_Value']) & 
            (seq_df['ETC_STOP_NAME'].str.lower().str.contains(value.lower()))
        ]

        # If sequence_value is empty, apply fuzzy matching
        if sequence_value.empty:
            # Use fuzzy matching to find the best match for ETC_STOP_NAME
            best_match, score, _ = process.extractOne(
                value.lower(),
                seq_df[seq_df['Line_Value'] == row['Line_Value']]['ETC_STOP_NAME'].str.lower(),
                scorer=fuzz.ratio
            )
            print(f'{best_match},{value},{score},{row["Line_Value"]}')
            # print(score,best_match,value.lower())
            # print()
            if score >= 40:
                sequence_value = seq_df[
                    (seq_df['Line_Value'] == row['Line_Value']) & 
                    (seq_df['ETC_STOP_NAME'].str.lower() == best_match)
                ]
                
        # Proceed only if we have a valid sequence_value after both methods
        if not sequence_value.empty:
            seq_values_array = sequence_value['seq_fixed'].values

            if seq_values_array.size > 0:
                differences = np.abs(seq_values_array - seq_value)
                nearest_index = np.argmin(differences)
                nearest_value = seq_values_array[nearest_index]
                matched_value = sequence_value[sequence_value['seq_fixed'] == nearest_value]

                if not matched_value.empty:
                    counter += 1
                    if counter == 1:
                        new_df.loc[row.name, ['ROUTE_DESCRIPTION[CODE]', 'ETC_ROUTE_NAME', 'BOARD_ID', 'BOARD_STOP[CODE]', 'BOARD_STOP_NAME']] = [
                            matched_value.iloc[0]['ETC_ROUTE_ID'],
                            matched_value.iloc[0]['ETC_ROUTE_NAME'],
                            matched_value.iloc[0]['seq_fixed'],
                            matched_value.iloc[0]['ETC_STOP_ID'],
                            matched_value.iloc[0]['ETC_STOP_NAME'],
                        ]
                    else:  # counter > 1
                        new_df.loc[row.name, ['ALIGHT_ID', 'ALIGHT_STOP[CODE]', 'ALIGHT_STOP_NAME']] = [
                            matched_value.iloc[0]['seq_fixed'],
                            matched_value.iloc[0]['ETC_STOP_ID'],
                            matched_value.iloc[0]['ETC_STOP_NAME'],
                        ]
            else:
                print(f"No valid seq_fixed values found for {row['Line_Value']} and {value}.")

In [27]:

new_df=pd.merge(new_df,df[['id','TIME_BOARDED_Code_']],on='id',how='left')

new_df['Date'] = np.where(new_df['Completed'].notna(), new_df['Completed'], new_df['Date_started'])

In [28]:
def get_day_name(x):
    if pd.isna(x):
        return np.nan
    x = str(x)
    try:
        date_object = datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
    except ValueError:
        try:
            date_object = datetime.strptime(x, '%d/%m/%Y %H:%M')
        except ValueError:
            return np.nan
    day_name = date_object.strftime('%A')
    if day_name in ['Saturday', 'Sunday']:
        return 'Weekend'
    return 'Weekday'

new_df['Day']=new_df['Date'].apply(get_day_name)

new_df=new_df[new_df['INTERV_INIT']!='999']

In [29]:

# time_period_mapping = {
#     'PM1': 'PM',
#     'PM2': 'Evening',
#     'MID': 'MIDDAY',
#     'AM': 'AM'
# }

# time_period_code_mapping = {
#     'PM':2,
#     'Evening':4,
#     'MIDDAY':1,
#     'AM': 0
# }

# new_df['TIME PERIOD'] = new_df['TIME_BOARDED_Code_'].map(time_period_mapping).fillna(new_df['TIME_BOARDED_Code_'])
# new_df['TIME PERIOD[Code]'] = new_df['TIME PERIOD'].map(time_period_code_mapping)

In [30]:

for _, row in new_df.iterrows():
    # Extract the alight sequence
    alight_seq_df = seq_df[(seq_df['ETC_ROUTE_NAME'] == row['ETC_ROUTE_NAME']) & 
                           (seq_df['ETC_STOP_ID'] == row['ALIGHT_STOP[CODE]'])][['seq_fixed']]
    # alight_seq_df = seq_df[(seq_df['ETC_ROUTE_NAME'] == row['ETC_ROUTE_NAME']) & 
    #                     (seq_df['ETC_STOP_NAME'] == row['ALIGHT_STOP_NAME'])][['seq_fixed']]
    # alight_seq_lat_long_df = seq_df[(seq_df['ETC_STOP_NAME'] == row['ALIGHT_STOP_NAME']) & 
    #                                 (seq_df['ETC_STOP_ID'] == row['ALIGHT_STOP[CODE]'])][['stop_lat6', 'stop_lon6']]
    alight_seq_lat_long_df = seq_df[(seq_df['ETC_ROUTE_NAME'] == row['ETC_ROUTE_NAME']) & 
                            (seq_df['ETC_STOP_NAME'] == row['ALIGHT_STOP_NAME'])][['stop_lat6', 'stop_lon6']]
    if not alight_seq_df.empty:
        alight_seq = alight_seq_df.iloc[0, 0]
    else:
        alight_seq = 0

    # Extract the board sequence
    board_seq_df = seq_df[(seq_df['ETC_ROUTE_NAME'] == row['ETC_ROUTE_NAME']) & 
                          (seq_df['ETC_STOP_ID'] == row['BOARD_STOP[CODE]'])][['seq_fixed']]
    # board_seq_df = seq_df[(seq_df['ETC_ROUTE_NAME'] == row['ETC_ROUTE_NAME']) & 
    #                     (seq_df['ETC_STOP_NAME'] == row['BOARD_STOP_NAME'])][['seq_fixed']]
    # board_seq_lat_long_df = seq_df[(seq_df['ETC_STOP_NAME'] == row['BOARD_STOP_NAME']) & 
    #                             (seq_df['ETC_STOP_ID'] == row['BOARD_STOP[CODE]'])][['stop_lat6', 'stop_lon6']]
    board_seq_lat_long_df = seq_df[(seq_df['ETC_ROUTE_NAME'] == row['ETC_ROUTE_NAME']) & 
                                   (seq_df['ETC_STOP_NAME'] == row['BOARD_STOP_NAME'])][['stop_lat6', 'stop_lon6']]
    
    if not board_seq_df.empty:
        board_seq = board_seq_df.iloc[0, 0]
    else:
        board_seq = 0

    # Assign sequence values to new_df
    new_df.loc[row.name, 'Alight_Seq'] = alight_seq
    new_df.loc[row.name, 'Board_Seq'] = board_seq

    # Assign latitude and longitude values to new_df
    if not board_seq_lat_long_df.empty:
        new_df.loc[row.name, 'BOARD_STOP_ON_LAT'] = board_seq_lat_long_df.iloc[0, 0]
        new_df.loc[row.name, 'BOARD_STOP_ON_LONG'] = board_seq_lat_long_df.iloc[0, 1]
    else:
        new_df.loc[row.name, 'BOARD_STOP_ON_LAT'] = None
        new_df.loc[row.name, 'BOARD_STOP_ON_LONG'] = None

    if not alight_seq_lat_long_df.empty:
        new_df.loc[row.name, 'ALIGHT_STOP_ON_LAT'] = alight_seq_lat_long_df.iloc[0, 0]
        new_df.loc[row.name, 'ALIGHT_STOP_ON_LONG'] = alight_seq_lat_long_df.iloc[0, 1]
    else:
        new_df.loc[row.name, 'ALIGHT_STOP_ON_LAT'] = None
        new_df.loc[row.name, 'ALIGHT_STOP_ON_LONG'] = None

new_df['SEQ_CHECK'] = new_df['Alight_Seq'] - new_df['Board_Seq']

In [31]:
new_df = new_df[new_df['SEQ_CHECK'] != 0].copy()

ids_list = []

for _, row in new_df.iterrows():
    if row['SEQ_CHECK'] < 0:
        # Extract route code and modify it
        ids_list.append(row['id'])

        route_code = row['ROUTE_DESCRIPTION[CODE]']
        new_route_code = f"{'_'.join(route_code.split('_')[:-1])}_01" if route_code.split('_')[-1] == '00' else f"{'_'.join(route_code.split('_')[:-1])}_00"
        
        # Get new route name
        new_route_name_row = seq_df[seq_df['ETC_ROUTE_ID'] == new_route_code]
        if not new_route_name_row.empty:
            new_route_name = new_route_name_row['ETC_ROUTE_NAME'].iloc[0]
        else:
            # Handle the case when the new route name is not found
            continue  # Skip to the next iteration if new route code is not valid

        # Board stop details
        board_stop_row = seq_df[(seq_df['ETC_ROUTE_ID'] == new_route_code) & (seq_df['ETC_STOP_NAME'] == row['BOARD_STOP_NAME'])]
        if not board_stop_row.empty:
            board_stop_code = board_stop_row['ETC_STOP_ID'].iloc[0]
            board_stop_lat_lon = board_stop_row[['seq_fixed', 'stop_lat6', 'stop_lon6']].iloc[0]
        else:
            # Skip if no board stop information is found
            continue

        # Alight stop details
        alight_stop_row = seq_df[(seq_df['ETC_ROUTE_ID'] == new_route_code) & (seq_df['ETC_STOP_NAME'] == row['ALIGHT_STOP_NAME'])]
        if not alight_stop_row.empty:
            alight_stop_code = alight_stop_row['ETC_STOP_ID'].iloc[0]
            alight_stop_lat_lon = alight_stop_row[['seq_fixed', 'stop_lat6', 'stop_lon6']].iloc[0]
        else:
            # Skip if no alight stop information is found
            continue

        # Update new_df with the retrieved values
        new_df.loc[row.name, 'ROUTE_DESCRIPTION[CODE]'] = new_route_code
        new_df.loc[row.name, 'ETC_ROUTE_NAME'] = new_route_name

        new_df.loc[row.name, 'Board_Seq'] = board_stop_lat_lon['seq_fixed']
        new_df.loc[row.name, 'BOARD_STOP[CODE]'] = board_stop_code

        new_df.loc[row.name, 'BOARD_STOP_ON_LAT'] = board_stop_lat_lon['stop_lat6']
        new_df.loc[row.name, 'BOARD_STOP_ON_LONG'] = board_stop_lat_lon['stop_lon6']

        new_df.loc[row.name, 'Alight_Seq'] = alight_stop_lat_lon['seq_fixed']
        new_df.loc[row.name, 'ALIGHT_STOP[CODE]'] = alight_stop_code

        new_df.loc[row.name, 'ALIGHT_STOP_ON_LAT'] = alight_stop_lat_lon['stop_lat6']
        new_df.loc[row.name, 'ALIGHT_STOP_ON_LONG'] = alight_stop_lat_lon['stop_lon6']

In [32]:
final_df=new_df[['id','Date','Day','TIME_BOARDED','ROUTE_DESCRIPTION[CODE]','ETC_ROUTE_NAME','Line_Value','BOARD_STOP[CODE]','Board_Seq' ,'BOARD_STOP_NAME','BOARD_STOP_ON_LAT','BOARD_STOP_ON_LONG','ALIGHT_STOP[CODE]','Alight_Seq' ,'ALIGHT_STOP_NAME','ALIGHT_STOP_ON_LAT','ALIGHT_STOP_ON_LONG']]

In [33]:
# final_df.to_csv('SEATTLE_NEW_O2O.csv',index=False)

In [34]:
final_df.head()

,id,Date,Day,TIME_BOARDED,ROUTE_DESCRIPTION[CODE],ETC_ROUTE_NAME,Line_Value,BOARD_STOP[CODE],Board_Seq,BOARD_STOP_NAME,BOARD_STOP_ON_LAT,BOARD_STOP_ON_LONG,ALIGHT_STOP[CODE],Alight_Seq,ALIGHT_STOP_NAME,ALIGHT_STOP_ON_LAT,ALIGHT_STOP_ON_LONG
2,105546,2024-10-07 08:05:52,Weekday,AM Peak (Before 9:00am),MET_1_249_00,MET_1_249_00,2,MET_1_249_00_84264,1.0,South Bellevue Station Bus Plaza - Bay 2,47.586960,-122.190590,SND_1_2Line_00_E15-T2,0.0,Bellevue Downtown,None,None
3,105547,2024-10-07 08:08:37,Weekday,AM Peak (Before 9:00am),MET_1_249_00,MET_1_249_00,2,MET_1_249_00_84264,1.0,South Bellevue Station Bus Plaza - Bay 2,47.586960,-122.190590,SND_1_2Line_00_E15-T2,0.0,Bellevue Downtown,None,None
4,105548,2024-10-07 08:08:48,Weekday,AM Peak (Before 9:00am),MET_1_249_00,MET_1_249_00,2,MET_1_249_00_84264,1.0,South Bellevue Station Bus Plaza - Bay 2,47.586960,-122.190590,SND_1_2Line_00_E15-T2,0.0,Bellevue Downtown,None,None
5,105549,2024-10-07 08:09:10,Weekday,AM Peak (Before 9:00am),SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2,SND_1_2Line_00_E15-T2,3.0,Bellevue Downtown,47.615183,-122.191303,SND_1_2Line_00_E21-T2,5.0,Spring District,47.623776,-122.178239
6,105550,2024-10-07 08:09:25,Weekday,AM Peak (Before 9:00am),SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2,SND_1_2Line_00_E15-T2,3.0,Bellevue Downtown,47.615183,-122.191303,SND_1_2Line_00_E21-T2,5.0,Spring District,47.623776,-122.178239