In [1]:
import pandas as pd
import numpy as np
from datetime import datetime,date
import warnings
import copy

warnings.filterwarnings('ignore')

In [2]:
file_name='DENVER_OB_KINGElvis (4).xlsx'
# df=pd.read_csv('elvisdenverco2024obweekday_export_odbc (2).csv')
elvis_df=pd.read_excel(file_name,sheet_name='Elvis_Review')

In [3]:
elvis_df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO
0,2024-08-23,11423,Test,Test/No 5 MIN,Remove,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-08-23,11424,Test,Test/No 5 MIN,Remove,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-08-23,11425,Test,Test/No 5 MIN,Remove,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-08-23,11427,Test,Test/No 5 MIN,Remove,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-08-23,11634,HereAPI,Kesar,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
elvis_df=elvis_df.query("`1st Cleaner` == 'HereAPI'")

In [5]:
removed_df=elvis_df.query('Final_Usage=="Remove"')

In [6]:
removed_df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO
241,2024-08-23,12328,HereAPI,T A Divya,Remove,NaN,Use of Transit not necessary,Elvis_Review,Elvis_Review,o=d,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
272,2024-08-23,12382,HereAPI,T A Divya,Remove,NaN,O=D,Elvis_Review,Elvis_Review,O = D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,2024-08-23,12400,HereAPI,Saurav,Remove,NaN,Use of Transit not necessary,Elvis_Review,Elvis_Review,Trip isn't logical,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,2024-08-23,12538,HereAPI,Kashish,Remove,NaN,Greater than 50 Miles,Elvis_Review,Elvis_Review,o=airport//a=Union Station Track 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
383,2024-08-23,12569,HereAPI,Kashish,Remove,NaN,B=A,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
removed_df.columns

Index(['Elvis_Date', 'elvis_id', '1st Cleaner', 'FINAL_REVIEWER',
       'Final_Usage', 'REASON FOR REMOVAL', 'REASON FOR REMOVAL [Other]',
       'route_match_flag', 'distance_flag', 'SUPERVISOR_COMMENT', 'id',
       'Completed', 'INTERV_INIT', 'ROUTE_SURVEYEDCode', 'ROUTE_SURVEYED',
       'HAVE_5_MIN_FOR_SURVECode', 'HAVE_5_MIN_FOR_SURVE', 'ORIGIN_PLACE_TYPE',
       'ORIGIN_TRANSPORTCode', 'ORIGIN_TRANSPORT', 'DESTIN_PLACE_TYPE',
       'DESTIN_TRANSPORTCode', 'DESTIN_TRANSPORT', '_INTRV_NOTE',
       'ELVIS_STATUS', 'ELVIS_COMMENT', 'ROUTE_STATUS', 'Stops_Status',
       'Test_Status', 'Traditional_Check', 'OD_Distance_Check',
       'Transfer_Distance_Check', '2X_REVIEW_CHECK', '2X_REVIEW_CHECK.1',
       '2x_REVIEWED_BY', '2x_REVIEWED_FLAG', 'ADMIN_APPROVED',
       'SURVEY_RECOVERY', 'SURVEY_RECOVERY_REVIEWED_BY', 'Recovery Check',
       '2x_REVIEWED_BY.1', '2x_REVIEWED_FLAG.1', 'ADMIN_APPROVED.1',
       'RECORD_INFO'],
      dtype='object')

In [8]:
removed_df[['SUPERVISOR_COMMENT']]

                       SUPERVISOR_COMMENT
241                                   o=d
272                                O = D
286                    Trip isn't logical
361    o=airport//a=Union Station Track 1
383                                   NaN
...                                   ...
21809                                 NaN
22457                                 NaN
22495                                 NaN
22550                                 NaN
22877                                 NaN

[397 rows x 1 columns]

In [9]:
filtered_df = removed_df[removed_df['SUPERVISOR_COMMENT'].notna() & (removed_df['SUPERVISOR_COMMENT'] != '')]


filtered_df[['Elvis_Date','elvis_id','1st Cleaner','SUPERVISOR_COMMENT','FINAL_REVIEWER']]

,Elvis_Date,elvis_id,1st Cleaner,SUPERVISOR_COMMENT,FINAL_REVIEWER
241,2024-08-23,12328,HereAPI,o=d,T A Divya
272,2024-08-23,12382,HereAPI,O = D,T A Divya
286,2024-08-23,12400,HereAPI,Trip isn't logical,Saurav
361,2024-08-23,12538,HereAPI,o=airport//a=Union Station Track 1,Kashish
390,2024-08-23,12577,HereAPI,Surveyor confirmed D = 2301 Blake St Suit 100 ...,Kashish
...,...,...,...,...,...
20804,2024-10-25,43727,HereAPI,POSSIBLE FRADULENT SURVEY,Vilas
20805,2024-10-25,43728,HereAPI,POSSIBLE FRADULENT SURVEY,Vilas
20806,2024-10-25,43729,HereAPI,POSSIBLE FRADULENT SURVEY,Vilas
20808,2024-10-25,43732,HereAPI,POSSIBLE FRADULENT SURVEY,Vilas
20811,2024-10-25,43736,HereAPI,POSSIBLE FRADULENT SURVEY,Vilas

In [12]:
filtered_df.to_csv('BUFFALO_Supervisor_Comment_Review.csv',index=False)

In [11]:
filtered_df[['SUPERVISOR_COMMENT']].shape

(89, 1)