In [1]:
import pandas as pd
from math import sin, cos, sqrt, atan2, radians
from concurrent.futures import ThreadPoolExecutor
import os
import numpy as np
from datetime import date
import warnings

warnings.filterwarnings("ignore")

In [2]:

def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [3]:

today_date = date.today()
today_date=''.join(str(today_date).split('-'))

project_name='ANCHORAGE'

file_name='ANCHORAGE_AK_KINGElvis.xlsx'
detail_df=pd.read_excel("details_anchorage_ak_od_excel (2).xlsx",sheet_name='STOPS')
df=pd.read_csv('elvisanchorageak2024obweekday_export_odbc(new).csv')
elvis_df=pd.read_excel(file_name,sheet_name='Elvis_Review')

In [4]:
if file_name.split('_')[0].isdigit():
    file_first_name=file_name.split('_')[0]+'_'+file_name.split('_')[1]
else:
    file_first_name=file_name.split('_')[0]

elvis_date_check=['elvisdate']
elvis_date=check_all_characters_present(elvis_df,elvis_date_check)

# df = df.merge(elvis_df[['elvis_date', 'id', 'Final_Usage']], on='id', how='left')
df = df.merge(elvis_df[[elvis_date[0], 'id', 'Final_Usage','FINAL_REVIEWER']], on='id', how='left')

In [5]:
df=df[df['ELVIS_STATUS'].str.lower()!='delete']

df=df[df['Final_Usage'].str.lower()=='use']

In [6]:
duplicate_records_checks=['routesurveyedcode','prevtran1onbuslat', 'prevtran1onbuslong',
                  'prevtran1offbuslat', 'prevtran1offbuslong', 'prevtran2onbuslat', 
                  'prevtran2onbuslong', 'prevtran2offbuslat', 'prevtran2offbuslong',
                  'prevtran3onbuslat', 'prevtran3onbuslong', 'prevtran3offbuslat',
                  'prevtran3offbuslong', 'prevtran4onbuslat', 'prevtran4onbuslong', 
                  'prevtran4offbuslat', 'prevtran4offbuslong','nexttran1onbuslat',
                  'nexttran1onbuslong', 'nexttran1offbuslat', 'nexttran1offbuslong', 
                  'nexttran2onbuslat', 
                  'nexttran2onbuslong', 'nexttran2offbuslat', 'nexttran2offbuslong', 
                  'nexttran3onbuslat', 'nexttran3onbuslong',
                  'nexttran3offbuslat', 'nexttran3offbuslong', 'nexttran4onbuslat', 'nexttran4onbuslong',
                  'nexttran4offbuslat', 'nexttran4offbuslong']
duplicate_columns=check_all_characters_present(df,duplicate_records_checks)
duplicates = df.drop_duplicates(subset=duplicate_columns)

In [9]:
# duplicates

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,_REVERSE_TRIP,GENERATABLE_TRIPS,Elvis_Date,Final_Usage,FINAL_REVIEWER
5,12228,2024-09-03 06:59:03,74,en,2024-09-03 06:21:16,2024-09-16 00:46:59,172.58.139.14,https://anchorage-ak-od.etc-research.com/,-28800,LSS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45548,Use,Priyanka
6,12230,2024-09-03 07:07:39,74,en,2024-09-03 07:00:33,2024-09-16 00:47:27,172.58.30.161,https://anchorage-ak-od.etc-research.com/,-28800,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45548,Use,Priyanka
8,12234,2024-09-03 07:18:58,74,en,2024-09-03 07:13:36,2024-09-16 00:52:27,172.58.30.161,https://anchorage-ak-od.etc-research.com/index...,-28800,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45548,Use,Priyanka
10,12238,2024-09-03 07:33:07,74,en,2024-09-03 07:24:31,2024-09-16 00:53:21,172.58.30.161,https://anchorage-ak-od.etc-research.com/,-28800,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45548,Use,Priyanka
11,12243,2024-09-03 07:35:40,74,en,2024-09-03 07:28:50,2024-09-16 00:53:49,172.58.139.14,https://anchorage-ak-od.etc-research.com/,-28800,LSS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45548,Use,Priyanka
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2008,14977,2024-09-26 16:27:22,75,en,2024-09-26 16:21:35,2024-09-26 16:27:22,172.58.27.133,https://anchorage-ak-od.etc-research.com/index...,-28800,LSS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-27 00:00:00,Use,Aditya
2010,14981,2024-09-26 17:15:32,75,en,2024-09-26 17:09:16,2024-09-30 03:13:05,172.58.27.133,https://anchorage-ak-od.etc-research.com/index...,-28800,LSS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-27 00:00:00,Use,Aditya
2011,14982,2024-09-26 17:26:42,75,en,2024-09-26 17:15:35,2024-09-30 03:13:55,172.58.27.133,https://anchorage-ak-od.etc-research.com/index...,-28800,LSS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-27 00:00:00,Use,Aditya
2013,14985,2024-09-26 18:05:16,75,en,2024-09-26 17:32:36,2024-09-26 18:05:16,172.58.27.133,https://anchorage-ak-od.etc-research.com/,-28800,LSS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-27 00:00:00,Use,Aditya
2018,14990,2024-09-26 18:31:16,75,en,2024-09-26 18:23:42,2024-09-30 03:17:01,172.58.111.229,https://anchorage-ak-od.etc-research.com/index...,-28800,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-27 00:00:00,Use,Aditya

In [10]:
prev_transfer_codes=['prevtransferscode','tripfirstroutecode','tripsecondroutecode','tripthirdroutecode','tripfourthroutecode']
next_transfer_codes=['nexttransferscode','tripnextroutecode','tripafterroutecode','trip3rdroutecode','triplast4thrtecode']
prev_transfer_columns=check_all_characters_present(df,prev_transfer_codes)
next_transfer_columns=check_all_characters_present(df,next_transfer_codes)
prev_transfer_columns,next_transfer_columns

(['PREV_TRANSFERSCode',
  'TRIP_FIRST_ROUTECode',
  'TRIP_SECOND_ROUTECode',
  'TRIP_THIRD_ROUTECode',
  'TRIP_FOURTH_ROUTECode'],
 ['NEXT_TRANSFERSCode',
  'TRIP_NEXT_ROUTECode',
  'TRIP_AFTER_ROUTECode',
  'TRIP_3RD_ROUTECode',
  'TRIP_LAST4TH_RTECode'])

In [11]:
prev_df=df.loc[:,prev_transfer_columns]
next_df=df.loc[:,next_transfer_columns]
prev_df_list=prev_df.values.tolist()
next_df_list=next_df.values.tolist()

In [13]:
def transfer_route_check(df,prev_df_list,next_df_list):
    # Assuming both lists have the same length
    status=[]
    for i in range(len(prev_df_list)):
        prev_data = prev_df_list[i]
        next_data = next_df_list[i]
        prev_count = sum(1 for j in range(1, len(prev_data)) if not pd.isna(prev_data[j]))
        next_count = sum(1 for j in range(1, len(next_data)) if not pd.isna(next_data[j]))
        if prev_count == prev_data[0] and next_count == next_data[0]:
            status.append(0)            
        else:
            status.append(1)
    return status
status_transfers=transfer_route_check(df,prev_df_list,next_df_list)

df['Status']=status_transfers

In [15]:
df[df['Status']==1][['Status']]

     Status
853       1
906       1
910       1
919       1
921       1
925       1
926       1
928       1
931       1
937       1
939       1
940       1

In [17]:
desired_columns = [elvis_date[0], 'Final_Usage', 'id']
missing_columns = [col for col in desired_columns if col not in df.columns]
if missing_columns:
    raise ValueError(f"Columns {missing_columns} do not exist in df1.")

# Reorder the columns to make them first
df = df[desired_columns + [col for col in df.columns if col not in desired_columns]]

In [18]:
def split_etc_route_id(value):
    value_list = value.split('_')
    etc_id = '_'.join(value_list[:-1])
    return etc_id

In [20]:
stops_columns_to_check=['stoplat','stoplon','etcrouteid']
stops_columns=check_all_characters_present(detail_df,stops_columns_to_check)
stops_columns

['stop_lat', 'stop_lon', 'ETC_ROUTE_ID']

In [28]:
stops_df=detail_df.loc[:,stops_columns]
stops_df_list=stops_df.values.tolist()
stops_df_list[-5:]

[[61.217631, -149.871757, 'ANC_1_92_01'],
 [61.217672, -149.882007, 'ANC_1_92_01'],
 [61.217663, -149.886447, 'ANC_1_92_01'],
 [61.217603, -149.893845, 'ANC_1_92_01'],
 [61.216553, -149.896763, 'ANC_1_92_01']]

In [27]:
# Reverse the list
rev_stops_df_list = stops_df_list[::-1]
rev_stops_df_list[:5]

[[61.216553, -149.896763, 'ANC_1_92_01'],
 [61.217603, -149.893845, 'ANC_1_92_01'],
 [61.217663, -149.886447, 'ANC_1_92_01'],
 [61.217672, -149.882007, 'ANC_1_92_01'],
 [61.217631, -149.871757, 'ANC_1_92_01']]

In [29]:

from concurrent.futures import ThreadPoolExecutor
from math import radians, sin, cos, sqrt, atan2

# Approximate radius of earth in km
R = 6373.0

def get_distance_between_coordinates(start_lat, start_lng, end_lat, end_lng):
    lat1 = radians(start_lat)
    lon1 = radians(start_lng)
    lat2 = radians(end_lat)
    lon2 = radians(end_lng)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance_km = R * c
    distance_in_miles = distance_km * 0.621371  # Convert km to miles
    return distance_in_miles

In [37]:

def calculate_distance_for_pair(args):
    i, stops_df_list, success_list = args
    results = []
    for j in range(len(stops_df_list)):
        if str(stops_df_list[i][-1]).split('_')[-1] != str(stops_df_list[j][-1]).split('_')[-1]:
            if str(stops_df_list[i][-1]).split('_')[-2] != str(stops_df_list[j][-1]).split('_')[-2] and f'{stops_df_list[i][-1]} to {stops_df_list[j][-1]}' not in success_list:
                distance = get_distance_between_coordinates(
                    stops_df_list[i][0], stops_df_list[i][1], stops_df_list[j][0], stops_df_list[j][1])
                if distance <= 0.25:
                    success_list.append(f'{stops_df_list[i][-1]} to {stops_df_list[j][-1]}')
                    splited_list1 = stops_df_list[i][-1].split('_')
                    splited_value1 = '_'.join(splited_list1[:-1])
                    splited_list = stops_df_list[j][-1].split('_')
                    splited_value = '_'.join(splited_list[:-1])
                    result = f'{splited_value1}>>{splited_value}\n'
                    results.append(result)
    return results

def calculate_and_print_distance(stops_df_list):
    results = []  # Initialize a list to store the results
    success_list = []

    # Create a list of tasks
    tasks = [(i, stops_df_list, success_list) for i in range(len(stops_df_list))]

    # Use ThreadPoolExecutor to run tasks in parallel
    with ThreadPoolExecutor() as executor:
        thread_results = list(executor.map(calculate_distance_for_pair, tasks))

    # Flatten the results
    for res in thread_results:
        results.extend(res)

    return results

In [38]:
results = calculate_and_print_distance(stops_df_list)
final_text = ''.join(results)

In [32]:
reverse_results = calculate_and_print_distance(rev_stops_df_list)
final_reverse_text = ''.join(reverse_results)

In [35]:
# final_text+'\n'+final_reverse_text

'ANC_1_10>>ANC_1_11\nANC_1_10>>ANC_1_20\nANC_1_10>>ANC_1_25\nANC_1_10>>ANC_1_30\nANC_1_10>>ANC_1_35\nANC_1_10>>ANC_1_40\nANC_1_10>>ANC_1_41\nANC_1_10>>ANC_1_85\nANC_1_10>>ANC_1_92\nANC_1_10>>ANC_1_55\nANC_1_10>>ANC_1_31\nANC_1_10>>ANC_1_51\nANC_1_20>>ANC_1_10\nANC_1_20>>ANC_1_11\nANC_1_20>>ANC_1_25\nANC_1_20>>ANC_1_30\nANC_1_20>>ANC_1_35\nANC_1_20>>ANC_1_40\nANC_1_20>>ANC_1_41\nANC_1_20>>ANC_1_85\nANC_1_20>>ANC_1_92\nANC_1_20>>ANC_1_31\nANC_1_20>>ANC_1_55\nANC_1_25>>ANC_1_10\nANC_1_25>>ANC_1_11\nANC_1_25>>ANC_1_20\nANC_1_25>>ANC_1_30\nANC_1_25>>ANC_1_35\nANC_1_25>>ANC_1_40\nANC_1_25>>ANC_1_41\nANC_1_25>>ANC_1_85\nANC_1_25>>ANC_1_92\nANC_1_25>>ANC_1_55\nANC_1_25>>ANC_1_31\nANC_1_25>>ANC_1_51\nANC_1_30>>ANC_1_10\nANC_1_30>>ANC_1_11\nANC_1_30>>ANC_1_20\nANC_1_30>>ANC_1_25\nANC_1_30>>ANC_1_35\nANC_1_30>>ANC_1_40\nANC_1_30>>ANC_1_41\nANC_1_30>>ANC_1_85\nANC_1_30>>ANC_1_92\nANC_1_30>>ANC_1_31\nANC_1_30>>ANC_1_51\nANC_1_35>>ANC_1_10\nANC_1_35>>ANC_1_11\nANC_1_35>>ANC_1_20\nANC_1_35>>ANC_1_25\nANC_1_35>>ANC_1_30\nANC_1_35>>ANC_1_40\nANC_1_35>>ANC_1_41\nANC_1_35>>ANC_1_85\nANC_1_35>>ANC_1_92\nANC_1_35>>ANC_1_65\nANC_1_35>>ANC_1_55\nANC_1_55>>ANC_1_35\nANC_1_55>>ANC_1_65\nANC_1_55>>ANC_1_85\nANC_1_55>>ANC_1_25\nANC_1_55>>ANC_1_10\nANC_1_55>>ANC_1_20\nANC_1_85>>ANC_1_10\nANC_1_85>>ANC_1_11\nANC_1_85>>ANC_1_20\nANC_1_85>>ANC_1_25\nANC_1_85>>ANC_1_30\nANC_1_85>>ANC_1_35\nANC_1_85>>ANC_1_40\nANC_1_85>>ANC_1_41\nANC_1_85>>ANC_1_92\nANC_1_85>>ANC_1_55\nANC_1_85>>ANC_1_65\nANC_1_92>>ANC_1_10\nANC_1_92>>ANC_1_11\nANC_1_92>>ANC_1_20\nANC_1_92>>ANC_1_25\nANC_1_92>>ANC_1_30\nANC_1_92>>ANC_1_35\nANC_1_92>>ANC_1_40\nANC_1_92>>ANC_1_41\nANC_1_92>>ANC_1_85\nANC_1_92>>ANC_1_31\n\nANC_1_92>>ANC_1_25\nANC_1_92>>ANC_1_31\nANC_1_92>>ANC_1_20\nANC_1_92>>ANC_1_11\nANC_1_92>>ANC_1_41\nANC_1_92>>ANC_1_40\nANC_1_92>>ANC_1_30\nANC_1_92>>ANC_1_85\nANC_1_92>>ANC_1_35\nANC_1_92>>ANC_1_10\nANC_1_85>>ANC_1_55\nANC_1_85>>ANC_1_65\nANC_1_85>>ANC_1_35\nANC_1_85>>ANC_1_25\nANC_1_85>>ANC_1_40\nANC_1_85>>ANC_1_10\nANC_1_85>>ANC_1_30\nANC_1_85>>ANC_1_92\nANC_1_85>>ANC_1_41\nANC_1_85>>ANC_1_20\nANC_1_85>>ANC_1_11\nANC_1_55>>ANC_1_25\nANC_1_55>>ANC_1_20\nANC_1_55>>ANC_1_10\nANC_1_55>>ANC_1_85\nANC_1_55>>ANC_1_65\nANC_1_55>>ANC_1_35\nANC_1_35>>ANC_1_85\nANC_1_35>>ANC_1_65\nANC_1_35>>ANC_1_55\nANC_1_35>>ANC_1_40\nANC_1_35>>ANC_1_10\nANC_1_35>>ANC_1_30\nANC_1_35>>ANC_1_20\nANC_1_35>>ANC_1_11\nANC_1_35>>ANC_1_41\nANC_1_35>>ANC_1_25\nANC_1_35>>ANC_1_92\nANC_1_30>>ANC_1_51\nANC_1_30>>ANC_1_31\nANC_1_30>>ANC_1_25\nANC_1_30>>ANC_1_10\nANC_1_30>>ANC_1_11\nANC_1_30>>ANC_1_92\nANC_1_30>>ANC_1_41\nANC_1_30>>ANC_1_20\nANC_1_30>>ANC_1_40\nANC_1_30>>ANC_1_85\nANC_1_30>>ANC_1_35\nANC_1_25>>ANC_1_92\nANC_1_25>>ANC_1_51\nANC_1_25>>ANC_1_31\nANC_1_25>>ANC_1_30\nANC_1_25>>ANC_1_10\nANC_1_25>>ANC_1_55\nANC_1_25>>ANC_1_20\nANC_1_25>>ANC_1_85\nANC_1_25>>ANC_1_35\nANC_1_25>>ANC_1_40\nANC_1_25>>ANC_1_11\nANC_1_25>>ANC_1_41\nANC_1_20>>ANC_1_55\nANC_1_20>>ANC_1_25\nANC_1_20>>ANC_1_10\nANC_1_20>>ANC_1_31\nANC_1_20>>ANC_1_30\nANC_1_20>>ANC_1_92\nANC_1_20>>ANC_1_41\nANC_1_20>>ANC_1_11\nANC_1_20>>ANC_1_40\nANC_1_20>>ANC_1_85\nANC_1_20>>ANC_1_35\nANC_1_10>>ANC_1_51\nANC_1_10>>ANC_1_31\nANC_1_10>>ANC_1_30\nANC_1_10>>ANC_1_25\nANC_1_10>>ANC_1_20\nANC_1_10>>ANC_1_55\nANC_1_10>>ANC_1_35\nANC_1_10>>ANC_1_40\nANC_1_10>>ANC_1_85\nANC_1_10>>ANC_1_92\nANC_1_10>>ANC_1_41\nANC_1_10>>ANC_1_11\n'

In [42]:
final_text

'ANC_1_10>>ANC_1_11\nANC_1_10>>ANC_1_20\nANC_1_10>>ANC_1_25\nANC_1_10>>ANC_1_30\nANC_1_10>>ANC_1_35\nANC_1_10>>ANC_1_40\nANC_1_10>>ANC_1_41\nANC_1_10>>ANC_1_85\nANC_1_10>>ANC_1_92\nANC_1_10>>ANC_1_55\nANC_1_10>>ANC_1_31\nANC_1_10>>ANC_1_51\nANC_1_10>>ANC_1_25\nANC_1_10>>ANC_1_30\nANC_1_10>>ANC_1_20\nANC_1_10>>ANC_1_55\nANC_1_10>>ANC_1_35\nANC_1_10>>ANC_1_85\nANC_1_10>>ANC_1_92\nANC_1_11>>ANC_1_10\nANC_1_11>>ANC_1_20\nANC_1_11>>ANC_1_25\nANC_1_11>>ANC_1_30\nANC_1_11>>ANC_1_35\nANC_1_11>>ANC_1_85\nANC_1_11>>ANC_1_92\nANC_1_20>>ANC_1_10\nANC_1_20>>ANC_1_11\nANC_1_20>>ANC_1_25\nANC_1_20>>ANC_1_30\nANC_1_20>>ANC_1_35\nANC_1_20>>ANC_1_40\nANC_1_20>>ANC_1_41\nANC_1_20>>ANC_1_85\nANC_1_20>>ANC_1_92\nANC_1_20>>ANC_1_31\nANC_1_20>>ANC_1_55\nANC_1_20>>ANC_1_25\nANC_1_20>>ANC_1_55\nANC_1_20>>ANC_1_10\nANC_1_20>>ANC_1_30\nANC_1_20>>ANC_1_92\nANC_1_20>>ANC_1_35\nANC_1_20>>ANC_1_85\nANC_1_25>>ANC_1_10\nANC_1_25>>ANC_1_11\nANC_1_25>>ANC_1_20\nANC_1_25>>ANC_1_30\nANC_1_25>>ANC_1_35\nANC_1_25>>ANC_1_40\nANC_1_25>>ANC_1_41\nANC_1_25>>ANC_1_85\nANC_1_25>>ANC_1_92\nANC_1_25>>ANC_1_55\nANC_1_25>>ANC_1_31\nANC_1_25>>ANC_1_51\nANC_1_25>>ANC_1_92\nANC_1_25>>ANC_1_10\nANC_1_25>>ANC_1_30\nANC_1_25>>ANC_1_20\nANC_1_25>>ANC_1_55\nANC_1_25>>ANC_1_85\nANC_1_25>>ANC_1_35\nANC_1_30>>ANC_1_10\nANC_1_30>>ANC_1_11\nANC_1_30>>ANC_1_35\nANC_1_30>>ANC_1_85\nANC_1_30>>ANC_1_20\nANC_1_30>>ANC_1_25\nANC_1_30>>ANC_1_40\nANC_1_30>>ANC_1_41\nANC_1_30>>ANC_1_92\nANC_1_30>>ANC_1_31\nANC_1_30>>ANC_1_51\nANC_1_30>>ANC_1_10\nANC_1_30>>ANC_1_25\nANC_1_30>>ANC_1_20\nANC_1_30>>ANC_1_35\nANC_1_30>>ANC_1_85\nANC_1_30>>ANC_1_92\nANC_1_31>>ANC_1_10\nANC_1_31>>ANC_1_25\nANC_1_31>>ANC_1_30\nANC_1_31>>ANC_1_20\nANC_1_31>>ANC_1_92\nANC_1_35>>ANC_1_10\nANC_1_35>>ANC_1_11\nANC_1_35>>ANC_1_20\nANC_1_35>>ANC_1_25\nANC_1_35>>ANC_1_30\nANC_1_35>>ANC_1_40\nANC_1_35>>ANC_1_41\nANC_1_35>>ANC_1_85\nANC_1_35>>ANC_1_92\nANC_1_35>>ANC_1_65\nANC_1_35>>ANC_1_55\nANC_1_35>>ANC_1_55\nANC_1_35>>ANC_1_85\nANC_1_35>>ANC_1_10\nANC_1_35>>ANC_1_25\nANC_1_35>>ANC_1_20\nANC_1_35>>ANC_1_30\nANC_1_35>>ANC_1_92\nANC_1_40>>ANC_1_85\nANC_1_40>>ANC_1_10\nANC_1_40>>ANC_1_35\nANC_1_40>>ANC_1_20\nANC_1_40>>ANC_1_25\nANC_1_40>>ANC_1_30\nANC_1_40>>ANC_1_92\nANC_1_41>>ANC_1_10\nANC_1_41>>ANC_1_20\nANC_1_41>>ANC_1_25\nANC_1_41>>ANC_1_30\nANC_1_41>>ANC_1_35\nANC_1_41>>ANC_1_85\nANC_1_41>>ANC_1_92\nANC_1_51>>ANC_1_10\nANC_1_51>>ANC_1_25\nANC_1_51>>ANC_1_30\nANC_1_55>>ANC_1_35\nANC_1_55>>ANC_1_65\nANC_1_55>>ANC_1_85\nANC_1_55>>ANC_1_25\nANC_1_55>>ANC_1_10\nANC_1_55>>ANC_1_20\nANC_1_55>>ANC_1_20\nANC_1_55>>ANC_1_25\nANC_1_55>>ANC_1_10\nANC_1_55>>ANC_1_85\nANC_1_55>>ANC_1_35\nANC_1_65>>ANC_1_35\nANC_1_65>>ANC_1_55\nANC_1_65>>ANC_1_85\nANC_1_85>>ANC_1_10\nANC_1_85>>ANC_1_11\nANC_1_85>>ANC_1_20\nANC_1_85>>ANC_1_25\nANC_1_85>>ANC_1_30\nANC_1_85>>ANC_1_35\nANC_1_85>>ANC_1_40\nANC_1_85>>ANC_1_41\nANC_1_85>>ANC_1_92\nANC_1_85>>ANC_1_55\nANC_1_85>>ANC_1_65\nANC_1_85>>ANC_1_35\nANC_1_85>>ANC_1_55\nANC_1_85>>ANC_1_25\nANC_1_85>>ANC_1_10\nANC_1_85>>ANC_1_20\nANC_1_85>>ANC_1_30\nANC_1_85>>ANC_1_92\nANC_1_92>>ANC_1_10\nANC_1_92>>ANC_1_11\nANC_1_92>>ANC_1_20\nANC_1_92>>ANC_1_25\nANC_1_92>>ANC_1_30\nANC_1_92>>ANC_1_35\nANC_1_92>>ANC_1_40\nANC_1_92>>ANC_1_41\nANC_1_92>>ANC_1_85\nANC_1_92>>ANC_1_31\nANC_1_92>>ANC_1_25\nANC_1_92>>ANC_1_20\nANC_1_92>>ANC_1_30\nANC_1_92>>ANC_1_10\nANC_1_92>>ANC_1_35\nANC_1_92>>ANC_1_85\n'

In [39]:
with open(f'Final_distances_success.txt', 'w') as file:
    file.write(final_text)

In [45]:
# Split the lines into a list
lines = final_reverse_text.splitlines()

# Create a set of unique pairs
pairs = set(lines)

# Check for missing reverse pairs
missing_reverse_pairs = set()

for pair in pairs:
    # Split the pair into the two values
    a, b = pair.split(">>")
    
    # Check if the reverse pair exists
    reverse_pair = f"{b}>>{a}"
    if reverse_pair not in pairs:
        missing_reverse_pairs.add(reverse_pair)

# Add missing reverse pairs to the original set
pairs.update(missing_reverse_pairs)

# Convert the set back to a list and sort it
sorted_pairs = sorted(list(pairs))

# Print the sorted pairs
for pair in sorted_pairs:
    print(pair)

ANC_1_10>>ANC_1_11
ANC_1_10>>ANC_1_20
ANC_1_10>>ANC_1_25
ANC_1_10>>ANC_1_30
ANC_1_10>>ANC_1_31
ANC_1_10>>ANC_1_35
ANC_1_10>>ANC_1_40
ANC_1_10>>ANC_1_41
ANC_1_10>>ANC_1_51
ANC_1_10>>ANC_1_55
ANC_1_10>>ANC_1_85
ANC_1_10>>ANC_1_92
ANC_1_11>>ANC_1_10
ANC_1_11>>ANC_1_20
ANC_1_11>>ANC_1_25
ANC_1_11>>ANC_1_30
ANC_1_11>>ANC_1_35
ANC_1_11>>ANC_1_85
ANC_1_11>>ANC_1_92
ANC_1_20>>ANC_1_10
ANC_1_20>>ANC_1_11
ANC_1_20>>ANC_1_25
ANC_1_20>>ANC_1_30
ANC_1_20>>ANC_1_31
ANC_1_20>>ANC_1_35
ANC_1_20>>ANC_1_40
ANC_1_20>>ANC_1_41
ANC_1_20>>ANC_1_55
ANC_1_20>>ANC_1_85
ANC_1_20>>ANC_1_92
ANC_1_25>>ANC_1_10
ANC_1_25>>ANC_1_11
ANC_1_25>>ANC_1_20
ANC_1_25>>ANC_1_30
ANC_1_25>>ANC_1_31
ANC_1_25>>ANC_1_35
ANC_1_25>>ANC_1_40
ANC_1_25>>ANC_1_41
ANC_1_25>>ANC_1_51
ANC_1_25>>ANC_1_55
ANC_1_25>>ANC_1_85
ANC_1_25>>ANC_1_92
ANC_1_30>>ANC_1_10
ANC_1_30>>ANC_1_11
ANC_1_30>>ANC_1_20
ANC_1_30>>ANC_1_25
ANC_1_30>>ANC_1_31
ANC_1_30>>ANC_1_35
ANC_1_30>>ANC_1_40
ANC_1_30>>ANC_1_41
ANC_1_30>>ANC_1_51
ANC_1_30>>ANC_1_85
ANC_1_30>>ANC_1_92
ANC_1_31>>ANC_1_10
ANC_1_31>>ANC_1_20
ANC_1_31>>ANC_1_25
ANC_1_31>>ANC_1_30
ANC_1_31>>ANC_1_92
ANC_1_35>>ANC_1_10
ANC_1_35>>ANC_1_11
ANC_1_35>>ANC_1_20
ANC_1_35>>ANC_1_25
ANC_1_35>>ANC_1_30
ANC_1_35>>ANC_1_40
ANC_1_35>>ANC_1_41
ANC_1_35>>ANC_1_55
ANC_1_35>>ANC_1_65
ANC_1_35>>ANC_1_85
ANC_1_35>>ANC_1_92
ANC_1_40>>ANC_1_10
ANC_1_40>>ANC_1_20
ANC_1_40>>ANC_1_25
ANC_1_40>>ANC_1_30
ANC_1_40>>ANC_1_35
ANC_1_40>>ANC_1_85
ANC_1_40>>ANC_1_92
ANC_1_41>>ANC_1_10
ANC_1_41>>ANC_1_20
ANC_1_41>>ANC_1_25
ANC_1_41>>ANC_1_30
ANC_1_41>>ANC_1_35
ANC_1_41>>ANC_1_85
ANC_1_41>>ANC_1_92
ANC_1_51>>ANC_1_10
ANC_1_51>>ANC_1_25
ANC_1_51>>ANC_1_30
ANC_1_55>>ANC_1_10
ANC_1_55>>ANC_1_20
ANC_1_55>>ANC_1_25
ANC_1_55>>ANC_1_35
ANC_1_55>>ANC_1_65
ANC_1_55>>ANC_1_85
ANC_1_65>>ANC_1_35
ANC_1_65>>ANC_1_55
ANC_1_65>>ANC_1_85
ANC_1_85>>ANC_1_10
ANC_1_85>>ANC_1_11
ANC_1_85>>ANC_1_20
ANC_1_85>>ANC_1_25
ANC_1_85>>ANC_1_30
ANC_1_85>>ANC_1_35
ANC_1_85>>ANC_1_40
ANC_1_85>>ANC_1_41
ANC_1_85>>ANC_1_55
ANC_1_85>>ANC_1_65
ANC_1_85>>ANC_1_92
ANC_1_92>>ANC_1_10
ANC_1_92>>ANC_1_11
ANC_1_92>>ANC_1_20
ANC_1_92>>ANC_1_25
ANC_1_92>>ANC_1_30
ANC_1_92>>ANC_1_31
ANC_1_92>>ANC_1_35
ANC_1_92>>ANC_1_40
ANC_1_92>>ANC_1_41
ANC_1_92>>ANC_1_85

In [46]:
missing_reverse_pairs

{'ANC_1_11>>ANC_1_10',
 'ANC_1_11>>ANC_1_20',
 'ANC_1_11>>ANC_1_25',
 'ANC_1_11>>ANC_1_30',
 'ANC_1_11>>ANC_1_35',
 'ANC_1_11>>ANC_1_85',
 'ANC_1_11>>ANC_1_92',
 'ANC_1_31>>ANC_1_10',
 'ANC_1_31>>ANC_1_20',
 'ANC_1_31>>ANC_1_25',
 'ANC_1_31>>ANC_1_30',
 'ANC_1_31>>ANC_1_92',
 'ANC_1_40>>ANC_1_10',
 'ANC_1_40>>ANC_1_20',
 'ANC_1_40>>ANC_1_25',
 'ANC_1_40>>ANC_1_30',
 'ANC_1_40>>ANC_1_35',
 'ANC_1_40>>ANC_1_85',
 'ANC_1_40>>ANC_1_92',
 'ANC_1_41>>ANC_1_10',
 'ANC_1_41>>ANC_1_20',
 'ANC_1_41>>ANC_1_25',
 'ANC_1_41>>ANC_1_30',
 'ANC_1_41>>ANC_1_35',
 'ANC_1_41>>ANC_1_85',
 'ANC_1_41>>ANC_1_92',
 'ANC_1_51>>ANC_1_10',
 'ANC_1_51>>ANC_1_25',
 'ANC_1_51>>ANC_1_30',
 'ANC_1_65>>ANC_1_35',
 'ANC_1_65>>ANC_1_55',
 'ANC_1_65>>ANC_1_85'}

In [47]:
get_distance_between_coordinates(61.176543,-149.966894,61.137654,-149.923467)

3.053005755865577